//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSString, UIImage, UIView, _TtC8AppStore11ArtworkView, _TtC8AppStore11DividerView, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore24DetailCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: previousTitleTextColor
    // Error parsing type: , name: previousSubtitleTextColor
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
    // Error parsing type: , name: imageView
    // Error parsing type: , name: imageMarginRight
    // Error parsing type: , name: accessoryView
    // Error parsing type: , name: accessoryType
    // Error parsing type: , name: topDivider
    // Error parsing type: , name: topDividerInsets
    // Error parsing type: , name: showTopDivider
    // Error parsing type: , name: bottomDivider
    // Error parsing type: , name: bottomDividerInsets
    // Error parsing type: , name: showBottomDivider
    // Error parsing type: , name: accessoryAction
    // Error parsing type: , name: backgroundSelectionView
    // Error parsing type: , name: isSelectable
    // Error parsing type: , name: disabled
    // Error parsing type: , name: selectionHandler
    // Error parsing type: , name: tapGestureRecognizer
}

+ (double)defaultImageRightMargin;
+ (double)defaultAccessoryMargin;
- (CDUnknownBlockType).cxx_destruct;
- (void)prepareForReuse;
- (void)didTapWithAccessoryView:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)wasTapped;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) CDUnknownBlockType selectionHandler; // @synthesize selectionHandler;
@property(nonatomic) _Bool disabled; // @synthesize disabled;
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;
@property(nonatomic) _Bool selected;
- (_Bool)isSelected;
@property(nonatomic) _Bool isSelectable; // @synthesize isSelectable;
@property(nonatomic, copy) CDUnknownBlockType accessoryAction; // @synthesize accessoryAction;
@property(nonatomic) _Bool showBottomDivider; // @synthesize showBottomDivider;
@property(nonatomic, retain) _TtC8AppStore11DividerView *bottomDivider; // @synthesize bottomDivider;
@property(nonatomic) _Bool showTopDivider; // @synthesize showTopDivider;
@property(nonatomic, retain) _TtC8AppStore11DividerView *topDivider; // @synthesize topDivider;
@property(nonatomic, retain) UIView *accessoryView; // @synthesize accessoryView;
@property(nonatomic, retain) UIImage *image;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *imageView; // @synthesize imageView;
@property(nonatomic, copy) NSString *subtitle;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic, copy) NSString *title;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *titleLabel; // @synthesize titleLabel;

@end

