//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, _TtC8AppStore11ArtworkView;

@interface _TtC8AppStore9QuoteView : UIView
{
    // Error parsing type: , name: leftQuote
    // Error parsing type: , name: rightQuote
    // Error parsing type: , name: quoteLabel
    // Error parsing type: , name: quoteGlyphs
    // Error parsing type: , name: creditLabel
    // Error parsing type: , name: artworkAspectRatio
    // Error parsing type: , name: artworkView
    // Error parsing type: , name: isFullWidthArtwork
    // Error parsing type: , name: artworkHasRoundedCorners
}

+ (double)cornerRadius;
+ (struct UIEdgeInsets)quoteTextInsets;
- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool artworkHasRoundedCorners; // @synthesize artworkHasRoundedCorners;
@property(nonatomic) _Bool isFullWidthArtwork; // @synthesize isFullWidthArtwork;
@property(nonatomic) _Bool showArtwork;
@property(nonatomic, retain) _TtC8AppStore11ArtworkView *artworkView; // @synthesize artworkView;
@property(nonatomic, copy) NSString *credit;
@property(nonatomic, copy) NSString *text;

@end

