//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC8AppStore33PresentationContextViewController : UIViewController
{
    // Error parsing type: , name: contextViewController
    // Error parsing type: , name: animatedContext
    // Error parsing type: , name: hasPresentedViewController
    // Error parsing type: , name: flowController
    // Error parsing type: , name: actionRunner
    // Error parsing type: , name: dismissOverride
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dismissViewControllerWithTransition:(int)arg1 completion:(CDUnknownBlockType)arg2;
@property(nonatomic, copy) CDUnknownBlockType dismissOverride; // @synthesize dismissOverride;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithPresentedViewController:(id)arg1 animated:(_Bool)arg2;

@end

