//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC8AppStore18AnnotationItemView : UIView
{
    // Error parsing type: , name: textLabel
    // Error parsing type: , name: subTextLabel
}

+ (double)preferredHeightFor:(id)arg1 subText:(id)arg2 pageTraits:(id)arg3 fitting:(struct CGSize)arg4;
- (CDUnknownBlockType).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(nonatomic, readonly) double lastBaselineFromBottom;
@property(nonatomic, readonly) double firstBaselineFromTop;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

