//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSArray;

@interface _TtC8AppStore33GladiatorValidationViewController : UITableViewController
{
    // Error parsing type: , name: events
    // Error parsing type: , name: gladiator
    // Error parsing type: , name: rules
    // Error parsing type: , name: ruleNames
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithEvents:(id)arg1;
@property(nonatomic, readonly) NSArray *events; // @synthesize events;

@end

