//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSError;

@interface _TtC8AppStore15ErrorShieldView : UIView
{
    // Error parsing type: , name: presenter
    // Error parsing type: , name: errorView
    // Error parsing type: , name: retryHandler
    // Error parsing type: , name: isQRCodeBadgingEnabled
    // Error parsing type: , name: diagnosticImageView
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic) _Bool isQRCodeBadgingEnabled; // @synthesize isQRCodeBadgingEnabled;
@property(nonatomic, copy) CDUnknownBlockType retryHandler; // @synthesize retryHandler;
@property(nonatomic, copy) NSError *error;
- (void)internetDidBecomeReachable;
- (void)reload;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)willMoveToWindow:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

