//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class _TtC8AppStore16DynamicTypeLabel, _TtC8AppStore16ReviewRatingView, _TtC8AppStore17DynamicTypeButton;

@interface _TtC8AppStore31ProductReviewCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: ratingView
    // Error parsing type: , name: dateLabel
    // Error parsing type: , name: usernameLabel
    // Error parsing type: , name: textLabel
    // Error parsing type: , name: reviewMoreButton
    // Error parsing type: , name: responseTitleLabel
    // Error parsing type: , name: responseDateLabel
    // Error parsing type: , name: responseTextLabel
    // Error parsing type: , name: responseMoreButton
    // Error parsing type: , name: reviewBackgroundColor
    // Error parsing type: , name: hasResponse
    // Error parsing type: , name: isReviewExpanded
    // Error parsing type: , name: isResponseExpanded
    // Error parsing type: , name: actionHandler
    // Error parsing type: , name: moreReviewTapHandler
    // Error parsing type: , name: moreResponseTapHandler
}

+ (double)cornerRadius;
+ (double)verticalContentMargin;
- (CDUnknownBlockType).cxx_destruct;
- (void)moreResponseFrom:(id)arg1;
- (void)moreReviewFrom:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType moreResponseTapHandler; // @synthesize moreResponseTapHandler;
@property(nonatomic, copy) CDUnknownBlockType moreReviewTapHandler; // @synthesize moreReviewTapHandler;
@property(nonatomic, copy) CDUnknownBlockType moreTapHandler;
- (void)stateChangedFor:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType actionHandler; // @synthesize actionHandler;
- (void)previewDidEnd;
- (void)previewWillBegin;
@property(nonatomic) _Bool isResponseExpanded; // @synthesize isResponseExpanded;
@property(nonatomic) _Bool isReviewExpanded; // @synthesize isReviewExpanded;
@property(nonatomic) _Bool hasResponse; // @synthesize hasResponse;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) _TtC8AppStore17DynamicTypeButton *responseMoreButton; // @synthesize responseMoreButton;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *responseTextLabel; // @synthesize responseTextLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *responseDateLabel; // @synthesize responseDateLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *responseTitleLabel; // @synthesize responseTitleLabel;
@property(nonatomic, readonly) _TtC8AppStore17DynamicTypeButton *reviewMoreButton; // @synthesize reviewMoreButton;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *textLabel; // @synthesize textLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *usernameLabel; // @synthesize usernameLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *dateLabel; // @synthesize dateLabel;
@property(nonatomic, readonly) _TtC8AppStore16ReviewRatingView *ratingView; // @synthesize ratingView;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *titleLabel; // @synthesize titleLabel;

@end

