//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore23SegmentedViewController.h"

#import "_TtP11AppStoreKit26TopChartsPagePresenterView_-Protocol.h"

@class _TtC8AppStore28SelectCategoryViewController;

@interface _TtC8AppStore27TopChartsPageViewController : _TtC8AppStore23SegmentedViewController <_TtP11AppStoreKit26TopChartsPagePresenterView_>
{
    // Error parsing type: , name: presenter
    // Error parsing type: , name: artworkLoader
    // Error parsing type: , name: overlayView
    // Error parsing type: , name: categoriesBarButton
    // Error parsing type: , name: selectCategoryViewController
    // Error parsing type: , name: segmentViewControllerLoaders
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)showWithUpdateError:(id)arg1;
- (void)hideLoading;
- (void)showLoading;
- (void)didReloadSegmentPresentersWithOldCount:(long long)arg1 newCount:(long long)arg2;
- (void)didChangeCategoriesButtonTitle;
- (void)didChangeTitle;
@property(nonatomic, retain) _TtC8AppStore28SelectCategoryViewController *selectCategoryViewController; // @synthesize selectCategoryViewController;
- (void)showCategoriesFor:(id)arg1;
@property(nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

