//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary;

@interface _TtC8AppStore11ArtworkGrid : UIView
{
    // Error parsing type: , name: gridType
    // Error parsing type: , name: artworkViews
    // Error parsing type: , name: artworkImages
    // Error parsing type: , name: expectedNumberOfArtworkImages
    // Error parsing type: , name: contentView
    // Error parsing type: , name: imageBorderView
    // Error parsing type: , name: showBorder
    // Error parsing type: , name: isLazyLayoutEnabled
    // Error parsing type: , name: lastVisibleBounds
    // Error parsing type: , name: nearestCollectionView
}

- (CDUnknownBlockType).cxx_destruct;
- (void)_observeScrollViewDidScroll:(id)arg1;
- (void)didMoveToWindow;
- (void)didMoveToSuperview;
@property(nonatomic) _Bool isLazyLayoutEnabled; // @synthesize isLazyLayoutEnabled;
- (void)resetImages;
- (void)setWithImage:(id)arg1 at:(long long)arg2;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool showBorder; // @synthesize showBorder;
@property(nonatomic) struct CGRect frame;
@property(nonatomic) long long expectedNumberOfArtworkImages; // @synthesize expectedNumberOfArtworkImages;
@property(nonatomic, copy) NSDictionary *artworkViews; // @synthesize artworkViews;

@end

