//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

@class UIView;
@protocol UICollectionViewDataSource, UICollectionViewDelegate;

@interface _TtC8AppStore29StoreCollectionViewController : UICollectionViewController
{
    // Error parsing type: , name: lifecycleObserver
    // Error parsing type: , name: registeredForApplicationDidBecomeActive
    // Error parsing type: , name: statusBarBackgroundView
    // Error parsing type: , name: overlayView
    // Error parsing type: , name: prefersLargeTitle
    // Error parsing type: , name: navigationAccessories
    // Error parsing type: , name: collectionViewDelegate
    // Error parsing type: , name: collectionViewDataSource
}

+ (double)navigationAccessoryMargin;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, retain) id <UICollectionViewDataSource> collectionViewDataSource; // @synthesize collectionViewDataSource;
@property(nonatomic, retain) id <UICollectionViewDelegate> collectionViewDelegate; // @synthesize collectionViewDelegate;
- (void)displayWithAccessoryView:(id)arg1;
- (void)updateNavigationBarForLargeTitleChange;
@property(nonatomic, readonly) _Bool prefersLargeTitleInNavigationBar;
@property(nonatomic) _Bool prefersLargeTitle; // @synthesize prefersLargeTitle;
@property(nonatomic, readonly) _Bool isTopLevelViewController;
@property(nonatomic, retain) UIView *overlayView; // @synthesize overlayView;
@property(nonatomic, retain) UIView *statusBarBackgroundView; // @synthesize statusBarBackgroundView;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)appExitedWhileAppeared;
- (void)appEnteredWhileAppeared;
@property(nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;

@end

