//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "_TtP11AppStoreKit29TrendingSearchesPresenterView_-Protocol.h"

@class UIView, UIVisualEffectView, _TtC8AppStore16SearchHeaderView;

@interface _TtC8AppStore19BaseSearchContainer : UIScrollView <_TtP11AppStoreKit29TrendingSearchesPresenterView_>
{
    // Error parsing type: , name: pageTraits
    // Error parsing type: , name: searchContainerDelegate
    // Error parsing type: , name: searchHeaderView
    // Error parsing type: , name: trendingSearchesTitle
    // Error parsing type: , name: trendingSearches
    // Error parsing type: , name: dimmingView
    // Error parsing type: , name: trendingSearchesPresenter
    // Error parsing type: , name: activeContentView
    // Error parsing type: , name: isTrendingEnabled
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UIView *accessibilityActiveContentView;
- (void)showWithUpdateError:(id)arg1;
- (void)hideLoading;
- (void)showLoading;
- (void)performWithAction:(id)arg1 sender:(id)arg2;
- (void)reloadData;
@property(nonatomic) _Bool isTrendingEnabled; // @synthesize isTrendingEnabled;
- (void)hideDimmingViewWithAnimate:(_Bool)arg1;
- (void)showDimmingViewWithAnimate:(_Bool)arg1;
- (void)dimmingViewTappedWithGestureRecognizer:(id)arg1;
- (void)didTapWithFilterButton:(id)arg1;
- (void)searchTermChagedWithTerm:(id)arg1;
- (void)searchCancelled;
- (void)searchSubmittedWithTerm:(id)arg1;
- (void)searchDidEndEditingWithTerm:(id)arg1;
- (void)searchDidBeginEditingWithTerm:(id)arg1;
- (void)setSearchTerm:(id)arg1 url:(id)arg2;
- (void)setContentWithView:(id)arg1 animated:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) UIVisualEffectView *searchHeaderVisualEffectView;
@property(nonatomic, readonly) _TtC8AppStore16SearchHeaderView *searchHeaderView; // @synthesize searchHeaderView;

@end

