//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIButton, _TtC8AppStore11ArtworkView, _TtC8AppStore11OfferButton, _TtC8AppStore16DynamicTypeLabel, _TtC8AppStore23ProductLockupBadgeStack;

@interface _TtC8AppStore31ProductLockupCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: appStateMachine
    // Error parsing type: , name: developerLabel
    // Error parsing type: , name: taglineLabel
    // Error parsing type: , name: offerButton
    // Error parsing type: , name: offerSubtitleLabel
    // Error parsing type: , name: moreButton
    // Error parsing type: , name: badgeStack
    // Error parsing type: , name: badgeReusePool
    // Error parsing type: , name: iconSize
    // Error parsing type: , name: artworkView
    // Error parsing type: , name: artworkLabelsPadMargin
    // Error parsing type: , name: artworkLabelsPhoneMargin
    // Error parsing type: , name: moreTapHandler
    // Error parsing type: , name: developerAction
    // Error parsing type: , name: changeSubtitleOnce.storage
    // Error parsing type: , name: lockupOfferAnimationCount
}

+ (double)offerButtonMinYDistanceFromBottomWithIsBadgeStackEmpty:(_Bool)arg1 traits:(id)arg2;
- (CDUnknownBlockType).cxx_destruct;
- (void)taglineLabelTapped:(id)arg1;
- (void)developerLabelTapped:(id)arg1;
- (void)moreTappedFrom:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType developerAction; // @synthesize developerAction;
@property(nonatomic, copy) CDUnknownBlockType moreTapHandler; // @synthesize moreTapHandler;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *artworkView; // @synthesize artworkView;
@property(nonatomic) struct CGSize iconSize; // @synthesize iconSize;
@property(nonatomic, readonly) _TtC8AppStore23ProductLockupBadgeStack *badgeStack; // @synthesize badgeStack;
@property(nonatomic, readonly) UIButton *moreButton; // @synthesize moreButton;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *offerSubtitleLabel; // @synthesize offerSubtitleLabel;
@property(nonatomic, readonly) _TtC8AppStore11OfferButton *offerButton; // @synthesize offerButton;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *taglineLabel; // @synthesize taglineLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *developerLabel; // @synthesize developerLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *titleLabel; // @synthesize titleLabel;

@end

