//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@interface _TtC8AppStore28SelectCategoryViewController : UINavigationController
{
    // Error parsing type: , name: listViewController
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithRootViewController:(id)arg1;
- (id)initWithNavigationBarClass:(Class)arg1 toolbarClass:(Class)arg2;
- (void)presentFrom:(id)arg1 in:(id)arg2 animated:(_Bool)arg3;
- (void)viewWillAppear:(_Bool)arg1;
@property(nonatomic, copy) CDUnknownBlockType selectionHandler;
- (id)initWithCoder:(id)arg1;

@end

