//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class _TtC8AppStore18VideoControlButton;

@interface _TtC8AppStore18ProgressBarControl : UIControl
{
    // Error parsing type: , name: videoControlButton
    // Error parsing type: , name: backgroundBar
    // Error parsing type: , name: progressBar
    // Error parsing type: , name: progressType
    // Error parsing type: , name: incrementalProgress
    // Error parsing type: , name: continuousProgress
    // Error parsing type: , name: displayLink
    // Error parsing type: , name: lastTimestamp
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateIncrementalProgress;
- (void)stop;
- (void)start;
- (void)updateProgressWithDisplayLink:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)didMoveToSuperview;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(nonatomic) long long incrementalProgress; // @synthesize incrementalProgress;
@property(nonatomic, copy) CDUnknownBlockType videoControlSelectionHandler;
@property(nonatomic) _Bool selected;
- (_Bool)isSelected;
@property(nonatomic, retain) _TtC8AppStore18VideoControlButton *videoControlButton; // @synthesize videoControlButton;

@end

