//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UICollectionView;
@protocol UICollectionViewDataSource, UICollectionViewDelegate;

@interface _TtC8AppStore23CollectionTableViewCell : UITableViewCell
{
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: delegate
    // Error parsing type: , name: collectionView
}

+ (id)reuseIdentifier;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic, retain) UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak id <UICollectionViewDelegate> delegate; // @synthesize delegate;
@property(nonatomic, retain) id <UICollectionViewDataSource> dataSource; // @synthesize dataSource;
- (void)layoutSubviews;
- (void)prepareForReuse;

@end

