//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class _TtC8AppStore11ArtworkView, _TtC8AppStore9QuoteView;

@interface _TtC8AppStore23QuoteCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: quoteView
    // Error parsing type: , name: preferredArtworkSize
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) struct CGSize preferredArtworkSize; // @synthesize preferredArtworkSize;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *artworkView;
@property(nonatomic, readonly) _TtC8AppStore9QuoteView *quoteView; // @synthesize quoteView;

@end

