//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore17DynamicTypeButton.h"

@class CAGradientLayer;

@interface _TtC8AppStore23FadeInDynamicTypeButton : _TtC8AppStore17DynamicTypeButton
{
    // Error parsing type: , name: fadeLayer
    // Error parsing type: , name: maximumFadeWidth
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic, readonly) double maximumFadeWidth; // @synthesize maximumFadeWidth;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) CAGradientLayer *fadeLayer; // @synthesize fadeLayer;

@end

