//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImage, UIImageView, UIView, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore33ProductPageLinkCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: iconImageView
    // Error parsing type: , name: textLabel
    // Error parsing type: , name: separatorView
    // Error parsing type: , name: iconImage
}

+ (double)regularIconBufferSpace;
+ (double)compactIconBufferSpace;
- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) _Bool isSeparatorDisplayed;
@property(nonatomic, retain) UIImage *iconImage; // @synthesize iconImage;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) UIView *separatorView; // @synthesize separatorView;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *textLabel; // @synthesize textLabel;
@property(nonatomic, retain) UIImageView *iconImageView; // @synthesize iconImageView;

@end

