//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class _TtC8AppStore11DividerView;

@interface _TtC8AppStore30TodayCardLockupListOverlayView : UIView
{
    // Error parsing type: , name: itemViews
    // Error parsing type: , name: reusePool
    // Error parsing type: , name: dividerView
    // Error parsing type: , name: lastSize
    // Error parsing type: , name: isExpanded
    // Error parsing type: , name: impressionableItemsFromLockups
    // Error parsing type: , name: impressionsReporter
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, copy) CDUnknownBlockType clickActionHandler;
@property(nonatomic) _Bool wantsCardConsistentMargins;
@property(nonatomic) _Bool isExpanded; // @synthesize isExpanded;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(nonatomic, retain) _TtC8AppStore11DividerView *dividerView; // @synthesize dividerView;
- (void)handleClickActionFor:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

