//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore29UpdatesCollectionViewDelegate.h"

@interface _TtC8AppStore29UpdatesCollectionViewDelegate (AppStore)
- (struct CGSize)collectionView:(id)arg1 sizeForEmptyStateViewIn:(id)arg2;
@property(nonatomic, readonly) _Bool shouldShowEmptyStateView;
- (_Bool)shouldShowDividerForItemAt:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 sizeForDividerViewIn:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForBackgroundAt:(long long)arg3;
- (_Bool)collectionView:(id)arg1 layout:(id)arg2 shouldProvideBackgroundAt:(long long)arg3;
@end

