//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore9BadgeView : UIView
{
    // Error parsing type: , name: valueLabel
    // Error parsing type: , name: valueView
    // Error parsing type: , name: badgeStackSize
    // Error parsing type: , name: valueViewAlignment
    // Error parsing type: , name: spacing
    // Error parsing type: , name: useCaptionTruncationFade
    // Error parsing type: , name: useValueTruncationFade
    // Error parsing type: , name: valueTruncationFadeLayer
    // Error parsing type: , name: captionTruncationFadeLayer
    // Error parsing type: , name: captionLabel
    // Error parsing type: , name: maximumTruncationFadeWidth
    // Error parsing type: , name: truncationFadeFactor
    // Error parsing type: , name: truncationFadeColor
    // Error parsing type: , name: leadingValue
    // Error parsing type: , name: caption
    // Error parsing type: , name: valueText
    // Error parsing type: , name: alignment
    // Error parsing type: , name: isTruncatable
    // Error parsing type: , name: captionCappingType
}

+ (double)heightWithTraits:(id)arg1 fitting:(double)arg2;
+ (double)heightFor:(id)arg1;
+ (id)badgeTintColor;
- (CDUnknownBlockType).cxx_destruct;
- (void)prepareForReuse;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(nonatomic) _Bool isTruncatable; // @synthesize isTruncatable;
@property(nonatomic) long long alignment; // @synthesize alignment;
@property(nonatomic, copy) NSString *valueText; // @synthesize valueText;
@property(nonatomic, copy) NSString *caption; // @synthesize caption;
- (void)tintColorDidChange;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *captionLabel; // @synthesize captionLabel;
@property(nonatomic, retain) UIView *valueView; // @synthesize valueView;
@property(nonatomic, retain) _TtC8AppStore16DynamicTypeLabel *valueLabel; // @synthesize valueLabel;

@end

