//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC8AppStore10ShadowView : UIView
{
    // Error parsing type: , name: cornerRadius
    // Error parsing type: , name: cornerStyle
    // Error parsing type: , name: shadow
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius;

@end

