//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface _TtC8AppStore17DynamicTypeButton : UIButton
{
    // Error parsing type: , name: fontUseCaseContentSizeCategory
    // Error parsing type: , name: fontUseCase
}

+ (id)adTransparencyButton;
+ (id)moreButtonWithBackgroundColor:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)traitCollectionDidChange:(id)arg1;

@end

