//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UILabel, UIView, _TtC8AppStore11ArtworkView;

@interface _TtC8AppStore31EditorialCardCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: artworkView
    // Error parsing type: , name: separatorView
    // Error parsing type: , name: separatorInset
    // Error parsing type: , name: captionLabel
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
@property(nonatomic, readonly) UILabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic, readonly) UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic, readonly) UILabel *captionLabel; // @synthesize captionLabel;
@property(nonatomic) struct UIEdgeInsets separatorInset; // @synthesize separatorInset;
@property(nonatomic, readonly) UIView *separatorView; // @synthesize separatorView;
@property(nonatomic, readonly) struct CGSize preferredArtworkSize;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *artworkView; // @synthesize artworkView;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

