//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIVisualEffectView;

@interface _TtC8AppStore20VideoControlBackdrop : UIView
{
    // Error parsing type: , name: primaryBackgroundView
    // Error parsing type: , name: contentView
    // Error parsing type: , name: groupName
}

+ (void)configureWithView:(id)arg1 withFillColor:(id)arg2 opacity:(double)arg3 filterType:(id)arg4;
+ (void)configureWithView:(id)arg1 withTintColor:(id)arg2 filterType:(id)arg3;
+ (void)applyTrackTextColorTo:(id)arg1;
+ (void)applyFilledTrackColorTo:(id)arg1;
+ (void)applyUnfilledTrackColorTo:(id)arg1;
+ (void)applyPrimaryGlyphTintTo:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, copy) NSString *groupName; // @synthesize groupName;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UIView *contentView; // @synthesize contentView;
@property(nonatomic, retain) UIVisualEffectView *primaryBackgroundView; // @synthesize primaryBackgroundView;

@end

