//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC8AppStore19RiverCardDataSource : SwiftObject
{
    // Error parsing type: , name: lockups
    // Error parsing type: , name: pageTraits
    // Error parsing type: , name: artworkLoader
}

@end

