//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITraitEnvironment-Protocol.h"

@class UITraitCollection;

@interface _TtC8AppStore28SnapshotPageTraitEnvironment : NSObject <UITraitEnvironment>
{
    // Error parsing type: , name: safeAreaLayoutMargin
    // Error parsing type: , name: traitCollection
    // Error parsing type: , name: containerSize
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) double pageColumnWidth;
@property(nonatomic, readonly) double pageColumnMargin;
@property(nonatomic, readonly) struct UIEdgeInsets pageMarginInsets;
@property(nonatomic, readonly) struct CGSize pageContainerSize;
- (void)traitCollectionDidChange:(id)arg1;
@property(nonatomic, readonly) struct CGSize containerSize; // @synthesize containerSize;
@property(nonatomic, readonly) UITraitCollection *traitCollection; // @synthesize traitCollection;
@property(nonatomic, readonly) struct NSDirectionalEdgeInsets safeAreaLayoutMargin; // @synthesize safeAreaLayoutMargin;
- (id)initWithContainerSize:(struct CGSize)arg1 safeAreaLayoutMargin:(struct NSDirectionalEdgeInsets)arg2 traitCollection:(id)arg3;

@end

