//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore18BaseFlowController.h"

@interface _TtC8AppStore20TabBarFlowController : _TtC8AppStore18BaseFlowController
{
    // Error parsing type: , name: tabBarController
    // Error parsing type: , name: loadingNavigationController
    // Error parsing type: , name: tabChangeDelegate
}

@end

