//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel;

@interface _TtC8AppStore21ProductCapabilityCell : UICollectionViewCell
{
    // Error parsing type: , name: iconImageView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: descriptionLabel
}

+ (struct CGSize)preferredImageSize;
+ (double)imageLabelMargin;
- (CDUnknownBlockType).cxx_destruct;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UILabel *descriptionLabel; // @synthesize descriptionLabel;
@property(nonatomic, readonly) UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic, readonly) UIImageView *iconImageView; // @synthesize iconImageView;

@end

