//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIProgressView, _TtC8AppStore16ReviewRatingView;

@interface _TtC8AppStore13RatingRowView : UIView
{
    // Error parsing type: , name: ratingView
    // Error parsing type: , name: barView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UIProgressView *accessibilityBarView;
@property(nonatomic, readonly) _TtC8AppStore16ReviewRatingView *accessibilityRatingView;
@property(nonatomic) float ratingProportion;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithRepresentedRating:(unsigned long long)arg1;

@end

