//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore27AnimatedTransitionWithTasks.h"

@interface _TtC8AppStore23BouncyFromRectAnimation : _TtC8AppStore27AnimatedTransitionWithTasks
{
    // Error parsing type: , name: fromRect
}

+ (double)settlingMagicScale;
+ (double)animationDuration;
- (id)init;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

@end

