//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8AppStore24ProductScrollCoordinator : NSObject
{
    // Error parsing type: , name: lockupDistance
    // Error parsing type: , name: modeChangeHandler
    // Error parsing type: , name: transitionMode
}

+ (double)transitionDurationWithVelocity:(double)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)didScrollIn:(id)arg1;
- (id)initWithModeChangeHandler:(CDUnknownBlockType)arg1;

@end

