//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, UITextView;

@interface _TtC8AppStore25RuleResultsViewController : UIViewController
{
    // Error parsing type: , name: rule
    // Error parsing type: , name: events
    // Error parsing type: , name: textView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, retain) UITextView *textView; // @synthesize textView;
@property(nonatomic, readonly) NSArray *events; // @synthesize events;

@end

