//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "CLLocationManagerDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"
#import "UIApplicationTestingDelegate-Protocol.h"

@class UIViewController, UIWindow;

@interface _TtC8AppStore11AppDelegate : UIResponder <CLLocationManagerDelegate, UIApplicationTestingDelegate, UIApplicationDelegate>
{
    // Error parsing type: , name: window
    // Error parsing type: , name: appHasBeenInBackground
    // Error parsing type: , name: eventWatchdoge
    // Error parsing type: , name: urlActionRunner
    // Error parsing type: , name: quickActionsController
    // Error parsing type: , name: pendingBootstrap
    // Error parsing type: , name: pptViewHierarchyProxy
    // Error parsing type: , name: flowController
    // Error parsing type: , name: adBootstrap
    // Error parsing type: , name: freshnessWatchdog
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) UIViewController *rootViewController;
- (void)didFinishAppBootstrap;
- (void)networkReachabilityDidChangeTo:(unsigned int)arg1;
- (void)networkActivityDidEnd;
- (void)networkActivityDidBegin;
- (void)handleDebugActivationFrom:(id)arg1;
- (void)performAfterBootstrapping:(CDUnknownBlockType)arg1;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
@property(nonatomic) _Bool appHasBeenInBackground; // @synthesize appHasBeenInBackground;
@property(nonatomic, retain) UIWindow *window; // @synthesize window;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)askForLocationPermissionIfNeeded;
- (_Bool)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;

@end

