//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIActivityItemProvider.h>

@interface _TtC8AppStore33NotesMetadataActivityItemProvider : UIActivityItemProvider
{
    // Error parsing type: , name: context
    // Error parsing type: , name: metadata
}

+ (id)notesShareMetadataUTI;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithPlaceholderItem:(id)arg1;
- (id)activityViewController:(id)arg1 dataTypeIdentifierForActivityType:(id)arg2;
@property(nonatomic, readonly) id item;

@end

