//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC8AppStore24UpdateAppStateDataSource : SwiftObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: accessQueue
    // Error parsing type: , name: observer
    // Error parsing type: , name: expectedAppStates
    // Error parsing type: , name: updateStore
}

- (void)updateStoreDidChange;

@end

