//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIInterfaceAction.h>

@interface _TtC8AppStore22ContextInterfaceAction : UIInterfaceAction
{
    // Error parsing type: , name: dismissHandler
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, copy) CDUnknownBlockType dismissHandler; // @synthesize dismissHandler;

@end

