//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore17RoundedCornerView.h"

@class UIColor, UIImage;

@interface _TtC8AppStore11ArtworkView : _TtC8AppStore17RoundedCornerView
{
    // Error parsing type: , name: imageView
    // Error parsing type: , name: shadowView
    // Error parsing type: , name: shadow
    // Error parsing type: , name: internalBackgroundColor
    // Error parsing type: , name: imageSize
    // Error parsing type: , name: isCornerRadiusInvalid
    // Error parsing type: , name: isStyleInvalid
    // Error parsing type: , name: style
}

+ (id)screenshotArtworkView;
+ (id)brickArtworkView;
+ (id)cardArtworkView;
+ (id)iapIconArtworkView;
+ (id)iconArtworkView;
+ (double)iconBorderWidth;
+ (id)iconBorderColor;
- (CDUnknownBlockType).cxx_destruct;
- (void)animateToImage:(id)arg1;
- (void)setImageWithImage:(id)arg1 animated:(_Bool)arg2;
@property(nonatomic, retain) UIImage *image;
@property(nonatomic) _Bool isImageHidden;
@property(nonatomic) _Bool accessibilityIgnoresInvertColors;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize;
@property(nonatomic) struct CGRect frame;
- (void)layoutSubviews;
@property(nonatomic, retain) UIColor *backgroundColor;
@property(nonatomic) unsigned long long roundedCorners;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

