//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtP11AppStoreKit19ActionPresenterView_-Protocol.h"
#import "_TtP11AppStoreKit23ReloadablePresenterView_-Protocol.h"

@class NSIndexPath, NSString;

@protocol _TtP11AppStoreKit29PurchasesContentPresenterView_ <_TtP11AppStoreKit19ActionPresenterView_, _TtP11AppStoreKit23ReloadablePresenterView_>
- (void)showEmptyStateWithTitle:(NSString *)arg1 description:(NSString *)arg2 canChangeModes:(_Bool)arg3 canSearch:(_Bool)arg4;
- (void)deleteWithIndexPath:(NSIndexPath *)arg1;
@end

