//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol AppLibraryNotificationDelegate;

@interface AppLibraryNotificationForwarder : NSObject
{
    id <AppLibraryNotificationDelegate> _delegate;
}

@property(readonly, nonatomic) __weak id <AppLibraryNotificationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

