//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSNumber, NSString, NSURL, SSBag;

@protocol ASKBag <NSObject>
@property(nonatomic, readonly) SSBag *underlyingBag;
@property(nonatomic, readonly) _Bool isContentGiftingEnabled;
@property(nonatomic, readonly) _Bool isMonetaryGiftingEnabled;
@property(nonatomic, readonly) NSNumber *numberOfPurchasesThreshold;
@property(nonatomic, readonly) double onboardingCardExpirationThreshold;
@property(nonatomic, readonly) NSDictionary *onboardingCardsMap;
@property(nonatomic, readonly) NSString *defaultAutoPlayVideoSetting;
@property(nonatomic, readonly) _Bool familyPurchasesEnabled;
@property(nonatomic, readonly) NSURL *familyPurchasesLearnMoreURL;
@property(nonatomic, readonly) NSURL *termsAndConditionsURL;
@property(nonatomic, readonly) NSURL *iForgotURL;
@property(nonatomic, readonly) NSURL *writeReviewURL;
@property(nonatomic, readonly) NSURL *userRateURL;
@property(nonatomic, readonly) _Bool personalizedUserReviewEnabled;
@property(nonatomic, readonly) NSURL *personalizedUserReviewUrl;
@property(nonatomic, readonly) double fastImpressionsTimeout;
@property(nonatomic, readonly) double impressionableViewablePercentage;
@property(nonatomic, readonly) double impressionableThreshold;
@property(nonatomic, readonly) double samplingPercentageUsersPageRender;
@property(nonatomic, readonly) double sessionDurationPageRender;
@property(nonatomic, readonly) NSDictionary *metricsConfiguration;
@property(nonatomic, readonly) _Bool usePostForAppStoreSearch;
@property(nonatomic, readonly) double adTargetingRefreshInterval;
@property(nonatomic, readonly) _Bool isSponsoredAdsEnabled;
@property(nonatomic, readonly) NSURL *searchHintsURL;
@property(nonatomic, readonly) NSURL *searchURL;
@property(nonatomic, readonly) NSURL *trendingSearchesURL;
@property(nonatomic, readonly) NSArray *rawStandardTabs;
@property(nonatomic, readonly) _Bool isQRCodeBadgingEnabled;
@property(nonatomic, readonly) NSURL *libraryLinkURL;
@property(nonatomic, readonly) NSURL *passbookMainURL;
@property(nonatomic, readonly) NSURL *accessoryRoomURL;
@property(nonatomic, readonly) double residentSessionMaximumAge;
@property(nonatomic, readonly) double fetchTimeout;
@property(nonatomic, readonly) NSString *language;
@property(nonatomic, readonly) NSString *storefrontSuffix;
@property(nonatomic, readonly) NSURL *appScriptURL;
@end

