//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ASReportAConcernReason : NSObject
{
    NSString *_reasonID;
    NSString *_name;
    NSString *_uppercaseName;
}

@property(copy, nonatomic) NSString *uppercaseName; // @synthesize uppercaseName=_uppercaseName;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *reasonID; // @synthesize reasonID=_reasonID;
- (void).cxx_destruct;

@end

