//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIInterfaceAction.h>

@interface UIInterfaceAction (AppStore)
- (id)initWithTitle:(id)arg1 image:(id)arg2 handler:(CDUnknownBlockType)arg3;
@end

