//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface _AKMessage : NSObject
{
    NSMutableDictionary *_properties;
}

+ (id)messageFromTransportRepresentation:(id)arg1;
+ (unsigned long long)typeForMessageWithTransportRepresentation:(id)arg1;
- (void).cxx_destruct;
- (id)transportRepresentation;
@property(readonly, nonatomic) unsigned long long type;
@property(readonly, nonatomic) NSString *identifier;
- (id)init;

@end

