//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AKAnisetteProvisioningDaemonProtocol-Protocol.h"

@class AKAppleIDAuthenticationContext, AKClient, AKNativeAnisetteService, NSString;

@interface AKAnisetteProvisioningService : NSObject <AKAnisetteProvisioningDaemonProtocol>
{
    AKClient *_client;
    AKAppleIDAuthenticationContext *_context;
    AKNativeAnisetteService *_nativeAnisetteService;
}

- (void).cxx_destruct;
- (id)_clientAnisetteService;
- (id)_pairedDeviceAnisetteService;
- (id)_nativeAnisetteService;
- (id)_helperServiceForDevice:(id)arg1;
- (void)eraseAnisetteForDevice:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)syncAnisetteWithSIMData:(id)arg1 device:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)provisionAnisetteForDevice:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)legacyAnisetteDataForDSID:(id)arg1 device:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchAnisetteDataAndProvisionIfNecessary:(_Bool)arg1 device:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)anisetteDataForDevice:(id)arg1 provisionIfNecessary:(_Bool)arg2;
- (id)initWithClient:(id)arg1 context:(id)arg2;
- (id)initWithClient:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

