//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSData, NSDictionary, NSURL;

@protocol AKAppleIDAuthSupportProxy <NSObject>
- (NSDictionary *)appleIDAuthSupportCopyAppTokensWithMasterToken:(struct __AppleIDAuthSupportTokenData *)arg1 authURL:(NSURL *)arg2 serviceIds:(NSArray *)arg3 authParams:(NSDictionary *)arg4 error:(id *)arg5;
- (struct __AppleIDAuthSupportTokenData *)appleIDAuthSupportTokenCreateWithExternalizedVersion:(NSData *)arg1 error:(id *)arg2;
@end

