//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AKAppleIDAuthSupportProxy-Protocol.h"

@class NSString;

@interface AKAppleIDAuthSupportProxyImpl : NSObject <AKAppleIDAuthSupportProxy>
{
}

- (id)appleIDAuthSupportCopyAppTokensWithMasterToken:(struct __AppleIDAuthSupportTokenData *)arg1 authURL:(id)arg2 serviceIds:(id)arg3 authParams:(id)arg4 error:(id *)arg5;
- (struct __AppleIDAuthSupportTokenData *)appleIDAuthSupportTokenCreateWithExternalizedVersion:(id)arg1 error:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

