//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "APSConnectionDelegate-Protocol.h"

@class AKAccountManager, APSConnection, NSHashTable, NSLock, NSMutableDictionary, NSMutableSet, NSString;
@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface AKAppleIDPushHelperService : NSObject <APSConnectionDelegate>
{
    APSConnection *_apsConnection;
    NSString *_activeAPSEnvironment;
    AKAccountManager *_accountManager;
    NSObject<OS_dispatch_queue> *_pushServiceQueue;
    NSMutableDictionary *_notificationsByPushID;
    NSMutableSet *_pigNotifications;
    NSLock *_notificationsByPushIDLock;
    NSObject<OS_dispatch_semaphore> *_apsTokenSemaphore;
    NSString *_loginCodeNotificationID;
    NSHashTable *_weakPushDelegates;
    NSString *_activeCode;
}

+ (id)sharedService;
@property(copy, nonatomic) NSString *activeCode; // @synthesize activeCode=_activeCode;
- (void).cxx_destruct;
- (void)_receiveResponseFromNotification:(struct __CFUserNotification *)arg1 handler:(CDUnknownBlockType)arg2;
- (void)_populateNotificationOptionsWithCommonKeys:(id)arg1 makeNoise:(_Bool)arg2;
- (void)_promptForChangePasswordForAccount:(id)arg1;
- (struct __CFUserNotification *)_createUserNotificationWithTitle:(id)arg1 body:(id)arg2 defaultButtonTitle:(id)arg3 alternateButtonTitle:(id)arg4 makeNoise:(_Bool)arg5;
- (void)_tearDownNotificationWithID:(id)arg1;
- (void)_showNotification:(struct __CFUserNotification *)arg1 withIdentifier:(id)arg2 responseHandler:(CDUnknownBlockType)arg3;
- (struct __CFUserNotification *)_loginNotificationWithContext:(id)arg1 isSilent:(_Bool)arg2 defaultButtonTitle:(id)arg3 alternateButtonTitle:(id)arg4;
- (void)_showNotificationForMessage:(id)arg1 account:(id)arg2 responseHandler:(CDUnknownBlockType)arg3;
- (void)_locationNameWithLatitude:(id)arg1 longitude:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_startChangePasswordFlowForAccount:(id)arg1;
- (void)_startPasswordResetFlowForAccount:(id)arg1;
- (void)_showTrustedDevicesForAccount:(id)arg1;
- (_Bool)_awaitResponseForNotification:(struct __CFUserNotification *)arg1;
- (void)_showLoginNotificationWithCode:(id)arg1 incomingMessage:(id)arg2 piggy:(_Bool)arg3;
- (void)tearDownLoginNotifications;
- (void)showPigCode:(id)arg1 withIncomingMessage:(id)arg2;
- (void)_generateLoginCodeForAccount:(id)arg1 withIncomingMessage:(id)arg2;
- (void)tearDownNotificationWithPayload:(id)arg1 account:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (unsigned long long)notificationResultFromUserResponse:(_Bool)arg1;
- (unsigned long long)notificationResultFromButtonPressed:(unsigned long long)arg1;
- (void)_notifyServerAboutUserResponseToPushMessageWithID:(id)arg1 command:(unsigned long long)arg2 account:(id)arg3 result:(unsigned long long)arg4;
- (void)_performCommandForMessage:(id)arg1 forAccount:(id)arg2;
- (_Bool)_messageSupportsAlerts:(id)arg1;
- (void)_presentMessage:(id)arg1 withPushMessageId:(id)arg2 withCommand:(unsigned long long)arg3 forAccount:(id)arg4;
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;
- (id)_publicAPSToken;
- (id)publicAPSTokenString;
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;
- (void)connectionDidReconnect:(id)arg1;
- (void)connection:(id)arg1 didChangeConnectedStatus:(_Bool)arg2;
- (void)registerForPushesWithAccount:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (void)_ensureDesiredAPSEnvironmentIsInUse;
- (void)_performHeartbeatCheck:(_Bool)arg1;
- (void)_performHeartbeatCheckInIfNecessary;
- (void)performHeartbeatCheck;
- (void)_processMessageWithDelegates:(id)arg1;
- (_Bool)_queryDelegatesForSuppressAction:(id)arg1;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (void)start;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

