//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface AKAppleIDUserInformationResponse : NSObject
{
    _Bool _isUnderage;
    _Bool _isLegacyStudent;
    unsigned long long _appleIDSecurityLevel;
    NSString *_masterKeyID;
    NSArray *_emailList;
}

@property(readonly, copy) NSArray *emailList; // @synthesize emailList=_emailList;
@property(readonly, copy) NSString *masterKeyID; // @synthesize masterKeyID=_masterKeyID;
@property(readonly) _Bool isLegacyStudent; // @synthesize isLegacyStudent=_isLegacyStudent;
@property(readonly) _Bool isUnderage; // @synthesize isUnderage=_isUnderage;
@property(readonly) unsigned long long appleIDSecurityLevel; // @synthesize appleIDSecurityLevel=_appleIDSecurityLevel;
- (void).cxx_destruct;
@property(readonly, copy) NSDictionary *dictionaryRepresentation;
- (id)initWithResponseBody:(id)arg1;

@end

