//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AKAccountManager, AKAppleIDAuthenticationContext, AKClient, NSLock, NSUUID;
@protocol OS_dispatch_queue;

@interface AKAuthenticationUILiaison : NSObject
{
    NSUUID *_surrogateCheckinID;
    NSLock *_surrogateCheckinIDLock;
    AKAppleIDAuthenticationContext *_surrogateContext;
    AKClient *_surrogateClient;
    NSObject<OS_dispatch_queue> *_surrogateQueue;
    AKAppleIDAuthenticationContext *_pendingBGContext;
    CDUnknownBlockType _pendingClientUIWork;
    NSObject<OS_dispatch_queue> *_clientUIWorkQueue;
    AKAccountManager *_accountManager;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (_Bool)_isFullUICapabilityRequiredFor2FA;
- (_Bool)_launchUISurrogateForContext:(id)arg1 withCheckinID:(id)arg2;
- (id)_stringByAppendingBlameIfNecessary:(id)arg1 withContext:(id)arg2 client:(id)arg3;
- (id)_optionsForCreatingUserNotificationWithTitle:(id)arg1 message:(id)arg2 defaultButton:(id)arg3 alternateButton:(id)arg4;
- (void)_showAlertForSettingsLoginIfNecessaryWithContext:(id)arg1 client:(id)arg2 needFullUI:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (_Bool)_isSettingsForeground;
- (_Bool)_isBackgroundClient:(id)arg1 eligibleForForegroundAuthenticationWithContext:(id)arg2;
- (void)_performBlockWithClient:(id)arg1 context:(id)arg2 requireFullUICapability:(_Bool)arg3 allowRedirectToSettings:(_Bool)arg4 block:(CDUnknownBlockType)arg5;
- (void)unregisterUISurrogateContext:(id)arg1 client:(id)arg2;
- (void)registerUISurrogateContext:(id)arg1 client:(id)arg2;
- (void)dismissNativeRecoveryUIForContext:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)presentNativeRecoveryUIForContext:(id)arg1 recoveryContext:(id)arg2 client:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)dismissServerProvidedUIForContext:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)presentServerProvidedUIForContext:(id)arg1 client:(id)arg2 URLRequest:(id)arg3 delegate:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)presentSecondFactorAlertForContext:(id)arg1 client:(id)arg2 withError:(id)arg3 title:(id)arg4 message:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)dismissSecondFactorUIForContext:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)presentSecondFactorUIForContext:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)presentLoginAlertForContext:(id)arg1 client:(id)arg2 withError:(id)arg3 title:(id)arg4 message:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)dismissBasicLoginUIForContext:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)presentBasicLoginUIForContext:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismissKeepUsingUIForContext:(id)arg1 client:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)presentKeepUsingUIForContext:(id)arg1 client:(id)arg2 appleID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)init;

@end

