//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AKDServerUIContext, NSDictionary;

@protocol AKDServerUIDelegate <NSObject>
- (void)serverUIContext:(AKDServerUIContext *)arg1 processAdditionalData:(NSDictionary *)arg2 completion:(void (^)(AKAuthenticationServerResponse *, NSDictionary *, NSError *))arg3;
- (_Bool)shouldProcessAdditionalServerUIData:(NSDictionary *)arg1;
@end

