//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AKAppleIDAuthenticationContext, AKAppleIDServerResourceLoadDelegate, AKAuthenticationServerResponse, NSURLRequest;

@interface AKDServerUIContext : NSObject
{
    NSURLRequest *_urlRequest;
    AKAppleIDAuthenticationContext *_authContext;
    AKAppleIDServerResourceLoadDelegate *_loadDelegate;
    AKAuthenticationServerResponse *_initiatingServerResponse;
}

@property(retain, nonatomic) AKAuthenticationServerResponse *initiatingServerResponse; // @synthesize initiatingServerResponse=_initiatingServerResponse;
@property(retain, nonatomic) AKAppleIDServerResourceLoadDelegate *loadDelegate; // @synthesize loadDelegate=_loadDelegate;
@property(retain, nonatomic) AKAppleIDAuthenticationContext *authContext; // @synthesize authContext=_authContext;
@property(copy, nonatomic) NSURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
- (void).cxx_destruct;

@end

