//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AKAuthenticationUILiaison, AKClient;
@protocol AKDServerUIDelegate;

@interface AKDServerUIController : NSObject
{
    AKAuthenticationUILiaison *_authUILiaison;
    id <AKDServerUIDelegate> _delegate;
    AKClient *_client;
}

- (void).cxx_destruct;
- (id)getServerUILoadDelegateWithContext:(id)arg1 error:(id *)arg2;
- (void)showServerUIWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithLiaison:(id)arg1 client:(id)arg2 delegate:(id)arg3;
- (id)initWithClient:(id)arg1;

@end

