//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AKAppleIDPushHelperServiceDelegate-Protocol.h"

@class NSString;
@protocol AKFollowUpControllerServiceProvider, AKFollowUpItemFactory, AKFollowUpProvider;

@interface AKFollowUpController : NSObject <AKAppleIDPushHelperServiceDelegate>
{
    id <AKFollowUpItemFactory> _factory;
    id <AKFollowUpProvider> _provider;
    id <AKFollowUpControllerServiceProvider> _serviceProvider;
}

+ (id)sharedController;
@property(retain, nonatomic) id <AKFollowUpControllerServiceProvider> serviceProvider; // @synthesize serviceProvider=_serviceProvider;
- (void).cxx_destruct;
- (void)_notifyServerOfTeardownWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)teardownFollowUpWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_alignedInsertionCandidates:(id)arg1 withExistingItems:(id)arg2;
- (_Bool)_synchronizeLocalFollowUpsWithServerPayload:(id)arg1 altDSID:(id)arg2 error:(id *)arg3;
- (void)_processFetchCompletionForAltDSID:(id)arg1 items:(id)arg2 fetchError:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_refreshFollowUpsWithIdmsInfo:(id)arg1 context:(id)arg2 authHandler:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_refreshFollowUpsWithIdmsInfo:(id)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)synchronizeFollowUpItemsForContext:(id)arg1 authHandler:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)processPushMessage:(id)arg1;
- (_Bool)shouldSuppressPushMessage:(id)arg1;
- (id)initWithFollowUpFactory:(id)arg1 provider:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

