//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AKPiggybackRequestingController, NSError, NSNumber;

@protocol AKPiggybackRequestingControllerDelegate <NSObject>
- (void)piggyback:(AKPiggybackRequestingController *)arg1 handleEscapeHatchError:(NSError *)arg2 completion:(void (^)(NSDictionary *, NSError *))arg3;
- (void)piggyback:(AKPiggybackRequestingController *)arg1 shouldContinueWithCompletion:(void (^)(NSDictionary *, NSError *))arg2;
- (void)piggyback:(AKPiggybackRequestingController *)arg1 validateSecurityCode:(NSNumber *)arg2 completion:(void (^)(AKAuthenticationServerResponse *, NSError *))arg3;
- (void)piggyback:(AKPiggybackRequestingController *)arg1 handleVerificationWithError:(NSError *)arg2 completion:(void (^)(NSNumber *, NSError *))arg3;
- (void)piggyback:(AKPiggybackRequestingController *)arg1 promptForRandomCodeWithCompletion:(void (^)(NSNumber *, NSError *))arg2;
@end

