//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AKAppleIDPushHelperServiceDelegate-Protocol.h"

@class AKPiggybackRequestingController, NSMutableDictionary, NSOperationQueue, NSString;
@protocol OS_dispatch_queue;

@interface AKPiggybackController : NSObject <AKAppleIDPushHelperServiceDelegate>
{
    NSMutableDictionary *_acceptingControllers;
    NSMutableDictionary *_pendingReplies;
    AKPiggybackRequestingController *_requestingController;
    NSObject<OS_dispatch_queue> *_replyProcessingQueue;
    NSOperationQueue *_circleRequestProcessingQueue;
    _Bool _requiresHSA2Repair;
}

+ (_Bool)payloadIndicatesHSA2RepairNeeded:(id)arg1;
+ (void)tearDown;
+ (id)sharedController;
- (void).cxx_destruct;
- (double)_processingTimeOut;
- (id)performCircleRequestWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)serviceControllerForContext:(id)arg1;
- (void)startRequestSessionWithController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_removeAcceptingControllerForTransaction:(id)arg1;
- (id)_acceptingControllerForTransactionId:(id)arg1;
- (_Bool)_processPendingCompletionsForPayload:(id)arg1;
- (_Bool)_hasPrimaryiCloudAccountForPayload:(id)arg1;
- (void)_processPiggybackPayload:(id)arg1;
- (void)processPushMessage:(id)arg1;
- (_Bool)shouldSuppressPushMessage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

