//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "KCJoiningAcceptSecretDelegate-Protocol.h"

@class AKCircleRequestPayload, KCJoiningAcceptAccountCircleDelegate, KCJoiningAcceptSession, NSLock;

@interface AKPiggybackAcceptingController : NSObject <KCJoiningAcceptSecretDelegate>
{
    AKCircleRequestPayload *_lastPayload;
    AKCircleRequestPayload *_initiatingPayload;
    long long _verificationAttempts;
    KCJoiningAcceptAccountCircleDelegate *_circleDelegate;
    _Bool _verificationFailed;
    struct __MKBAssertion *_assertionRef;
    NSLock *_assertionLock;
    KCJoiningAcceptSession *_acceptSession;
}

+ (_Bool)isInCircle;
@property(retain, nonatomic) KCJoiningAcceptSession *acceptSession; // @synthesize acceptSession=_acceptSession;
- (void).cxx_destruct;
- (void)_releaseAssertion;
- (void)_grabLockAssertion;
- (id)_generateSecret;
- (id)accountCode;
- (int)verificationFailed:(id *)arg1;
- (id)secret;
- (_Bool)isDone;
- (id)_authKitAccountForPayload:(id)arg1;
- (id)replyContextWithPayload:(id)arg1;
- (id)_acceptSessionForPayload:(id)arg1 error:(id *)arg2;
- (void)processPushPayload:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

