//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class APSIncomingMessage, NSDictionary, NSNumber, NSString;

@interface AKPushMessage : NSObject
{
    _Bool _isSilent;
    APSIncomingMessage *_message;
    unsigned long long _command;
    NSString *_messageId;
    NSString *_previousMessageId;
    NSString *_altDSID;
    NSDictionary *_userInfo;
    NSDictionary *_alertInfo;
    NSString *_alertTitle;
    NSString *_alertBody;
    NSString *_defaultButtonTitle;
    NSString *_alternateButtonTitle;
    NSString *_secondaryTitle;
    NSString *_secondaryBody;
    NSDictionary *_eventDetails;
    NSNumber *_latitude;
    NSNumber *_longitude;
    NSString *_deviceClass;
    NSString *_deviceColor;
    NSString *_deviceEnclosureColor;
}

@property(readonly, nonatomic) NSString *deviceEnclosureColor; // @synthesize deviceEnclosureColor=_deviceEnclosureColor;
@property(readonly, nonatomic) NSString *deviceColor; // @synthesize deviceColor=_deviceColor;
@property(readonly, nonatomic) NSString *deviceClass; // @synthesize deviceClass=_deviceClass;
@property(readonly, nonatomic) NSNumber *longitude; // @synthesize longitude=_longitude;
@property(readonly, nonatomic) NSNumber *latitude; // @synthesize latitude=_latitude;
@property(readonly, nonatomic) NSDictionary *eventDetails; // @synthesize eventDetails=_eventDetails;
@property(readonly, nonatomic) _Bool isSilent; // @synthesize isSilent=_isSilent;
@property(readonly, nonatomic) NSString *secondaryBody; // @synthesize secondaryBody=_secondaryBody;
@property(readonly, nonatomic) NSString *secondaryTitle; // @synthesize secondaryTitle=_secondaryTitle;
@property(readonly, nonatomic) NSString *alternateButtonTitle; // @synthesize alternateButtonTitle=_alternateButtonTitle;
@property(readonly, nonatomic) NSString *defaultButtonTitle; // @synthesize defaultButtonTitle=_defaultButtonTitle;
@property(readonly, nonatomic) NSString *alertBody; // @synthesize alertBody=_alertBody;
@property(readonly, nonatomic) NSString *alertTitle; // @synthesize alertTitle=_alertTitle;
@property(readonly, nonatomic) NSDictionary *alertInfo; // @synthesize alertInfo=_alertInfo;
@property(readonly, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(readonly, nonatomic) NSString *altDSID; // @synthesize altDSID=_altDSID;
@property(readonly, nonatomic) NSString *previousMessageId; // @synthesize previousMessageId=_previousMessageId;
@property(readonly, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(readonly, nonatomic) unsigned long long command; // @synthesize command=_command;
@property(readonly, nonatomic) APSIncomingMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (id)initWithMessage:(id)arg1;

@end

