//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AKAppleIDPushHelperServiceDelegate-Protocol.h"

@class AKAccountManager, NSString;

@interface AKUserInfoController : NSObject <AKAppleIDPushHelperServiceDelegate>
{
    AKAccountManager *_accountManager;
}

+ (id)sharedController;
- (void).cxx_destruct;
- (void)_sendNotification:(id)arg1 withValue:(unsigned long long)arg2 altDSID:(id)arg3;
- (void)_saveAccount:(id)arg1;
- (void)handleSecurityLevelChangeForAccount:(id)arg1 previousSecurity:(unsigned long long)arg2 newSecurity:(unsigned long long)arg3;
- (void)_processIncomingUserInformationForAltDSID:(id)arg1 userInformation:(id)arg2;
- (void)processPushMessage:(id)arg1;
- (_Bool)shouldSuppressPushMessage:(id)arg1;
- (void)refreshAccountUsernamesForAltDSID:(id)arg1;
- (void)_broadcastEmailChangeNotification;
- (void)_updateAccount:(id)arg1 withRefreshedEmails:(id)arg2 altDSID:(id)arg3 modifyAliases:(_Bool)arg4;
- (void)_setLastEmailListRequestDate:(id)arg1;
- (id)lastEmailListRequestDate;
- (void)refreshAccountUsernamesForAltDSID:(id)arg1 withNewEmailList:(id)arg2;
- (void)fetchUserInformationForAltDSID:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

