//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Typedef'd Structures

typedef struct {
    void *_field1;
    char *_field2;
    char *_field3;
    long long _field4;
    unsigned int _field5;
    int _field6;
    int _field7;
    int _field8;
    int _field9;
} CDStruct_05e9b5e4;

