//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface DataArk : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_store;
    NSMutableDictionary *_set_notifications;
    NSMutableDictionary *_change_notifications;
    NSMutableDictionary *_remove_notifications;
    NSString *_path;
}

@property(retain) NSString *path; // @synthesize path=_path;
@property(retain) NSMutableDictionary *remove_notifications; // @synthesize remove_notifications=_remove_notifications;
@property(retain) NSMutableDictionary *change_notifications; // @synthesize change_notifications=_change_notifications;
@property(retain) NSMutableDictionary *set_notifications; // @synthesize set_notifications=_set_notifications;
@property(retain) NSMutableDictionary *store; // @synthesize store=_store;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (id)init;

@end

