//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DeviceType : NSObject
{
    _Bool _is_fpga;
    _Bool _has_telephony;
    _Bool _should_hactivate;
    NSString *_product_type;
    NSString *_device_class;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool should_hactivate; // @synthesize should_hactivate=_should_hactivate;
@property(nonatomic) _Bool has_telephony; // @synthesize has_telephony=_has_telephony;
@property(nonatomic) _Bool is_fpga; // @synthesize is_fpga=_is_fpga;
@property(copy, nonatomic) NSString *device_class; // @synthesize device_class=_device_class;
@property(copy, nonatomic) NSString *product_type; // @synthesize product_type=_product_type;
- (void).cxx_destruct;
- (id)copyDeviceTreeInt:(id)arg1 key:(id)arg2 defaultValue:(int)arg3;
- (id)copyDeviceTreeProperty:(id)arg1 key:(id)arg2;

@end

