//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSDictionary;

@protocol MobileActivationProtocol <NSObject>
- (void)isInFieldCollectedWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)issueClientCertificateWithReferenceKey:(NSData *)arg1 options:(NSDictionary *)arg2 completion:(void (^)(NSDictionary *, NSError *))arg3;
- (void)issueClientCertificateLegacy:(NSData *)arg1 WithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg2;
- (void)handleActivationInfoWithSession:(NSData *)arg1 activationSignature:(NSData *)arg2 completionBlock:(void (^)(NSDictionary *, NSError *))arg3;
- (void)recertifyDevice:(_Bool)arg1 WithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg2;
- (void)unbrickDeviceWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)copyActivationRecordWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)copyRegulatoryImagesWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)handleReCertInfo:(NSDictionary *)arg1 withCompletionBlock:(void (^)(NSDictionary *, NSError *))arg2;
- (void)createReCertInfoWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)getActivationBuildWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)getActivationStateWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)requestDeviceReactivationWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)deactivateDeviceWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)isDeviceBrickedWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)copyPCRTTokenWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)copyUCRTTokenWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)copyUCRTWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)handleActivationInfo:(NSDictionary *)arg1 withCompletionBlock:(void (^)(NSDictionary *, NSError *))arg2;
- (void)createActivationInfoWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)createTunnel1SessionInfoWithCompletionBlock:(void (^)(NSDictionary *, NSError *))arg1;
- (void)createTunnel1ActivationInfo:(NSData *)arg1 options:(NSDictionary *)arg2 withCompletionBlock:(void (^)(NSDictionary *, NSError *))arg3;
@end

