//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DataArk;

@interface MobileRecertifyEngine : NSObject
{
    _Bool _storebagRecert;
    DataArk *_dark;
}

@property(nonatomic) _Bool storebagRecert; // @synthesize storebagRecert=_storebagRecert;
@property(retain, nonatomic) DataArk *dark; // @synthesize dark=_dark;
- (void).cxx_destruct;
- (_Bool)recertifyDevice:(id *)arg1;
- (_Bool)recertifyDeviceWithURL:(id)arg1 andKey:(id)arg2 andSession:(id)arg3 error:(id *)arg4;
- (_Bool)recertifyDeviceWithURL:(id)arg1 error:(id *)arg2;

@end

