//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RUITableViewRowDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AATrustedDevice, ACAccount, ACAccountStore, NSDictionary, NSString, RUIPage, UITableView;
@protocol AAUIFMIPHeaderDeviceInfoPageDelegate, UITableViewDelegate><UITableViewDataSource;

@interface AAUIFMIPHeaderDeviceInfoPageSurrogate : NSObject <UITableViewDelegate, RUITableViewRowDelegate, UITableViewDataSource>
{
    NSObject<UITableViewDelegate><UITableViewDataSource> *_remoteTableViewController;
    UITableView *_remoteTableView;
    ACAccountStore *_accountStore;
    ACAccount *_account;
    RUIPage *_remoteUIPage;
    AATrustedDevice *_device;
    NSDictionary *_remoteClientInfo;
    id <AAUIFMIPHeaderDeviceInfoPageDelegate> _delegate;
}

@property(nonatomic) __weak id <AAUIFMIPHeaderDeviceInfoPageDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)refreshBackupDetailText:(id)arg1;
- (void)updateDetailLabelWithBackup:(id)arg1;
- (id)backupForUDID:(id)arg1;
- (id)_dateStringOfLatestBackup:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)cellWithTag:(long long)arg1;
- (id)_footerForBackupRow;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)dealloc;
- (id)initWithPage:(id)arg1 device:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

