//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Preferences/PSTableCell.h>

@class UILabel;

@interface AAUISpecifierWithAlertCell : PSTableCell
{
    UILabel *alertTitle;
    UILabel *alertSubtitle;
}

+ (long long)cellStyle;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

