//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, _TtC11AppStoreKit7Artwork;

@interface _TtC11AppStoreKit6Action : NSObject
{
    // Error parsing type: , name: title
    // Error parsing type: , name: artwork
    // Error parsing type: , name: presentationStyle
    // Error parsing type: , name: metricsEvents
    // Error parsing type: , name: impressionFields
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) id clickSender;
@property(nonatomic, readonly) _TtC11AppStoreKit6Action *clickAction;
@property(nonatomic, readonly) unsigned long long presentationStyle; // @synthesize presentationStyle;
@property(nonatomic, readonly) _TtC11AppStoreKit7Artwork *artwork; // @synthesize artwork;
@property(nonatomic, readonly) NSString *title; // @synthesize title;

@end

