//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@class NSString, NSURL;

@interface _TtC11AppStoreKit12SearchAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: origin
    // Error parsing type: , name: term
    // Error parsing type: , name: url
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) NSURL *url; // @synthesize url;
@property(nonatomic, readonly) NSString *term; // @synthesize term;

@end

