//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, NSURL, _TtC11AppStoreKit6Action;

@interface _TtC11AppStoreKit5Shelf : NSObject
{
    // Error parsing type: , name: contentType
    // Error parsing type: , name: title
    // Error parsing type: , name: subtitle
    // Error parsing type: , name: seeAllAction
    // Error parsing type: , name: isHorizontal
    // Error parsing type: , name: items
    // Error parsing type: , name: url
    // Error parsing type: , name: isHidden
    // Error parsing type: , name: isPersonalized
    // Error parsing type: , name: backgroundColor
    // Error parsing type: , name: rowsPerColumn
    // Error parsing type: , name: accessoryModel
    // Error parsing type: , name: accessoryContentType
    // Error parsing type: , name: presentationHints
    // Error parsing type: , name: impressionFields
    // Error parsing type: , name: mergeWhenFetched
    // Error parsing type: , name: allArtwork
    // Error parsing type: , name: personalizationStyles
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _Bool containsPersonalizableItems;
- (id)initWithMerging:(id)arg1 with:(id)arg2;
@property(nonatomic, readonly) NSArray *allArtwork; // @synthesize allArtwork;
@property(nonatomic, readonly) _Bool mergeWhenFetched; // @synthesize mergeWhenFetched;
@property(nonatomic, readonly) long long rowsPerColumn; // @synthesize rowsPerColumn;
@property(nonatomic, readonly) _Bool isPersonalized; // @synthesize isPersonalized;
@property(nonatomic, readonly) _Bool isHidden; // @synthesize isHidden;
@property(nonatomic, readonly) NSURL *url; // @synthesize url;
@property(nonatomic, readonly) _Bool isHorizontal; // @synthesize isHorizontal;
@property(nonatomic, readonly) _TtC11AppStoreKit6Action *seeAllAction; // @synthesize seeAllAction;
@property(nonatomic, readonly) NSString *subtitle; // @synthesize subtitle;
@property(nonatomic, readonly) NSString *title; // @synthesize title;
@property(nonatomic, readonly) long long contentType; // @synthesize contentType;

@end

