//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@interface _TtC11AppStoreKit11LocalAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: handler
}

- (CDUnknownBlockType).cxx_destruct;
- (void)perform;
- (id)initWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;

@end

