//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC11AppStoreKit19ShelfContentTypeSet : NSObject
{
    // Error parsing type: , name: contents
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, readonly) NSString *debugDescription;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hashValue;

@end

