//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@class NSString;

@interface _TtC11AppStoreKit11OfferAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: purchaseToken
    // Error parsing type: , name: adamId
    // Error parsing type: , name: bundleId
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) NSString *bundleId; // @synthesize bundleId;
@property(nonatomic, readonly) id purchaseToken; // @synthesize purchaseToken;

@end

