//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit11Screenshots : SwiftObject
{
    // Error parsing type: , name: artwork
    // Error parsing type: , name: appPlatform
}

@end

