//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppStoreKit-1103/_TtP11AppStoreKit13StoreProtocol_-Protocol.h>

@class NSOperationQueue, NSString;
@protocol ASKBag;

__attribute__((visibility("hidden")))
@interface _TtC11AppStoreKit5Store : NSObject <_TtP11AppStoreKit13StoreProtocol_>
{
    // Error parsing type: , name: bag
    // Error parsing type: , name: storeFrontSuffix
    // Error parsing type: , name: cache
    // Error parsing type: , name: workQueue
    // Error parsing type: , name: headerProvider
    // Error parsing type: , name: pendingStorePlatformFetches
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)fetchStorePlatformData:(id)arg1:(id)arg2:(id)arg3;
- (void)commitStorePlatformDataFetches;
- (void)beginStorePlatformDataFetches;
- (void)fetchPlist:(id)arg1:(id)arg2:(id)arg3;
- (void)fetchJson:(id)arg1:(id)arg2:(id)arg3;
- (void)fetch:(id)arg1:(id)arg2:(id)arg3;
@property(nonatomic, readonly) NSOperationQueue *workQueue; // @synthesize workQueue;
@property(nonatomic, readonly) NSString *storeFrontSuffix; // @synthesize storeFrontSuffix;
@property(nonatomic, readonly) id <ASKBag> bag; // @synthesize bag;

@end

