//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreServices/SSVURLDataConsumer.h>

@class NSURL;

@interface _TtC11AppStoreKit20ProtocolDataConsumer : SSVURLDataConsumer
{
    // Error parsing type: , name: redirectURL
    // Error parsing type: , name: parseStartTime
    // Error parsing type: , name: parseEndTime
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSURL *redirectURL; // @synthesize redirectURL;
- (id)objectForData:(id)arg1 response:(id)arg2 error:(id *)arg3;

@end

