//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreServices/SSMetricsCustomEvent.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface _TtC11AppStoreKitP33_4E8C15A1165D3F1974B8F5C50AF1595715MetricsLogEvent : SSMetricsCustomEvent
{
}

- (id)initWithBodyDictionary:(id)arg1;
@property(nonatomic, copy) NSString *message;
@property(nonatomic, copy) NSString *loggerName;
@property(nonatomic, copy) NSArray *arguments;
- (id)init;

@end

