//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

#import <AppStoreKit-1103/ASKImageRequestDelegate-Protocol.h>

@interface _TtC11AppStoreKit13ArtworkLoader : SwiftObject <ASKImageRequestDelegate>
{
    // Error parsing type: , name: resourceLoader
    // Error parsing type: , name: accessQueue
    // Error parsing type: , name: completionHandlers
    // Error parsing type: , name: requestCompletionMap
    // Error parsing type: , name: isOccluded
}

- (void)imageRequest:(id)arg1 didFailWithError:(id)arg2;
- (void)imageRequest:(id)arg1 didLoadImage:(id)arg2;

@end

