//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit14TodayCardMedia.h>

@interface _TtC11AppStoreKit19TodayCardMediaVideo : _TtC11AppStoreKit14TodayCardMedia
{
    // Error parsing type: , name: video
    // Error parsing type: , name: allowsAutoPlay
    // Error parsing type: , name: looping
    // Error parsing type: , name: description
}

@end

