//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit21EditorialSearchResult : SwiftObject
{
    // Error parsing type: , name: type
    // Error parsing type: , name: title
    // Error parsing type: , name: subtitle
    // Error parsing type: , name: editorialArtwork
    // Error parsing type: , name: iconArtwork
    // Error parsing type: , name: collectionAdamIds
    // Error parsing type: , name: artworkGridType
    // Error parsing type: , name: impressionFields
    // Error parsing type: , name: clickAction
}

@end

