//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit16TodayCardOverlay.h>

@interface _TtC11AppStoreKit22TodayCardActionOverlay : _TtC11AppStoreKit16TodayCardOverlay
{
    // Error parsing type: , name: action
}

@end

