//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@class NSString;

@interface _TtC11AppStoreKit20AdTransparencyAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: adTransparencyData
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithTitle:(id)arg1 adTransparencyData:(id)arg2;
@property(nonatomic, readonly) NSString *adTransparencyData; // @synthesize adTransparencyData;

@end

