//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit18AppStateController : SwiftObject
{
    // Error parsing type: , name: dataSources
    // Error parsing type: , name: stateMachines
    // Error parsing type: , name: stateTransitionRules
    // Error parsing type: , name: stateMachineAccessQueue
    // Error parsing type: , name: dataSourceRefreshQueue
    // Error parsing type: , name: loadedAccessQueue
    // Error parsing type: , name: loadedCallbacks
    // Error parsing type: , name: loadState
}

@end

