//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit26TodayCardTriggerController : SwiftObject
{
    // Error parsing type: , name: persistantStore
    // Error parsing type: , name: accessQueue
    // Error parsing type: , name: missingIds
    // Error parsing type: , name: unresolved
    // Error parsing type: , name: inactive
    // Error parsing type: , name: activated
    // Error parsing type: , name: persistedActive
    // Error parsing type: , name: expired
    // Error parsing type: , name: activeTriggerAdamIds
}

@end

