//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@interface _TtC11AppStoreKit14AppStateAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: defaultAction
    // Error parsing type: , name: buyAction
    // Error parsing type: , name: openAction
    // Error parsing type: , name: adamId
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) _TtC11AppStoreKit6Action *openAction; // @synthesize openAction;
@property(nonatomic, readonly) _TtC11AppStoreKit6Action *buyAction; // @synthesize buyAction;
@property(nonatomic, readonly) _TtC11AppStoreKit6Action *defaultAction; // @synthesize defaultAction;

@end

