//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit18ProductDescription : SwiftObject
{
    // Error parsing type: , name: developerAction
    // Error parsing type: , name: paragraph
    // Error parsing type: , name: clickAction
    // Error parsing type: , name: clickSender
}

@end

