//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

#import <AppStoreKit-1103/NSLocking-Protocol.h>

@interface _TtC11AppStoreKit10UnfairLock : SwiftObject <NSLocking>
{
    // Error parsing type: , name: unfairLock
}

- (void)unlock;
- (void)lock;

@end

