//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface _TtC11AppStoreKit12LinkableText : NSObject
{
    // Error parsing type: , name: text
    // Error parsing type: , name: linkedSubstrings
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithText:(id)arg1 linkedSubstrings:(id)arg2;
@property(nonatomic, readonly) NSDictionary *linkedSubstrings; // @synthesize linkedSubstrings;
@property(nonatomic, readonly) NSString *text; // @synthesize text;

@end

