//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit10Annotation : SwiftObject
{
    // Error parsing type: , name: title
    // Error parsing type: , name: summary
    // Error parsing type: , name: items
    // Error parsing type: , name: isExpanded
    // Error parsing type: , name: clickAction
    // Error parsing type: , name: clickSender
}

@end

