//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit15MetricsActivity : SwiftObject
{
    // Error parsing type: , name: pageContext
    // Error parsing type: , name: hostApp
    // Error parsing type: , name: pageReferrer
    // Error parsing type: , name: buyReferrer
    // Error parsing type: , name: affiliateIdentifier
    // Error parsing type: , name: pageReferrerUrl
}

@end

