//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit28MSOPersonalizationDataSource : SwiftObject
{
    // Error parsing type: , name: storeDataProvider
    // Error parsing type: , name: accountChannelsProvider
    // Error parsing type: , name: lastContextPromise
    // Error parsing type: , name: personalizationStyle
    // Error parsing type: , name: delegate
    // Error parsing type: , name: lock
}

- (void)backingAccountStoreDidChange;

@end

