//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit4Gate : SwiftObject
{
    // Error parsing type: , name: queue
    // Error parsing type: , name: passingDelay
    // Error parsing type: , name: name
    // Error parsing type: , name: conditions
    // Error parsing type: , name: printUnsatisfiedConditions
    // Error parsing type: , name: pendingTryToPass
    // Error parsing type: , name: observerScheduler
    // Error parsing type: , name: observer
}

@end

