//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@class NSArray;

@interface _TtC11AppStoreKit15TabChangeAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: navigationTab
    // Error parsing type: , name: actions
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) NSArray *actions; // @synthesize actions;

@end

