//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit18StorePlatformCache : SwiftObject
{
    // Error parsing type: , name: cacheBox
    // Error parsing type: , name: lowMemoryWarnings
    // Error parsing type: , name: didEnterBackground
    // Error parsing type: , name: filter
}

@end

