//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit5Brick : SwiftObject
{
    // Error parsing type: , name: artwork
    // Error parsing type: , name: accessibilityLabel
    // Error parsing type: , name: shortEditorialDescription
    // Error parsing type: , name: clickAction
    // Error parsing type: , name: impressionFields
    // Error parsing type: , name: personalizationStyle
    // Error parsing type: , name: originalModel
}

@end

