//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreDaemon/ASDSoftwareUpdatesStore.h>

@interface _TtC11AppStoreKit11UpdateStore : ASDSoftwareUpdatesStore
{
    // Error parsing type: , name: notificationQueue
    // Error parsing type: , name: coalesceUpdateNotifications
}

+ (id)didChangeNotification;
+ (id)shared;
- (CDUnknownBlockType).cxx_destruct;
- (void)broadcastChangeNotificationIfNotCoalescing;
- (void)reloadFromServerWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

