//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit19ArtworkLoaderConfig : SwiftObject
{
    // Error parsing type: , name: template
    // Error parsing type: , name: size
    // Error parsing type: , name: format
    // Error parsing type: , name: crop
    // Error parsing type: , name: scale
}

@end

