//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit12MetricsEvent.h>

@interface _TtC11AppStoreKit21AppLaunchMetricsEvent : _TtC11AppStoreKit12MetricsEvent
{
    // Error parsing type: , name: launchCorrelationKey
    // Error parsing type: , name: processStartTime
    // Error parsing type: , name: requests
    // Error parsing type: , name: launchFailureTime
    // Error parsing type: , name: launchSuccessTime
}

@end

