//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC11AppStoreKit24WeakNotificationObserver : NSObject
{
    // Error parsing type: , name: scheduler
    // Error parsing type: , name: block
    // Error parsing type: , name: center
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)didReceiveWithNotification:(id)arg1;
- (void)invalidate;
- (void)dealloc;

@end

