//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSString;
@protocol ASKBag;

__attribute__((visibility("hidden")))
@interface _TtC11AppStoreKit24CoalescedLookupOperation : NSOperation
{
    // Error parsing type: , name: bag
    // Error parsing type: , name: fetches
    // Error parsing type: , name: lookupOptions
    // Error parsing type: , name: callbackScheduler
    // Error parsing type: , name: storeFrontSuffix
    // Error parsing type: , name: headerProvider
    // Error parsing type: , name: cache
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)main;
@property(nonatomic, copy) NSString *storeFrontSuffix; // @synthesize storeFrontSuffix;
@property(nonatomic, readonly) id <ASKBag> bag; // @synthesize bag;

@end

