//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@class NSString;

@interface _TtC11AppStoreKit19InAppPurchaseAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: productIdentifier
    // Error parsing type: , name: appAdamId
    // Error parsing type: , name: appBundleId
    // Error parsing type: , name: installRequiredAction
    // Error parsing type: , name: minimumShortVersionSupportingInAppPurchaseFlow
    // Error parsing type: , name: appTitle
    // Error parsing type: , name: productTitle
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) NSString *productTitle; // @synthesize productTitle;
@property(nonatomic, readonly) NSString *appTitle; // @synthesize appTitle;
@property(nonatomic, readonly) NSString *minimumShortVersionSupportingInAppPurchaseFlow; // @synthesize minimumShortVersionSupportingInAppPurchaseFlow;
@property(nonatomic, readonly) _TtC11AppStoreKit6Action *installRequiredAction; // @synthesize installRequiredAction;
@property(nonatomic, readonly) NSString *appBundleId; // @synthesize appBundleId;
@property(nonatomic, readonly) NSString *productIdentifier; // @synthesize productIdentifier;

@end

