//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKitP33_E134333D0CDAFCFB5195147F0B85274723UpdateTransitionContext : SwiftObject
{
    // Error parsing type: , name: originalIndexPaths
    // Error parsing type: , name: finalPendingUpdates
    // Error parsing type: , name: finalRecentUpdates
    // Error parsing type: , name: finalIndexPaths
}

@end

