//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC11AppStoreKit6Banner : NSObject
{
    // Error parsing type: , name: message
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithMessage:(id)arg1;
@property(nonatomic, readonly) NSString *message; // @synthesize message;

@end

