//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC11AppStoreKit29InstallPageOfferConfiguration : NSObject
{
    // Error parsing type: , name: buttonText
    // Error parsing type: , name: headerText
    // Error parsing type: , name: subheaderText
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithButtonText:(id)arg1 headerText:(id)arg2 subheaderText:(id)arg3;
@property(nonatomic, readonly) NSString *subheaderText; // @synthesize subheaderText;
@property(nonatomic, readonly) NSString *headerText; // @synthesize headerText;
@property(nonatomic, readonly) NSString *buttonText; // @synthesize buttonText;

@end

