//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@class NSDictionary, NSString, NSURL, SSURLRequestProperties;

@interface _TtC11AppStoreKit10HttpAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: url
    // Error parsing type: , name: method
    // Error parsing type: , name: headers
    // Error parsing type: , name: body
    // Error parsing type: , name: isStoreRequest
    // Error parsing type: , name: needsAuthentication
    // Error parsing type: , name: retryCount
    // Error parsing type: , name: disableCache
    // Error parsing type: , name: successAction
    // Error parsing type: , name: failureAction
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, retain) _TtC11AppStoreKit6Action *failureAction; // @synthesize failureAction;
@property(nonatomic, retain) _TtC11AppStoreKit6Action *successAction; // @synthesize successAction;
@property(nonatomic) _Bool disableCache; // @synthesize disableCache;
@property(nonatomic) long long retryCount; // @synthesize retryCount;
@property(nonatomic) _Bool needsAuthentication; // @synthesize needsAuthentication;
@property(nonatomic) _Bool isStoreRequest; // @synthesize isStoreRequest;
@property(nonatomic, copy) NSString *body; // @synthesize body;
@property(nonatomic, copy) NSDictionary *headers; // @synthesize headers;
@property(nonatomic, readonly) NSURL *url; // @synthesize url;
- (id)initWithUrl:(id)arg1 presentationStyle:(unsigned long long)arg2;
@property(nonatomic, readonly) SSURLRequestProperties *requestProperties;

@end

