//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppStoreKit-1103/_TtP11AppStoreKit12UserProtocol_-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _TtC11AppStoreKit4User : NSObject <_TtP11AppStoreKit12UserProtocol_>
{
}

- (id)init;
@property(nonatomic, readonly) _Bool isManagedAppleID;
@property(nonatomic, readonly) NSString *dsid;
@property(nonatomic, readonly) NSString *accountIdentifier;
@property(nonatomic, readonly) NSString *lastName;
@property(nonatomic, readonly) NSString *firstName;

@end

