//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@class NSArray, NSString;

@interface _TtC11AppStoreKit11SheetAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: actions
    // Error parsing type: , name: isCancelable
    // Error parsing type: , name: message
    // Error parsing type: , name: style
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) NSString *message; // @synthesize message;
@property(nonatomic, readonly) _Bool isCancelable; // @synthesize isCancelable;
@property(nonatomic, readonly) NSArray *actions; // @synthesize actions;

@end

