//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit12MetricsEvent.h>

@interface _TtC11AppStoreKit22PageRenderMetricsEvent : _TtC11AppStoreKit12MetricsEvent
{
    // Error parsing type: , name: clientCorrelationKey
    // Error parsing type: , name: pageRequestedTime
    // Error parsing type: , name: pageAppearTime
    // Error parsing type: , name: pageDisappearTime
    // Error parsing type: , name: platformRequestStartTime
    // Error parsing type: , name: platformResponseStartTime
    // Error parsing type: , name: platformResponseEndTime
    // Error parsing type: , name: platformResponseWasCached
    // Error parsing type: , name: platformJsonParseStartTime
    // Error parsing type: , name: platformJsonParseEndTime
    // Error parsing type: , name: _domChanges
    // Error parsing type: , name: requests
    // Error parsing type: , name: resourceRequestStartTime
    // Error parsing type: , name: resourceRequestOnScreenEndTime
    // Error parsing type: , name: resourceRequestEndTime
    // Error parsing type: , name: pageUserReadyTime
    // Error parsing type: , name: networkQualityReports
    // Error parsing type: , name: xpSessionDuration
    // Error parsing type: , name: xpSamplingForced
    // Error parsing type: , name: xpSamplingPercentageUsers
}

@end

