//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit15TopChartSegment : SwiftObject
{
    // Error parsing type: , name: shortName
    // Error parsing type: , name: longName
    // Error parsing type: , name: shelves
    // Error parsing type: , name: nextPage
    // Error parsing type: , name: metricsEvents
}

@end

