//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit19JSStoreDataProvider : SwiftObject
{
    // Error parsing type: , name: scheduler
    // Error parsing type: , name: runner
    // Error parsing type: , name: networkObserver
    // Error parsing type: , name: appStateController
    // Error parsing type: , name: observations
    // Error parsing type: , name: diagnostics
    // Error parsing type: , name: bag
}

@end

