//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtC11AppStoreKit6Action.h>

@class NSURL;

@interface _TtC11AppStoreKit17ExternalUrlAction : _TtC11AppStoreKit6Action
{
    // Error parsing type: , name: url
    // Error parsing type: , name: isSensitive
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) _Bool isSensitive; // @synthesize isSensitive;
@property(nonatomic, readonly) NSURL *url; // @synthesize url;
- (id)initWithTitle:(id)arg1 urlString:(id)arg2 isSensitive:(_Bool)arg3 presentationStyle:(unsigned long long)arg4;

@end

