//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit7Ratings : SwiftObject
{
    // Error parsing type: , name: productId
    // Error parsing type: , name: ratingAverage
    // Error parsing type: , name: ratingCounts
    // Error parsing type: , name: totalNumberOfRatings
    // Error parsing type: , name: totalNumberOfReviews
    // Error parsing type: , name: status
    // Error parsing type: , name: reviews
    // Error parsing type: , name: actions
    // Error parsing type: , name: nextPage
}

@end

