//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC11AppStoreKit13SearchResults : SwiftObject
{
    // Error parsing type: , name: results
    // Error parsing type: , name: facets
    // Error parsing type: , name: nextPage
    // Error parsing type: , name: isAutoPlayEnabled
    // Error parsing type: , name: metricsEvents
}

@end

