//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppStoreKit-1103/_TtP11AppStoreKit20LocalizationProtocol_-Protocol.h>

@class NSBundle, NSDateFormatter, NSDictionary, NSLocale, NSString;

@interface _TtC11AppStoreKit12Localization : NSObject <_TtP11AppStoreKit20LocalizationProtocol_>
{
    // Error parsing type: , name: locale
    // Error parsing type: , name: bundle
    // Error parsing type: , name: dateFormatters
    // Error parsing type: , name: relativeDateFormatter.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)relativeDate:(id)arg1;
- (id)formatDate:(id)arg1:(id)arg2;
- (id)timeAgo:(id)arg1;
- (id)timeAgo:(id)arg1 now:(id)arg2;
- (id)formattedCount:(id)arg1 locale:(id)arg2;
- (id)formattedCount:(id)arg1;
- (id)fileSize:(id)arg1;
- (id)stringWithCount:(id)arg1:(long long)arg2;
- (id)string:(id)arg1;
- (id)decimal:(id)arg1:(long long)arg2;
@property(nonatomic, readonly) NSString *identifier;
- (void)setAsPrimary;
- (id)init:(id)arg1;
@property(nonatomic, retain) NSDateFormatter *relativeDateFormatter;
@property(nonatomic, copy) NSDictionary *dateFormatters; // @synthesize dateFormatters;
@property(nonatomic, readonly) NSBundle *bundle; // @synthesize bundle;
@property(nonatomic, readonly) NSLocale *locale; // @synthesize locale;

@end

