//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC11AppStoreKit22OfferDisplayProperties : NSObject
{
    // Error parsing type: , name: adamId
    // Error parsing type: , name: title
    // Error parsing type: , name: subtitle
    // Error parsing type: , name: subtitlePosition
    // Error parsing type: , name: theme
    // Error parsing type: , name: hasInAppPurchases
    // Error parsing type: , name: isDeletableSystemApp
    // Error parsing type: , name: isFree
    // Error parsing type: , name: contentRating
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _Bool isFree; // @synthesize isFree;
@property(nonatomic, readonly) _Bool isDeletableSystemApp; // @synthesize isDeletableSystemApp;
@property(nonatomic, readonly) _Bool hasInAppPurchases; // @synthesize hasInAppPurchases;
@property(nonatomic, readonly) long long subtitlePosition; // @synthesize subtitlePosition;
@property(nonatomic, readonly) NSString *subtitle; // @synthesize subtitle;
@property(nonatomic, readonly) NSString *title; // @synthesize title;

@end

