//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/JSExport-Protocol.h>

@class JSValue, NSString;

@protocol _TtP11AppStoreKit19ResultProxyProtocol_ <JSExport>
- (void)resolveToError:(JSValue *)arg1;
- (void)resolveToValue:(NSString *)arg1;
@end

