//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/_TtPs15_ShadowProtocol_-Protocol.h>

@protocol _TtPs10_NSCopying_ <_TtPs15_ShadowProtocol_>
- (id)copyWithZone:(void *)arg1;
@end

