//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/JSExport-Protocol.h>

@class JSValue, NSArray, NSDictionary, NSString;

@protocol _TtP11AppStoreKit13StoreProtocol_ <JSExport>
- (void)performPurchase:(NSDictionary *)arg1:(JSValue *)arg2;
- (void)fetchStorePlatformData:(NSArray *)arg1:(NSDictionary *)arg2:(JSValue *)arg3;
- (void)commitStorePlatformDataFetches;
- (void)beginStorePlatformDataFetches;
- (void)fetchPlist:(NSString *)arg1:(NSDictionary *)arg2:(JSValue *)arg3;
- (void)fetchJson:(NSString *)arg1:(NSDictionary *)arg2:(JSValue *)arg3;
- (void)fetch:(NSString *)arg1:(NSDictionary *)arg2:(JSValue *)arg3;
@end

