//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/JSExport-Protocol.h>

@class NSDictionary, NSString;

@protocol _TtP11AppStoreKit20StoreMetricsProtocol_ <JSExport>
- (void)flushUnrecordedEvents;
- (void)recordEvent:(NSString *)arg1:(NSDictionary *)arg2;
@end

