//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppStoreKit-1103/RadiosPreferencesDelegate-Protocol.h>

@class RadiosPreferences;
@protocol ASKAirplaneModeInquiryDelegate;

@interface ASKAirplaneModeInquiry : NSObject <RadiosPreferencesDelegate>
{
    id <ASKAirplaneModeInquiryDelegate> _delegate;
    RadiosPreferences *_radiosPreferences;
}

+ (id)settingsURL;
@property(readonly, nonatomic) RadiosPreferences *radiosPreferences; // @synthesize radiosPreferences=_radiosPreferences;
@property(nonatomic) __weak id <ASKAirplaneModeInquiryDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)airplaneModeChanged;
@property(readonly, nonatomic) _Bool isEnabled;
- (id)init;

@end

