//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreKit-1103/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSNumber, NSString, NSURL, SSBag;

@protocol ASKBag <NSObject>
@property(readonly, nonatomic) SSBag *underlyingBag;
@property(readonly, nonatomic) _Bool isContentGiftingEnabled;
@property(readonly, nonatomic) _Bool isMonetaryGiftingEnabled;
@property(readonly, nonatomic) NSNumber *numberOfPurchasesThreshold;
@property(readonly, nonatomic) double onboardingCardExpirationThreshold;
@property(readonly, copy, nonatomic) NSDictionary *onboardingCardsMap;
@property(readonly, nonatomic) NSString *defaultAutoPlayVideoSetting;
@property(readonly) _Bool familyPurchasesEnabled;
@property(readonly) NSURL *familyPurchasesLearnMoreURL;
@property(readonly, nonatomic) NSURL *termsAndConditionsURL;
@property(readonly) NSURL *iForgotURL;
@property(readonly, nonatomic) NSURL *writeReviewURL;
@property(readonly, nonatomic) NSURL *userRateURL;
@property(readonly, nonatomic) _Bool personalizedUserReviewEnabled;
@property(readonly, nonatomic) NSURL *personalizedUserReviewUrl;
@property(readonly, nonatomic) double fastImpressionsTimeout;
@property(readonly) double impressionableViewablePercentage;
@property(readonly) double impressionableThreshold;
@property(readonly) double samplingPercentageUsersPageRender;
@property(readonly) double sessionDurationPageRender;
@property(readonly, copy, nonatomic) NSDictionary *metricsConfiguration;
@property(readonly, nonatomic) _Bool usePostForAppStoreSearch;
@property(readonly, nonatomic) double adTargetingRefreshInterval;
@property(readonly, nonatomic) _Bool isSponsoredAdsEnabled;
@property(readonly, nonatomic) NSURL *searchHintsURL;
@property(readonly, nonatomic) NSURL *searchURL;
@property(readonly, nonatomic) NSURL *trendingSearchesURL;
@property(readonly, copy, nonatomic) NSArray *rawStandardTabs;
@property(readonly, nonatomic) _Bool isQRCodeBadgingEnabled;
@property(readonly, nonatomic) NSURL *libraryLinkURL;
@property(readonly, nonatomic) NSURL *passbookMainURL;
@property(readonly, nonatomic) NSURL *accessoryRoomURL;
@property(readonly, nonatomic) double residentSessionMaximumAge;
@property(readonly, nonatomic) double fetchTimeout;
@property(readonly, copy, nonatomic) NSString *language;
@property(readonly, copy, nonatomic) NSString *storefrontSuffix;
@property(readonly, nonatomic) NSURL *appScriptURL;
@end

