//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppStoreKit-1103/ASKClientExports-Protocol.h>

@class NSArray, NSString, NSURL;

@interface ASKClient : NSObject <ASKClientExports>
{
    NSArray *_deviceCapabilities;
}

+ (id)determinedProperties;
+ (id)currentClient;
@property(retain, nonatomic) NSArray *deviceCapabilities; // @synthesize deviceCapabilities=_deviceCapabilities;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSURL *jsPackageURL;
@property(readonly, nonatomic) _Bool debugAlwaysTreatResidentSessionAsInvalid;
@property(readonly, nonatomic) _Bool isCacheBusterEnabled;
@property(readonly) _Bool newPaymentMethodEnabled;
@property(readonly, copy) NSString *storefrontIdentifier;
@property(readonly, copy) NSString *modelIdentifier;
@property(readonly, copy) NSString *thinnedApplicationVariantIdentifier;
@property(readonly, copy) NSString *guid;
@property(readonly) struct CGSize screenSize;
@property(readonly) NSString *deviceType;
@property(readonly) _Bool diagnosticQRCodesEnabled;
@property(readonly) _Bool isUnitTesting;
@property(readonly) _Bool isConvergenceBuild;
@property(readonly) _Bool isDevelopmentBuild;
@property(readonly) _Bool isInternalBuild;
@property(readonly, copy) NSString *name;
- (_Bool)isOperatingSystemAtLeast:(long long)arg1:(long long)arg2:(long long)arg3;

@end

