//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class ASKImageRequest, NSError, UIImage;

@protocol ASKImageRequestDelegate
- (void)imageRequest:(ASKImageRequest *)arg1 didFailWithError:(NSError *)arg2;
- (void)imageRequest:(ASKImageRequest *)arg1 didLoadImage:(UIImage *)arg2;
@end

