//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreServices/SSVURLDataConsumer.h>

@class UIGraphicsImageRendererFormat;

@interface ASKImageDataConsumer : SSVURLDataConsumer
{
    UIGraphicsImageRendererFormat *_format;
    struct CGSize _size;
}

@property(readonly, nonatomic) UIGraphicsImageRendererFormat *format; // @synthesize format=_format;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
- (void).cxx_destruct;
- (id)objectForData:(id)arg1 response:(id)arg2 error:(id *)arg3;
- (id)initWithSize:(struct CGSize)arg1;
- (id)initWithSize:(struct CGSize)arg1 format:(id)arg2;

@end

