//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ASKMobileGestalt : NSObject
{
}

+ (_Bool)wapiCapability;
+ (_Bool)isD22;
+ (_Bool)hasVenice;
+ (_Bool)hasArm64;
+ (_Bool)hasMetal;
+ (_Bool)hasOpenGLES3;
+ (_Bool)hasHealthKit;
+ (_Bool)hasBluetoothLE;
+ (_Bool)hasArmV7;
+ (_Bool)hasGameKit;
+ (_Bool)hasCameraFlash;
+ (_Bool)hasFrontFacingCamera;
+ (_Bool)hasGyroscope;
+ (_Bool)hasAutoFocusCamera;
+ (_Bool)hasVideoCamera;
+ (_Bool)hasOpenGLES2;
+ (_Bool)hasMagnetometer;
+ (_Bool)hasOpenGLES1;
+ (_Bool)hasMicrophone;
+ (_Bool)hasLocationServices;
+ (_Bool)hasGPS;
+ (_Bool)hasAccelerometer;
+ (_Bool)hasWiFi;
+ (_Bool)hasStillCamera;
+ (_Bool)hasSMS;
+ (_Bool)hasTelephony;
+ (_Bool)hasSystemTelephonyOfAnyKind;

@end

