//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppStoreKit-1103/ASKPurchasesDatabaseNotificationDelegate-Protocol.h>

@class ASKPurchasesDatabaseNotificationForwarder, HSCloudClient, NSString, SSAppPurchaseHistoryDatabase;
@protocol OS_dispatch_queue;

@interface ASKPurchasesDatabase : NSObject <ASKPurchasesDatabaseNotificationDelegate>
{
    NSObject<OS_dispatch_queue> *_accessQueue;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    HSCloudClient *_cloudClient;
    SSAppPurchaseHistoryDatabase *_database;
    ASKPurchasesDatabaseNotificationForwarder *_notificationForwarder;
}

+ (id)purchasePredicateForStoreIdentifier:(id)arg1;
+ (id)defaultHiddenPurchasesPredicatesForDeviceType:(id)arg1 withSearchTerm:(id)arg2;
+ (id)defaultPurchasePredicatesForDeviceType:(id)arg1 withSearchTerm:(id)arg2;
+ (id)defaultPurchasePredicates;
+ (id)purchasesChangedNotificationName;
+ (id)shared;
@property(retain, nonatomic) ASKPurchasesDatabaseNotificationForwarder *notificationForwarder; // @synthesize notificationForwarder=_notificationForwarder;
@property(retain, nonatomic) SSAppPurchaseHistoryDatabase *database; // @synthesize database=_database;
@property(retain, nonatomic) HSCloudClient *cloudClient; // @synthesize cloudClient=_cloudClient;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *accessQueue; // @synthesize accessQueue=_accessQueue;
- (void).cxx_destruct;
- (long long)homeSharingReasonForPurchasesReason:(unsigned long long)arg1;
- (CDUnknownBlockType)_successCompletionOnCallbackQueue:(CDUnknownBlockType)arg1;
- (void)_updateForFamilyMember:(id)arg1 withReason:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateForFamilyMember:(id)arg1 withReason:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateActiveAccountWithReason:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)purchasesDatabaseChangeNotificationRecieved;
- (void)purchasesWithPredicates:(id)arg1 sortColumn:(id)arg2 ascending:(_Bool)arg3 familyMembers:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)unhideAllPurchasesWithCompletion:(CDUnknownBlockType)arg1;
- (void)unhidePurchaseWithAdamId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)hidePurchaseWithAdamId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

