//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable;

@interface ASKStorefrontChangeCoordinator : NSObject
{
    _Bool _hasPendingNotification;
    _Bool _activeAccountIsManagedAppleId;
    NSHashTable *_handlerTokens;
    CDUnknownBlockType _appBootstrapHandler;
    long long _delayCount;
}

+ (id)sharedCoordinator;
@property _Bool activeAccountIsManagedAppleId; // @synthesize activeAccountIsManagedAppleId=_activeAccountIsManagedAppleId;
@property(nonatomic) _Bool hasPendingNotification; // @synthesize hasPendingNotification=_hasPendingNotification;
@property(nonatomic) long long delayCount; // @synthesize delayCount=_delayCount;
@property(copy, nonatomic) CDUnknownBlockType appBootstrapHandler; // @synthesize appBootstrapHandler=_appBootstrapHandler;
@property(readonly, nonatomic) NSHashTable *handlerTokens; // @synthesize handlerTokens=_handlerTokens;
- (void).cxx_destruct;
- (void)registerAppBootstrapHandler:(CDUnknownBlockType)arg1;
- (id)registerCleanupHandler:(CDUnknownBlockType)arg1;
- (void)simulateStorefrontChange;
- (void)endDelayingNotifications;
- (void)beginDelayingNotifications;
- (void)notify;
- (void)sheduleNotification;
- (void)deviceStorefrontDidChange:(id)arg1;
- (void)accountDidChange:(id)arg1;
- (void)dealloc;
- (id)init;

@end

