//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableString.h>

@interface NSMutableString (AppStoreKit)
- (void)trimLeadingCharactersIn:(id)arg1;
- (void)trimCharactersIn:(id)arg1;
@end

