//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/NSParagraphStyle.h>

@interface NSParagraphStyle (AppStoreKit)
+ (id)listItemWithFont:(id)arg1;
+ (id)nqml;
+ (id)bulletPrefix;
@property(nonatomic, readonly) _Bool isListItem;
@end

