//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol SSMetricsFastImpressionDelegate;

@interface SSMetricsImpressionsCatalogue : NSObject
{
    double _impressionableThreshold;
    id <SSMetricsFastImpressionDelegate> _delegate;
    NSMutableDictionary *_impressionsMap;
}

@property(readonly, nonatomic) NSMutableDictionary *impressionsMap; // @synthesize impressionsMap=_impressionsMap;
@property(nonatomic) __weak id <SSMetricsFastImpressionDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) double impressionableThreshold; // @synthesize impressionableThreshold=_impressionableThreshold;
- (void).cxx_destruct;
- (void)flush:(id)arg1;
- (id)_impressionsEventsForQueue:(id)arg1 from:(id)arg2 inFormat:(unsigned long long)arg3;
- (id)impressionsForQueue:(id)arg1 inFormat:(unsigned long long)arg2;
- (id)impressionsInFormat:(unsigned long long)arg1;
- (id)impressionsSnapshotForQueue:(id)arg1 inFormat:(unsigned long long)arg2;
- (id)impressionsSnapshotInFormat:(unsigned long long)arg1;
- (void)elementDidLeaveViewWithId:(id)arg1 onDate:(id)arg2;
- (void)elementDidEnterViewWithId:(id)arg1 metricsBlob:(id)arg2 onDate:(id)arg3;
- (id)initWithImpressionableThreshold:(double)arg1;

@end

