//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "Action-Protocol.h"
#import "FMDAccessoryRegistryDelegate-Protocol.h"

@class FMDLocation, FMDLocator, FMDispatchTimer, FMFuture, NSString;
@protocol FMDInternalAccessory;

@interface AccessoryCurrentLocationAction : NSObject <Action, FMDAccessoryRegistryDelegate>
{
    NSObject<FMDInternalAccessory> *_accessory;
    FMDLocator *_locator;
    long long _event;
    CDUnknownBlockType _actionCompletion;
    FMDLocation *_location;
    CDUnknownBlockType _completion;
    FMFuture *_accessoryUpdateFuture;
    FMDispatchTimer *_discoveryWaitTimer;
}

@property(retain, nonatomic) FMDispatchTimer *discoveryWaitTimer; // @synthesize discoveryWaitTimer=_discoveryWaitTimer;
@property(retain, nonatomic) FMFuture *accessoryUpdateFuture; // @synthesize accessoryUpdateFuture=_accessoryUpdateFuture;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) FMDLocation *location; // @synthesize location=_location;
@property(copy, nonatomic) CDUnknownBlockType actionCompletion; // @synthesize actionCompletion=_actionCompletion;
@property(nonatomic) long long event; // @synthesize event=_event;
@property(retain, nonatomic) FMDLocator *locator; // @synthesize locator=_locator;
@property(retain, nonatomic) NSObject<FMDInternalAccessory> *accessory; // @synthesize accessory=_accessory;
- (void).cxx_destruct;
- (void)accessoryDidUpdate:(id)arg1;
- (void)updateLocationMetaData;
- (void)validateAccessoryDiscoveryDate;
- (void)_stopLocator;
- (void)_completeLocate;
- (void)_finishAction;
- (void)_retrieveLocationNow;
- (_Bool)shouldCancelAction:(id)arg1;
- (void)runWithCompletion:(CDUnknownBlockType)arg1;
- (void)willCancelAction;
- (id)actionType;
- (id)initWithAccessory:(id)arg1 locator:(id)arg2 event:(long long)arg3 completion:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

