//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "Action-Protocol.h"

@class FMDAccount, FMDRequestRegister, FMDServerInteractionController, NSString;
@protocol FMDInternalAccessory;

@interface AccessoryRegisterAction : NSObject <Action>
{
    _Bool _includeDeviceState;
    _Bool _force;
    FMDRequestRegister *_request;
    FMDAccount *_account;
    id <FMDInternalAccessory> _accessory;
    NSString *_cause;
    FMDServerInteractionController *_serverInteractionController;
    CDUnknownBlockType _completion;
}

+ (void)cleanupContextForAccessory:(id)arg1;
+ (id)contextForAccessory:(id)arg1 contextUUID:(id *)arg2;
+ (id)contextKeyForAccessory:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) __weak FMDServerInteractionController *serverInteractionController; // @synthesize serverInteractionController=_serverInteractionController;
@property(nonatomic) _Bool force; // @synthesize force=_force;
@property(retain, nonatomic) NSString *cause; // @synthesize cause=_cause;
@property(retain, nonatomic) id <FMDInternalAccessory> accessory; // @synthesize accessory=_accessory;
@property(retain, nonatomic) FMDAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) FMDRequestRegister *request; // @synthesize request=_request;
@property(nonatomic) _Bool includeDeviceState; // @synthesize includeDeviceState=_includeDeviceState;
- (void).cxx_destruct;
- (id)digestWithDeviceInfo:(id)arg1;
- (_Bool)_registerDeviceWithCause:(id)arg1;
- (_Bool)shouldCancelAction:(id)arg1;
- (void)terminate;
- (void)willCancelAction;
- (void)runWithCompletion:(CDUnknownBlockType)arg1;
- (id)actionType;
- (id)initWithAccount:(id)arg1 accessory:(id)arg2 cause:(id)arg3 force:(_Bool)arg4 serverInteractionController:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

