//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMGeoLocatable-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSDate, NSNumber, NSString;

@interface CLLocationFMGeoLocatableAdapter : NSObject <FMGeoLocatable, NSSecureCoding>
{
    NSNumber *_latitude;
    NSNumber *_longitude;
    NSNumber *_altitude;
    NSNumber *_horizontalAccuracy;
    NSNumber *_verticalAccuracy;
    NSNumber *_course;
    NSNumber *_speed;
    NSDate *_timestamp;
    NSNumber *_floor;
    long long _locationType;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) long long locationType; // @synthesize locationType=_locationType;
@property(copy, nonatomic) NSNumber *floor; // @synthesize floor=_floor;
@property(copy, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSNumber *speed; // @synthesize speed=_speed;
@property(retain, nonatomic) NSNumber *course; // @synthesize course=_course;
@property(retain, nonatomic) NSNumber *verticalAccuracy; // @synthesize verticalAccuracy=_verticalAccuracy;
@property(retain, nonatomic) NSNumber *horizontalAccuracy; // @synthesize horizontalAccuracy=_horizontalAccuracy;
@property(retain, nonatomic) NSNumber *altitude; // @synthesize altitude=_altitude;
@property(retain, nonatomic) NSNumber *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSNumber *latitude; // @synthesize latitude=_latitude;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (long long)geoLocatableLocationTypeForLocationType:(int)arg1;
- (id)initWithLocation:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

