//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "Action-Protocol.h"

@class FMDAssetRegistry, FMDServerInteractionController, FMFileDownloadRequest, NSString;
@protocol FMDAsset;

@interface FileDownloadAction : NSObject <Action>
{
    id <FMDAsset> _asset;
    FMDServerInteractionController *_serverInteractionController;
    FMDAssetRegistry *_assetRegistry;
    FMFileDownloadRequest *_request;
}

@property(retain, nonatomic) FMFileDownloadRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) FMDAssetRegistry *assetRegistry; // @synthesize assetRegistry=_assetRegistry;
@property(nonatomic) __weak FMDServerInteractionController *serverInteractionController; // @synthesize serverInteractionController=_serverInteractionController;
@property(retain, nonatomic) id <FMDAsset> asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (_Bool)shouldCancelAction:(id)arg1;
- (_Bool)shouldWaitForAction:(id)arg1;
- (void)willCancelAction;
- (void)_saveAsset:(id)arg1 fromLocation:(id)arg2;
- (void)runWithCompletion:(CDUnknownBlockType)arg1;
- (id)actionType;
- (id)initWithAsset:(id)arg1 serverInteractionController:(id)arg2 assetRegistry:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

