//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDServerInteractionController, FMDataArchiver, NSDictionary, NSString, NSURL;
@protocol OS_dispatch_queue;

@interface FMDAssetRegistry : NSObject
{
    NSURL *_baseStoragePath;
    NSDictionary *_assetsByURL;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSString *_storeIdentifier;
    FMDataArchiver *_dataArchiver;
    FMDServerInteractionController *_serverInteractionController;
}

+ (id)defaultStorageLocation;
@property(retain, nonatomic) FMDServerInteractionController *serverInteractionController; // @synthesize serverInteractionController=_serverInteractionController;
@property(retain, nonatomic) FMDataArchiver *dataArchiver; // @synthesize dataArchiver=_dataArchiver;
@property(retain, nonatomic) NSString *storeIdentifier; // @synthesize storeIdentifier=_storeIdentifier;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(retain, nonatomic) NSDictionary *assetsByURL; // @synthesize assetsByURL=_assetsByURL;
@property(retain, nonatomic) NSURL *baseStoragePath; // @synthesize baseStoragePath=_baseStoragePath;
- (void).cxx_destruct;
- (void)resumeBackgroundAssetDownloads:(id)arg1;
- (void)downloadAssets:(id)arg1;
- (id)generateAssetURL;
- (id)registryFileURL;
- (void)saveAssetMetadata:(id)arg1;
- (void)_removeUntrackedAssets:(id)arg1;
- (unsigned long long)assetTypeForString:(id)arg1;
- (id)newAssetForURL:(id)arg1 type:(unsigned long long)arg2;
- (void)clearAssetRegistry;
- (void)removeUntrackedAssets:(id)arg1;
- (id)newAssetWithDictionary:(id)arg1;
- (id)assetForURL:(id)arg1;
- (void)storeAsset:(id)arg1 fromLocation:(id)arg2;
- (id)initWithStorageLocation:(id)arg1 identifier:(id)arg2;

@end

