//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSString;

@interface FMDAccount : NSObject
{
    unsigned char _activityState;
    NSString *_oneTimeRemoveAuthToken;
    NSString *_username;
    NSString *_serverHost;
    NSString *_serverProtocolScheme;
    NSString *_apsEnvironment;
    unsigned long long _unregisterState;
    NSDate *_lastUnregisterFailedTime;
    NSArray *_versionHistory;
    NSDate *_accountAddTime;
}

@property(nonatomic) unsigned char activityState; // @synthesize activityState=_activityState;
@property(retain, nonatomic) NSDate *accountAddTime; // @synthesize accountAddTime=_accountAddTime;
@property(retain, nonatomic) NSArray *versionHistory; // @synthesize versionHistory=_versionHistory;
@property(retain, nonatomic) NSDate *lastUnregisterFailedTime; // @synthesize lastUnregisterFailedTime=_lastUnregisterFailedTime;
@property(nonatomic) unsigned long long unregisterState; // @synthesize unregisterState=_unregisterState;
@property(retain, nonatomic) NSString *apsEnvironment; // @synthesize apsEnvironment=_apsEnvironment;
@property(retain, nonatomic) NSString *serverProtocolScheme; // @synthesize serverProtocolScheme=_serverProtocolScheme;
@property(retain, nonatomic) NSString *serverHost; // @synthesize serverHost=_serverHost;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *oneTimeRemoveAuthToken; // @synthesize oneTimeRemoveAuthToken=_oneTimeRemoveAuthToken;
- (void).cxx_destruct;
- (void)copyInfoFromAccount:(id)arg1;
@property(readonly, nonatomic) NSString *apsEnvironmentConstant;
@property(readonly, nonatomic) NSString *authToken;
@property(readonly, nonatomic) NSString *authId;

@end

