//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDAccessoryRegistryDelegate-Protocol.h"

@class FMDAccessoryRegistry, FMDSupportedAccessoryRegistry, FMDXPCJanitor, FMDataArchiver, FMStateCapture, NSDate, NSDictionary, NSString;
@protocol OS_dispatch_queue;

@interface FMDAccessoryLocationStore : NSObject <FMDAccessoryRegistryDelegate>
{
    FMDSupportedAccessoryRegistry *_supportedAccessoryRegistry;
    FMDAccessoryRegistry *_accessoryRegistry;
    FMDXPCJanitor *_janitor;
    NSDate *_nextScheduledJanitorDate;
    FMDataArchiver *_dataArchiver;
    NSDictionary *_recordsByAccessoryIdentifier;
    NSObject<OS_dispatch_queue> *_serialQueue;
    FMStateCapture *_stateCapture;
}

+ (id)defaultStorageLocation;
@property(retain, nonatomic) FMStateCapture *stateCapture; // @synthesize stateCapture=_stateCapture;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(retain, nonatomic) NSDictionary *recordsByAccessoryIdentifier; // @synthesize recordsByAccessoryIdentifier=_recordsByAccessoryIdentifier;
@property(retain, nonatomic) FMDataArchiver *dataArchiver; // @synthesize dataArchiver=_dataArchiver;
@property(retain, nonatomic) NSDate *nextScheduledJanitorDate; // @synthesize nextScheduledJanitorDate=_nextScheduledJanitorDate;
@property(retain, nonatomic) FMDXPCJanitor *janitor; // @synthesize janitor=_janitor;
@property(nonatomic) __weak FMDAccessoryRegistry *accessoryRegistry; // @synthesize accessoryRegistry=_accessoryRegistry;
@property(nonatomic) __weak FMDSupportedAccessoryRegistry *supportedAccessoryRegistry; // @synthesize supportedAccessoryRegistry=_supportedAccessoryRegistry;
- (void).cxx_destruct;
- (void)accessoryDidDisconnect:(id)arg1;
- (void)accessoryDidUnpair:(id)arg1;
- (void)scheduleJanitor:(id)arg1;
- (id)contextKeyForAccessory:(id)arg1;
- (_Bool)canRetrieveLockedRecords;
- (void)readLocationsFromDisk;
- (void)clearAllRecords;
- (void)expungeRecordsForAccessory:(id)arg1 allRecords:(_Bool)arg2;
- (id)saveLocationToDisk:(id)arg1 accessory:(id)arg2 protection:(unsigned long long)arg3;
- (void)saveLocation:(id)arg1 forAccessory:(id)arg2;
- (_Bool)shouldRetrieveLocationForAccessory:(id)arg1;
- (void)retreiveLocationForAccessory:(id)arg1 forEvent:(long long)arg2 locator:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)removeOrphanedLocationFiles;
- (void)expungeAccessoryLocationStore;
- (void)clearAccessoryLocationStore;
- (id)historicalLocationForAccessory:(id)arg1;
- (void)locationForAccessory:(id)arg1 locator:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setup;
- (id)initWithSupportedAccessoryRegistry:(id)arg1 accessoryRegistry:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

