//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDAccountStore-Protocol.h"

@class FMDFMIPAccount, FMDataArchiver, FMStateCapture, NSDictionary, NSString;

@interface FMDAccountStoreFMIP : NSObject <FMDAccountStore>
{
    _Bool _oldLowBatteryState;
    _Bool _initialized;
    FMDFMIPAccount *_account;
    NSDictionary *_fmipStateChangeCriteria;
    FMStateCapture *_stateCapture;
    FMDataArchiver *_backedUpDataArchiver;
    FMDataArchiver *_notBackedUpDataArchiver;
}

@property(retain, nonatomic) FMDataArchiver *notBackedUpDataArchiver; // @synthesize notBackedUpDataArchiver=_notBackedUpDataArchiver;
@property(retain, nonatomic) FMDataArchiver *backedUpDataArchiver; // @synthesize backedUpDataArchiver=_backedUpDataArchiver;
@property(retain, nonatomic) FMStateCapture *stateCapture; // @synthesize stateCapture=_stateCapture;
@property(nonatomic) _Bool initialized; // @synthesize initialized=_initialized;
@property(nonatomic) _Bool oldLowBatteryState; // @synthesize oldLowBatteryState=_oldLowBatteryState;
@property(retain, nonatomic) NSDictionary *fmipStateChangeCriteria; // @synthesize fmipStateChangeCriteria=_fmipStateChangeCriteria;
@property(retain, nonatomic) FMDFMIPAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)accountsNotBackedUpFileURL;
- (id)accountsFileURL;
- (id)_stateChangeCriteriaForAccount:(id)arg1;
- (id)_notBackedUpDictionaryFromAccount:(id)arg1;
- (id)_backedUpDictionaryFromAccount:(id)arg1;
- (id)_accountFromBackedUpDictionary:(id)arg1 andNotBackedUpDictionary:(id)arg2;
- (void)_saveDictionaryForAccount:(id)arg1;
- (void)_checkOSVersionHistoryUsingBackedUpVersion:(id)arg1 nonBackedUpVersion:(id)arg2;
- (void)_saveChanges;
- (void)_loadTestAccount;
- (void)saveAccount:(id)arg1;
- (id)loadAccount;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

