//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDate, NSNumber, NSString;

@protocol FMDBluetoothManagerDevice <NSObject>
@property(readonly, nonatomic) NSDate *rssiUpdateDate;
@property(readonly, nonatomic) NSNumber *accessoryRSSI;
@property(readonly, nonatomic) NSNumber *bluetoothDeviceProductId;
@property(readonly, nonatomic) NSNumber *bluetoothDeviceVendor;
@property(readonly, nonatomic) NSString *address;
@property(readonly, nonatomic) NSString *scoUID;
@property(readonly, nonatomic) NSNumber *bluetoothMinorDeviceClass;
@property(readonly, nonatomic) NSNumber *bluetoothMajorDeviceClass;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) NSString *hardwareRevision;
@property(readonly, nonatomic) NSString *firmwareRevision;
@property(readonly, nonatomic) NSString *serialNumber;
@property(readonly, nonatomic) NSNumber *bluetoothConnected;
@property(readonly, nonatomic) NSArray *batteryInfo;
@property(readonly, nonatomic) NSArray *beacons;
@property(readonly, nonatomic) NSArray *audioChannelInfo;
@property(readonly, nonatomic) NSNumber *bluetoothColorCode;
@end

