//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDDeviceDiscovering-Protocol.h"
#import "FindMyDeviceBTDiscoveryDelegateXPCInterface-Protocol.h"

@class FMNSXPCConnection, NSString;

@interface FMDBluetoothDiscoveryXPCProxy : NSObject <FindMyDeviceBTDiscoveryDelegateXPCInterface, FMDDeviceDiscovering>
{
    CDUnknownBlockType _didEndDiscovery;
    CDUnknownBlockType _didDiscoverDevice;
    CDUnknownBlockType _didLoseDevice;
    FMNSXPCConnection *_connection;
}

@property(retain, nonatomic) FMNSXPCConnection *connection; // @synthesize connection=_connection;
@property(copy, nonatomic) CDUnknownBlockType didLoseDevice; // @synthesize didLoseDevice=_didLoseDevice;
@property(copy, nonatomic) CDUnknownBlockType didDiscoverDevice; // @synthesize didDiscoverDevice=_didDiscoverDevice;
@property(copy, nonatomic) CDUnknownBlockType didEndDiscovery; // @synthesize didEndDiscovery=_didEndDiscovery;
- (void).cxx_destruct;
- (void)_didEndDiscoveryWithError:(id)arg1;
- (oneway void)didLoseDevice:(id)arg1;
- (oneway void)didDiscoverDevice:(id)arg1;
- (oneway void)didEndDiscoveryWithError:(id)arg1;
- (void)stopDiscovery;
- (void)startDiscovery;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

