//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDBluetoothDeviceDiscovering-Protocol.h"

@class NSDate, NSString;
@protocol FMDBluetoothDiscoveryTokenDelegate;

@interface FMDBluetoothDiscoveryToken : NSObject <FMDBluetoothDeviceDiscovering>
{
    CDUnknownBlockType _tokenDiscoveryEnded;
    NSObject<FMDBluetoothDiscoveryTokenDelegate> *_delegate;
    NSDate *_endDate;
}

@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property(nonatomic) __weak NSObject<FMDBluetoothDiscoveryTokenDelegate> *delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType tokenDiscoveryEnded; // @synthesize tokenDiscoveryEnded=_tokenDiscoveryEnded;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool isDiscoveryActive;
- (void)stopDiscovery;
- (void)startDiscoveryForDuration:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

