//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol FMDBluetoothDeviceDiscovering <NSObject>
@property(copy, nonatomic) CDUnknownBlockType tokenDiscoveryEnded;
@property(readonly, nonatomic) _Bool isDiscoveryActive;
- (void)stopDiscovery;
- (void)startDiscoveryForDuration:(double)arg1;
@end

