//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDServerChannel-Protocol.h"

@class NSString, NSURLSession;
@protocol OS_dispatch_queue;

@interface FMDBackgroundServerChannel : NSObject <FMDServerChannel>
{
    NSURLSession *_session;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (void)tasksWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) _Bool isActive;
- (_Bool)supportsRequestType:(unsigned long long)arg1;
- (void)cancelAllRequests;
- (void)cancelRequestWithId:(id)arg1;
- (void)sendRequestWithId:(id)arg1 toURL:(id)arg2 withHeaders:(id)arg3 body:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)resumeBackgroundTasks;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

