//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDBeacon-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class FMDBLEBeaconIdentifier, NSDate, NSDictionary, NSNumber, NSString;

@interface FMDBLEBeacon : NSObject <FMDBeacon, NSSecureCoding>
{
    _Bool _trustAsItself;
    _Bool _trustAsOther;
    _Bool _active;
    _Bool _primary;
    _Bool _utpConnected;
    FMDBLEBeacon *_otherBeacon;
    NSNumber *_advertisementStatus;
    NSNumber *_rssi;
    NSDate *_updateDate;
    FMDBLEBeaconIdentifier *_identifier;
    NSString *_name;
    NSNumber *_colorCode;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) _Bool utpConnected; // @synthesize utpConnected=_utpConnected;
@property(nonatomic) _Bool primary; // @synthesize primary=_primary;
@property(retain, nonatomic) NSNumber *colorCode; // @synthesize colorCode=_colorCode;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) FMDBLEBeaconIdentifier *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSDate *updateDate; // @synthesize updateDate=_updateDate;
@property(retain, nonatomic) NSNumber *rssi; // @synthesize rssi=_rssi;
@property(retain, nonatomic) NSNumber *advertisementStatus; // @synthesize advertisementStatus=_advertisementStatus;
@property(retain, nonatomic) FMDBLEBeacon *otherBeacon; // @synthesize otherBeacon=_otherBeacon;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) _Bool trustAsOther; // @synthesize trustAsOther=_trustAsOther;
@property(nonatomic) _Bool trustAsItself; // @synthesize trustAsItself=_trustAsItself;
- (void).cxx_destruct;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)inflateHeadsetStatus:(unsigned int)arg1;
- (_Bool)trustHeadsetStatus:(unsigned int)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) NSDictionary *dictionaryValue;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithBLEDevice:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

