//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface FMDConcurrentMutableDictionary : NSObject
{
    NSMutableDictionary *_underlyingDictionary;
    NSObject<OS_dispatch_queue> *_dictModQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dictModQueue; // @synthesize dictModQueue=_dictModQueue;
@property(retain, nonatomic) NSMutableDictionary *underlyingDictionary; // @synthesize underlyingDictionary=_underlyingDictionary;
- (void).cxx_destruct;
- (id)nativeDictionary;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectForKey:(id)arg1;
@property(readonly, nonatomic) unsigned long long count;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

