//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDCommandHandler.h"

@class FMDMessage;

@interface FMDCommandHandlerMessage : FMDCommandHandler
{
    FMDMessage *_waitingSecureMsgNotfn;
}

@property(retain, nonatomic) FMDMessage *waitingSecureMsgNotfn; // @synthesize waitingSecureMsgNotfn=_waitingSecureMsgNotfn;
- (void).cxx_destruct;
- (void)showSecureMessage:(id)arg1 andLockScreenMessage:(id)arg2;
- (_Bool)shouldShowSecureMessageOnLockScreen;
- (_Bool)shouldShowLockScreenMessage;
- (_Bool)shouldHonorSecureMessage;
- (void)sendAckWithCompletion:(CDUnknownBlockType)arg1;
- (void)handleCommand;
- (id)initWithParams:(id)arg1 provider:(id)arg2;

@end

