//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDCommandContext, FMDServiceProvider, NSDictionary, NSString;

@interface FMDCommandHandler : NSObject
{
    _Bool _requiresAsynchronousAck;
    NSDictionary *_commandParams;
    FMDCommandContext *_commandContext;
    FMDServiceProvider *_provider;
    NSDictionary *_ackDataForCommand;
}

@property(retain, nonatomic) NSDictionary *ackDataForCommand; // @synthesize ackDataForCommand=_ackDataForCommand;
@property(nonatomic) _Bool requiresAsynchronousAck; // @synthesize requiresAsynchronousAck=_requiresAsynchronousAck;
@property(nonatomic) __weak FMDServiceProvider *provider; // @synthesize provider=_provider;
@property(retain, nonatomic) FMDCommandContext *commandContext; // @synthesize commandContext=_commandContext;
@property(retain, nonatomic) NSDictionary *commandParams; // @synthesize commandParams=_commandParams;
- (void).cxx_destruct;
- (id)fm_logID;
- (void)sendAckWithCompletion:(CDUnknownBlockType)arg1;
- (void)handleCommand;
- (void)didHandleCommandWithAckData:(id)arg1;
@property(readonly, nonatomic) _Bool isPreviouslyHandledCommand;
@property(readonly, nonatomic) NSString *commandID;
@property(readonly, nonatomic) NSString *commandName;
- (void)dealloc;
- (void)executeCommand;
- (id)initWithParams:(id)arg1 provider:(id)arg2;

@end

