//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMKeychainItem-Protocol.h"

@class NSData, NSDate, NSString;
@protocol FMDCiphering;

@interface FMDCipherKeychainItemAdaptor : NSObject <FMKeychainItem>
{
    NSData *_rawData;
    NSDate *_lastModifyDate;
    NSDate *_creationDate;
    NSString *_password;
    NSObject<FMDCiphering> *_cipher;
}

@property(retain, nonatomic) NSObject<FMDCiphering> *cipher; // @synthesize cipher=_cipher;
@property(readonly, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(retain, nonatomic) NSDate *lastModifyDate; // @synthesize lastModifyDate=_lastModifyDate;
@property(retain, nonatomic) NSData *rawData; // @synthesize rawData=_rawData;
- (void).cxx_destruct;
- (id)initWithCipher:(id)arg1;
- (id)initWithKeychainItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

