//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMLocatorPublishing-Protocol.h"

@class FMDispatchTimer, NSDate, NSNumber, NSString;
@protocol FMGeoLocatable;

@interface FMDConservativeLocatorPublisher : NSObject <FMLocatorPublishing>
{
    _Bool _startedPublishing;
    int _currentDecayMultiplier;
    NSNumber *_startThreshold;
    NSNumber *_endThreshold;
    NSNumber *_decayFactor;
    NSNumber *_publishTimeInterval;
    NSNumber *_minimumDistance;
    NSNumber *_cachedLocationValidityTimeInterval;
    CDUnknownBlockType _publishingBlock;
    NSDate *_launchDate;
    NSNumber *_currentThreshold;
    NSObject<FMGeoLocatable> *_lastLocation;
    NSObject<FMGeoLocatable> *_lastPublishedLocation;
    FMDispatchTimer *_publishTimer;
    NSDate *_nextPublishTimerFireDate;
}

@property(retain, nonatomic) NSDate *nextPublishTimerFireDate; // @synthesize nextPublishTimerFireDate=_nextPublishTimerFireDate;
@property(retain, nonatomic) FMDispatchTimer *publishTimer; // @synthesize publishTimer=_publishTimer;
@property(retain, nonatomic) NSObject<FMGeoLocatable> *lastPublishedLocation; // @synthesize lastPublishedLocation=_lastPublishedLocation;
@property(retain, nonatomic) NSObject<FMGeoLocatable> *lastLocation; // @synthesize lastLocation=_lastLocation;
@property(nonatomic) int currentDecayMultiplier; // @synthesize currentDecayMultiplier=_currentDecayMultiplier;
@property(retain, nonatomic) NSNumber *currentThreshold; // @synthesize currentThreshold=_currentThreshold;
@property(retain, nonatomic) NSDate *launchDate; // @synthesize launchDate=_launchDate;
@property(nonatomic) _Bool startedPublishing; // @synthesize startedPublishing=_startedPublishing;
@property(copy, nonatomic) CDUnknownBlockType publishingBlock; // @synthesize publishingBlock=_publishingBlock;
@property(retain, nonatomic) NSNumber *cachedLocationValidityTimeInterval; // @synthesize cachedLocationValidityTimeInterval=_cachedLocationValidityTimeInterval;
@property(retain, nonatomic) NSNumber *minimumDistance; // @synthesize minimumDistance=_minimumDistance;
@property(retain, nonatomic) NSNumber *publishTimeInterval; // @synthesize publishTimeInterval=_publishTimeInterval;
@property(retain, nonatomic) NSNumber *decayFactor; // @synthesize decayFactor=_decayFactor;
@property(retain, nonatomic) NSNumber *endThreshold; // @synthesize endThreshold=_endThreshold;
@property(retain, nonatomic) NSNumber *startThreshold; // @synthesize startThreshold=_startThreshold;
- (void).cxx_destruct;
- (void)_cancelPublishTimer;
- (void)_publishResultLocation:(id)arg1 reason:(long long)arg2;
- (void)flushLocations;
- (void)updatedLocations:(id)arg1 reason:(long long)arg2;
- (void)updatedLocations:(id)arg1;
- (void)startPublishingWithBlock:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

