//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FMCore/FMDaemon.h>

@class FMDServiceProvider, FMStateCapture, NSDate, NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

@interface FMDDaemon : FMDaemon
{
    _Bool _isFirstRunAfterBoot;
    _Bool _logLevelsMaxedOut;
    _Bool _startupComplete;
    NSDate *_startTime;
    NSMutableDictionary *_apsHandlers;
    NSObject<OS_dispatch_queue> *_apsHandlersModQueue;
    FMDServiceProvider *_activeServiceProvider;
    FMStateCapture *_stateCapture;
}

+ (id)sharedInstance;
@property(retain, nonatomic) FMStateCapture *stateCapture; // @synthesize stateCapture=_stateCapture;
@property(retain, nonatomic) FMDServiceProvider *activeServiceProvider; // @synthesize activeServiceProvider=_activeServiceProvider;
@property(nonatomic) _Bool startupComplete; // @synthesize startupComplete=_startupComplete;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *apsHandlersModQueue; // @synthesize apsHandlersModQueue=_apsHandlersModQueue;
@property(retain, nonatomic) NSMutableDictionary *apsHandlers; // @synthesize apsHandlers=_apsHandlers;
@property(nonatomic) _Bool logLevelsMaxedOut; // @synthesize logLevelsMaxedOut=_logLevelsMaxedOut;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(nonatomic) _Bool isFirstRunAfterBoot; // @synthesize isFirstRunAfterBoot=_isFirstRunAfterBoot;
- (void).cxx_destruct;
- (void)migrateAosnotifydStuff;
- (void)cleanupPostWipe;
- (void)waitForSpringBoard;
- (void)calculateFirstRunStatus;
- (void)migrateFromVersion:(id)arg1 toVersion:(id)arg2;
- (void)initialLaunchProcessing;
- (void)versionCheck;
- (id)xpcDistributedEventHandlers;
- (id)xpcDarwinEventHandlers;
- (void)startServiceProviders;
- (id)apsHandlerForEnvironment:(id)arg1;
- (void)checkInAllAPSHandlers;
- (void)_startupNowWithCompletion:(CDUnknownBlockType)arg1;
- (void)startupWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

@end

