//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDServerChannel-Protocol.h"
#import "NSURLSessionDelegate-Protocol.h"

@class NSHTTPCookieStorage, NSMutableDictionary, NSOperationQueue, NSRecursiveLock, NSString, NSURLSession, NSURLSessionConfiguration;

@interface FMDDirectServerChannel : NSObject <NSURLSessionDelegate, FMDServerChannel>
{
    NSURLSession *_session;
    NSURLSessionConfiguration *_sessionConfig;
    NSOperationQueue *_queue;
    NSMutableDictionary *_requests;
    NSRecursiveLock *_requestModifierLock;
    NSHTTPCookieStorage *_cookieStorage;
}

@property(retain, nonatomic) NSHTTPCookieStorage *cookieStorage; // @synthesize cookieStorage=_cookieStorage;
@property(retain, nonatomic) NSRecursiveLock *requestModifierLock; // @synthesize requestModifierLock=_requestModifierLock;
@property(retain, nonatomic) NSMutableDictionary *requests; // @synthesize requests=_requests;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSURLSessionConfiguration *sessionConfig; // @synthesize sessionConfig=_sessionConfig;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (void)_logRequestError:(id)arg1;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)supportsRequestType:(unsigned long long)arg1;
- (void)cancelAllRequests;
- (void)cancelRequestWithId:(id)arg1;
- (void)sendRequestWithId:(id)arg1 toURL:(id)arg2 withHeaders:(id)arg3 body:(id)arg4 completion:(CDUnknownBlockType)arg5;
@property(readonly, nonatomic) _Bool isActive;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

