//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FMDDispatchTransaction : NSObject
{
}

+ (id)transactionName:(id)arg1;
+ (void)dispatchTransactionSync:(id)arg1 transactionName:(id)arg2 block:(CDUnknownBlockType)arg3;
+ (void)dispatchTransactionAsync:(id)arg1 transactionName:(id)arg2 block:(CDUnknownBlockType)arg3;

@end

