//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol FMDDeviceDiscovering <NSObject>
@property(copy, nonatomic) CDUnknownBlockType didLoseDevice;
@property(copy, nonatomic) CDUnknownBlockType didDiscoverDevice;
@property(copy, nonatomic) CDUnknownBlockType didEndDiscovery;
- (void)stopDiscovery;
- (void)startDiscovery;
@end

