//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDEventLoggerFacility-Protocol.h"
#import "NSURLSessionDelegate-Protocol.h"

@class NSString, NSURLSession;

@interface FMDEventLoggerFacilityFMIPServer : NSObject <NSURLSessionDelegate, FMDEventLoggerFacility>
{
    NSURLSession *_defaultSession;
}

+ (id)facilityName;
@property(retain, nonatomic) NSURLSession *defaultSession; // @synthesize defaultSession=_defaultSession;
- (void).cxx_destruct;
- (id)splunkifyObject:(id)arg1 eventName:(id)arg2;
- (id)splunkifyDictionary:(id)arg1;
- (_Bool)shouldLog;
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;
- (void)reset;
- (void)logEvent:(id)arg1;
- (id)loggedEvents;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

