//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDEventLoggerEvent-Protocol.h"

@class NSMutableDictionary, NSNumber, NSString;

@interface FMDEventLoggerEventScalar : NSObject <FMDEventLoggerEvent>
{
    NSString *_groupByKey;
    NSNumber *_precision;
    NSMutableDictionary *_mutableDictionary;
    NSString *_eventName;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
@property(retain, nonatomic) NSMutableDictionary *mutableDictionary; // @synthesize mutableDictionary=_mutableDictionary;
@property(retain, nonatomic) NSNumber *precision; // @synthesize precision=_precision;
@property(retain, nonatomic) NSString *groupByKey; // @synthesize groupByKey=_groupByKey;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)userInfo;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)initWithEventName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

