//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDEventLoggerFacility-Protocol.h"

@class NSString;

@interface FMDEventLoggerFacilityDataPeek : NSObject <FMDEventLoggerFacility>
{
    NSString *_baseIdentifierKey;
}

+ (id)facilityName;
@property(retain, nonatomic) NSString *baseIdentifierKey; // @synthesize baseIdentifierKey=_baseIdentifierKey;
- (void).cxx_destruct;
- (_Bool)shouldLog;
- (void)reset;
- (void)logEvent:(id)arg1;
- (id)loggedEvents;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

