//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDAccount.h"

@class NSDate, NSString;

@interface FMDFMIPAccount : FMDAccount
{
    _Bool _lowBatteryLocateEnabled;
    NSString *_dsid;
    NSString *_adsid;
    NSString *_appleAccountIdentifier;
    NSString *_iCloudAuthToken;
    NSString *_fmipAuthToken;
    NSString *_lastLoggedInDsid;
    NSDate *_lastIdentityTime;
    unsigned long long _fmipEnableContext;
    unsigned long long _fmipDisableContext;
}

@property(nonatomic) _Bool lowBatteryLocateEnabled; // @synthesize lowBatteryLocateEnabled=_lowBatteryLocateEnabled;
@property(nonatomic) unsigned long long fmipDisableContext; // @synthesize fmipDisableContext=_fmipDisableContext;
@property(nonatomic) unsigned long long fmipEnableContext; // @synthesize fmipEnableContext=_fmipEnableContext;
@property(retain, nonatomic) NSDate *lastIdentityTime; // @synthesize lastIdentityTime=_lastIdentityTime;
@property(retain, nonatomic) NSString *lastLoggedInDsid; // @synthesize lastLoggedInDsid=_lastLoggedInDsid;
@property(retain, nonatomic) NSString *fmipAuthToken; // @synthesize fmipAuthToken=_fmipAuthToken;
@property(retain, nonatomic) NSString *iCloudAuthToken; // @synthesize iCloudAuthToken=_iCloudAuthToken;
@property(retain, nonatomic) NSString *appleAccountIdentifier; // @synthesize appleAccountIdentifier=_appleAccountIdentifier;
@property(retain, nonatomic) NSString *adsid; // @synthesize adsid=_adsid;
@property(retain, nonatomic) NSString *dsid; // @synthesize dsid=_dsid;
- (void).cxx_destruct;
- (void)copyInfoFromAccount:(id)arg1;
- (id)authToken;
- (id)authId;
- (_Bool)isActive;
- (void)applyPropertiesFromACAccount:(id)arg1;

@end

