//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDDictionaryRepresentable-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class FMDVolatileMetaDataRecord, NSDate, NSDictionary, NSString;
@protocol FMGeoLocatable;

@interface FMDLocation : NSObject <NSSecureCoding, FMDDictionaryRepresentable>
{
    unsigned char _positionType;
    NSDate *_timeStamp;
    NSObject<FMGeoLocatable> *_location;
    long long _eventType;
    FMDVolatileMetaDataRecord *_metaDataRecord;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) FMDVolatileMetaDataRecord *metaDataRecord; // @synthesize metaDataRecord=_metaDataRecord;
@property(nonatomic) unsigned char positionType; // @synthesize positionType=_positionType;
@property(nonatomic) long long eventType; // @synthesize eventType=_eventType;
@property(retain, nonatomic) NSObject<FMGeoLocatable> *location; // @synthesize location=_location;
@property(retain, nonatomic) NSDate *timeStamp; // @synthesize timeStamp=_timeStamp;
- (void).cxx_destruct;
- (id)_trackedLocationTypeAsString:(unsigned char)arg1;
- (id)stringForLocationType:(long long)arg1;
@property(readonly, nonatomic) NSDictionary *dictionaryValue;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithLocation:(id)arg1 eventType:(long long)arg2 positionType:(unsigned char)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

