//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVQueuePlayer;

@interface FMDLoopPlayer : NSObject
{
    _Bool _addedObservers;
    AVQueuePlayer *_player;
}

@property(nonatomic) _Bool addedObservers; // @synthesize addedObservers=_addedObservers;
@property(retain, nonatomic) AVQueuePlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)playbackInLoopWithURL:(id)arg1;
- (void)stopObservingPlayerAndItem;
- (void)startObservingPlayerAndItem;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)stop;
- (void)playURL:(id)arg1;
- (id)initWithPlayer:(id)arg1;

@end

