//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface FMDLocationManagerFactory : NSObject
{
    NSMutableArray *_locationManagers;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *locationManagers; // @synthesize locationManagers=_locationManagers;
- (void).cxx_destruct;
- (void)_discardLocationManager:(id)arg1;
- (id)_newCLLocationManager;
- (id)newLocationManager;
- (id)init;

@end

