//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDAccessoryRegistryDataSource-Protocol.h"

@class NSString;
@protocol FMDNanoRegistryDelegate;

@interface FMDNanoRegistry : NSObject <FMDAccessoryRegistryDataSource>
{
    NSObject<FMDNanoRegistryDelegate> *_delegate;
}

@property(nonatomic) __weak NSObject<FMDNanoRegistryDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)automationAccessories;
- (void)deviceDidUnpair:(id)arg1;
- (void)deviceDidPair:(id)arg1;
- (id)accessoriesWithProperty:(id)arg1;
- (id)migratableAccessoriesByIdentifier;
- (id)migratableAccessories;
- (id)pairedAccessories;
- (id)allAccessories;
- (void)getAccessoriesWithCompletion:(CDUnknownBlockType)arg1;
- (void)addObservers;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

