//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDNanoRegistryAccessory.h"

#import "FMDDictionaryRepresentable-Protocol.h"

@class FMDAccessoryIdentifier, NSDictionary, NSString;

@interface FMDNanoRegistryAutomationAccessory : FMDNanoRegistryAccessory <FMDDictionaryRepresentable>
{
    _Bool _paired;
    _Bool _migrationPossible;
    FMDAccessoryIdentifier *_accessoryIdentifier;
    NSString *_udid;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSString *udid; // @synthesize udid=_udid;
@property(nonatomic) _Bool migrationPossible; // @synthesize migrationPossible=_migrationPossible;
@property(nonatomic) _Bool paired; // @synthesize paired=_paired;
@property(retain, nonatomic) FMDAccessoryIdentifier *accessoryIdentifier; // @synthesize accessoryIdentifier=_accessoryIdentifier;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)lastDiscoveryDate;
- (id)name;
- (id)buildVersion;
- (id)productVersion;
- (id)productType;
- (id)serialNumber;
@property(readonly, nonatomic) NSDictionary *dictionaryValue;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

