//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData, NSString;

@interface FMDNanoSupportProtoSignedDataV4 : PBCodable <NSCopying>
{
    NSData *_finalRequestJsonData;
    NSData *_refKeyAttestation;
    NSString *_refKeyError;
    NSData *_refKeySignature;
    NSString *_signatureError;
    NSData *_signedData;
    NSData *_skAuth;
    _Bool _errorOccurred;
}

@property(retain, nonatomic) NSString *signatureError; // @synthesize signatureError=_signatureError;
@property(retain, nonatomic) NSString *refKeyError; // @synthesize refKeyError=_refKeyError;
@property(retain, nonatomic) NSData *finalRequestJsonData; // @synthesize finalRequestJsonData=_finalRequestJsonData;
@property(retain, nonatomic) NSData *refKeyAttestation; // @synthesize refKeyAttestation=_refKeyAttestation;
@property(retain, nonatomic) NSData *refKeySignature; // @synthesize refKeySignature=_refKeySignature;
@property(retain, nonatomic) NSData *skAuth; // @synthesize skAuth=_skAuth;
@property(retain, nonatomic) NSData *signedData; // @synthesize signedData=_signedData;
@property(nonatomic) _Bool errorOccurred; // @synthesize errorOccurred=_errorOccurred;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasSignatureError;
@property(readonly, nonatomic) _Bool hasRefKeyError;
@property(readonly, nonatomic) _Bool hasFinalRequestJsonData;
@property(readonly, nonatomic) _Bool hasRefKeyAttestation;
@property(readonly, nonatomic) _Bool hasRefKeySignature;
@property(readonly, nonatomic) _Bool hasSkAuth;
@property(readonly, nonatomic) _Bool hasSignedData;

@end

