//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDCiphering-Protocol.h"

@class NSData, NSDictionary, NSString;

@interface FMDOneShotCipher : NSObject <FMDCiphering>
{
    NSData *_initializationVector;
    NSData *_key;
    NSData *_tag;
}

@property(retain, nonatomic) NSData *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSData *key; // @synthesize key=_key;
@property(retain, nonatomic) NSData *initializationVector; // @synthesize initializationVector=_initializationVector;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *dictionaryValue;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

