//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDConcurrentMutableDictionary;

@interface FMDPowerMgr : NSObject
{
    FMDConcurrentMutableDictionary *_assertionsDict;
}

+ (id)sharedInstance;
@property(retain, nonatomic) FMDConcurrentMutableDictionary *assertionsDict; // @synthesize assertionsDict=_assertionsDict;
- (void).cxx_destruct;
- (void)_disableAssertion:(unsigned int)arg1 withName:(id)arg2;
- (void)powerAssertionDisableWithReason:(id)arg1;
- (void)powerAssertionEnableWithReason:(id)arg1 type:(id)arg2 timeout:(long long)arg3 appliesOnLidClose:(_Bool)arg4;
- (void)powerAssertionEnableWithReason:(id)arg1 type:(id)arg2 timeout:(long long)arg3;
- (void)powerAssertionEnableWithReason:(id)arg1 type:(id)arg2 appliesOnLidClose:(_Bool)arg3;
- (void)powerAssertionEnableWithReason:(id)arg1 type:(id)arg2;
- (void)powerAssertionEnableWithReason:(id)arg1 timeout:(long long)arg2;
- (void)powerAssertionEnableWithReason:(id)arg1;
- (id)init;

@end

