//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDRequest.h"

@class FMDServiceProvider, NSString, NSUUID;

@interface FMDRequestIdentityV3Session : FMDRequest
{
    _Bool _requiresAuthentication;
    NSString *_cause;
    FMDServiceProvider *_provider;
    NSString *_pscHelloMsg;
    NSUUID *_activationLockRequestUUID;
}

@property(retain, nonatomic) NSUUID *activationLockRequestUUID; // @synthesize activationLockRequestUUID=_activationLockRequestUUID;
@property(retain, nonatomic) NSString *pscHelloMsg; // @synthesize pscHelloMsg=_pscHelloMsg;
@property(nonatomic) __weak FMDServiceProvider *provider; // @synthesize provider=_provider;
@property(nonatomic) _Bool requiresAuthentication; // @synthesize requiresAuthentication=_requiresAuthentication;
@property(retain, nonatomic) NSString *cause; // @synthesize cause=_cause;
- (void).cxx_destruct;
- (_Bool)canReplace:(id)arg1;
- (_Bool)canRequestBeRetriedNow;
- (id)requestBody;
- (id)requestHeaders;
- (id)requestUrl;
- (unsigned long long)type;
- (id)requestId;
- (id)initWithProvider:(id)arg1 activationLockRequestUUID:(id)arg2 pscHelloMsg:(id)arg3;

@end

