//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDRequest.h"

@class FMDLocation;

@interface FMDRequestCurrentLocation : FMDRequest
{
    _Bool _finalLocation;
    FMDLocation *_location;
    long long _publishReason;
    double _accuracyChange;
    double _cacheValidityDuration;
}

@property(nonatomic) double cacheValidityDuration; // @synthesize cacheValidityDuration=_cacheValidityDuration;
@property(nonatomic) double accuracyChange; // @synthesize accuracyChange=_accuracyChange;
@property(nonatomic) long long publishReason; // @synthesize publishReason=_publishReason;
@property(nonatomic) _Bool finalLocation; // @synthesize finalLocation=_finalLocation;
@property(retain, nonatomic) FMDLocation *location; // @synthesize location=_location;
- (void).cxx_destruct;
- (_Bool)canReplace:(id)arg1;
- (_Bool)canRequestBeRetriedNow;
- (long long)maxConsecutiveNetworkNotificationRetries;
- (long long)maxNonNetworkRelatedRetries;
- (long long)maxTimerBasedNetworkRetries;
- (id)requestBody;
- (id)urlTemplateType;
- (id)initWithAccount:(id)arg1 location:(id)arg2 finalLocation:(_Bool)arg3 reason:(long long)arg4 accuracyChange:(double)arg5 cacheValidityDuration:(double)arg6;

@end

