//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDRequest.h"

@class NSString;

@interface FMDRequestRegister : FMDRequest
{
    NSString *_cause;
}

@property(retain, nonatomic) NSString *cause; // @synthesize cause=_cause;
- (void).cxx_destruct;
- (_Bool)canReplace:(id)arg1;
- (long long)maxConsecutiveNetworkNotificationRetries;
- (long long)maxNonNetworkRelatedRetries;
- (double)maxRetryInterval;
- (id)urlTemplateType;

@end

