//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDRequest.h"

@class FMDServiceProvider, NSData, NSString, NSUUID;

@interface FMDRequestIdentityV5 : FMDRequest
{
    FMDServiceProvider *_provider;
    NSString *_signatureHeader;
    NSString *_skAuthHeader;
    NSString *_refKeyAttestationHeader;
    NSString *_refKeySignatureHeader;
    NSString *_baaAttestationHeader;
    NSString *_baaSignatureHeader;
    NSData *_requestBodyDataForSignature;
    NSUUID *_activationLockRequestUUID;
    NSString *_signatureError;
    NSString *_refKeyError;
    NSString *_baaError;
    NSString *_refKeyErrorDescription;
}

@property(retain, nonatomic) NSString *refKeyErrorDescription; // @synthesize refKeyErrorDescription=_refKeyErrorDescription;
@property(retain, nonatomic) NSString *baaError; // @synthesize baaError=_baaError;
@property(retain, nonatomic) NSString *refKeyError; // @synthesize refKeyError=_refKeyError;
@property(retain, nonatomic) NSString *signatureError; // @synthesize signatureError=_signatureError;
@property(retain, nonatomic) NSUUID *activationLockRequestUUID; // @synthesize activationLockRequestUUID=_activationLockRequestUUID;
@property(retain, nonatomic) NSData *requestBodyDataForSignature; // @synthesize requestBodyDataForSignature=_requestBodyDataForSignature;
@property(retain, nonatomic) NSString *baaSignatureHeader; // @synthesize baaSignatureHeader=_baaSignatureHeader;
@property(retain, nonatomic) NSString *baaAttestationHeader; // @synthesize baaAttestationHeader=_baaAttestationHeader;
@property(retain, nonatomic) NSString *refKeySignatureHeader; // @synthesize refKeySignatureHeader=_refKeySignatureHeader;
@property(retain, nonatomic) NSString *refKeyAttestationHeader; // @synthesize refKeyAttestationHeader=_refKeyAttestationHeader;
@property(retain, nonatomic) NSString *skAuthHeader; // @synthesize skAuthHeader=_skAuthHeader;
@property(retain, nonatomic) NSString *signatureHeader; // @synthesize signatureHeader=_signatureHeader;
@property(nonatomic) __weak FMDServiceProvider *provider; // @synthesize provider=_provider;
- (void).cxx_destruct;
- (void)_calculateSignatureForBody:(id)arg1 ucrtSigningSession:(id)arg2;
- (_Bool)canReplace:(id)arg1;
- (_Bool)canRequestBeRetriedNow;
- (long long)maxConsecutiveNetworkNotificationRetries;
- (long long)maxNonNetworkRelatedRetries;
- (double)maxRetryInterval;
- (id)requestBody;
- (id)requestBodyData;
- (id)requestHeaders;
- (id)requestUrl;
- (id)initWithProvider:(id)arg1;

@end

