//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDRequest.h"

@class FMDAccount, NSDictionary, NSURL;

@interface FMDRequestAckTrack : FMDRequest
{
    FMDAccount *_account;
    NSDictionary *_trackCommand;
    NSURL *_ackURL;
}

@property(retain, nonatomic) NSURL *ackURL; // @synthesize ackURL=_ackURL;
@property(retain, nonatomic) NSDictionary *trackCommand; // @synthesize trackCommand=_trackCommand;
@property(retain, nonatomic) FMDAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (_Bool)canReplace:(id)arg1;
- (id)requestBody;
- (id)requestUrl;
- (id)initWithAccount:(id)arg1 trackCommand:(id)arg2 ackURL:(id)arg3;

@end

