//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDRequest.h"

@class FMDServiceProvider, NSData, NSString;

@interface FMDRequestIdentity : FMDRequest
{
    FMDServiceProvider *_provider;
    NSString *_signatureHeader;
    NSData *_requestBodyDataForSignature;
}

@property(retain, nonatomic) NSData *requestBodyDataForSignature; // @synthesize requestBodyDataForSignature=_requestBodyDataForSignature;
@property(retain, nonatomic) NSString *signatureHeader; // @synthesize signatureHeader=_signatureHeader;
@property(nonatomic) __weak FMDServiceProvider *provider; // @synthesize provider=_provider;
- (void).cxx_destruct;
- (void)_calculateSignatureForBody:(id)arg1;
- (_Bool)canReplace:(id)arg1;
- (_Bool)canRequestBeRetriedNow;
- (long long)maxConsecutiveNetworkNotificationRetries;
- (long long)maxNonNetworkRelatedRetries;
- (double)maxRetryInterval;
- (id)requestBody;
- (id)requestBodyData;
- (id)requestHeaders;
- (id)requestUrl;
- (id)initWithProvider:(id)arg1;

@end

