//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMDRequest.h"

@class FMDAccount, FMDFMIPMissingDeviceInfo, NSString;

@interface FMDRequestMissingDevice : FMDRequest
{
    FMDAccount *_account;
    FMDFMIPMissingDeviceInfo *_missingDeviceInfo;
    NSString *_shortLivedToken;
}

@property(retain, nonatomic) NSString *shortLivedToken; // @synthesize shortLivedToken=_shortLivedToken;
@property(retain, nonatomic) FMDFMIPMissingDeviceInfo *missingDeviceInfo; // @synthesize missingDeviceInfo=_missingDeviceInfo;
@property(retain, nonatomic) FMDAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (_Bool)canReplace:(id)arg1;
- (_Bool)canRequestBeRetriedNow;
- (_Bool)showAuthFailedMessage;
- (id)authToken;
- (id)requestBody;
- (id)urlTemplateType;
- (id)initWithAccount:(id)arg1 token:(id)arg2 andMissingDeviceInfo:(id)arg3;

@end

