//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FMDAccount, FMDRequest, FMDServerInteractionController;

@protocol FMDServerInteractionControllerDelegate <NSObject>
- (void)didReceiveServerAlertForRequest:(FMDRequest *)arg1;
- (void)didReceiveAuthFailureForRequest:(FMDRequest *)arg1;

@optional
- (FMDAccount *)accountForServerInteractionController:(FMDServerInteractionController *)arg1;
@end

