//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"

@class FMNanoIDSManager, NSString, NSXPCListener;

@interface FMDXPCManager : NSObject <NSXPCListenerDelegate>
{
    NSXPCListener *_fmdXPCListener;
    NSXPCListener *_fmdUserAgentXPCListener;
    FMNanoIDSManager *_protectedIDSManager;
}

+ (id)sharedInstance;
@property(retain, nonatomic) FMNanoIDSManager *protectedIDSManager; // @synthesize protectedIDSManager=_protectedIDSManager;
@property(retain, nonatomic) NSXPCListener *fmdUserAgentXPCListener; // @synthesize fmdUserAgentXPCListener=_fmdUserAgentXPCListener;
@property(retain, nonatomic) NSXPCListener *fmdXPCListener; // @synthesize fmdXPCListener=_fmdXPCListener;
- (void).cxx_destruct;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)initializeXPC;
- (void)dealloc;
- (id)initSingleton;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

