//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSNumber;

@protocol FMLocatorPublishing <NSObject>
@property(retain, nonatomic) NSNumber *cachedLocationValidityTimeInterval;
@property(retain, nonatomic) NSNumber *publishTimeInterval;
@property(retain, nonatomic) NSNumber *decayFactor;
@property(retain, nonatomic) NSNumber *minimumDistance;
@property(retain, nonatomic) NSNumber *endThreshold;
@property(retain, nonatomic) NSNumber *startThreshold;
- (void)flushLocations;
- (void)updatedLocations:(NSArray *)arg1 reason:(long long)arg2;
- (void)updatedLocations:(NSArray *)arg1;
- (void)startPublishingWithBlock:(void (^)(NSError *, NSObject<FMGeoLocatable> *, long long))arg1;
@end

