//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ServiceHostRegistry : NSObject
{
    NSString *_registeredHostBundleId;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSString *registeredHostBundleId; // @synthesize registeredHostBundleId=_registeredHostBundleId;
- (void).cxx_destruct;

@end

