//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIVisualEffectView.h>

@class UIColor;

@interface _TtC8AppStore21PaletteBackgroundView : UIVisualEffectView
{
    // Error parsing type: , name: tintView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithEffect:(id)arg1;
@property(nonatomic, retain) UIColor *legacyBackgroundTintColor;
- (void)layoutSubviews;

@end

