//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class _TtC8AppStore21AppShowcaseLockupView, _TtC8AppStore9VideoView;

@interface _TtC8AppStore29AppShowcaseCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: lockupView
    // Error parsing type: , name: videoContainer
    // Error parsing type: , name: showcaseType
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isVideoHidden;
@property(nonatomic, retain) _TtC8AppStore9VideoView *videoView;
@property(nonatomic, readonly) _TtC8AppStore21AppShowcaseLockupView *lockupView; // @synthesize lockupView;
- (void)didSelect:(id)arg1;

@end

