//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASDJobManagerObserver-Protocol.h"

@class ASDJobManager;

@interface _TtC8AppStore18JobManagerObserver : NSObject <ASDJobManagerObserver>
{
    // Error parsing type: , name: observers
    // Error parsing type: , name: jobManager
}

+ (id)shared;
- (CDUnknownBlockType).cxx_destruct;
- (void)jobManager:(id)arg1 completedJobs:(id)arg2;
- (void)jobManager:(id)arg1 updatedProgressOfJobs:(id)arg2;
- (void)jobManager:(id)arg1 updatedStateOfJobs:(id)arg2;
- (void)jobManager:(id)arg1 changedJobs:(id)arg2;
- (void)dealloc;
- (id)init;
@property(nonatomic, readonly) ASDJobManager *jobManager; // @synthesize jobManager;

@end

