//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UILabel, UIStackView, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore31ProductRatingCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: currentRatingLabel
    // Error parsing type: , name: outOfRatingLabel
    // Error parsing type: , name: ratingCountLabel
    // Error parsing type: , name: ratingBreakdownStack
    // Error parsing type: , name: statusLabel
    // Error parsing type: , name: pageTraits
}

+ (id)ratingCountFont;
- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilityStatusLabel;
@property(nonatomic, readonly) UILabel *accessibilityCurrentRatingLabel;
- (void)setStatus:(id)arg1;
- (void)clearAllRatings;
- (void)setCurrentRatingWithRating:(float)arg1;
- (void)setRatingWithProportion:(float)arg1 at:(long long)arg2;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UIStackView *ratingBreakdownStack; // @synthesize ratingBreakdownStack;
@property(nonatomic, readonly) UILabel *ratingCountLabel; // @synthesize ratingCountLabel;
@property(nonatomic, readonly) UILabel *outOfRatingLabel; // @synthesize outOfRatingLabel;

@end

