//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UINavigationController;

@interface _TtC8AppStore30ArticleContainerViewController : UIViewController
{
    // Error parsing type: , name: wrapperViewController
    // Error parsing type: , name: articleViewController
}

+ (id)prepareForPresentationOf:(id)arg1 containedIn:(id)arg2;
+ (_Bool)shouldUseContainer;
+ (double)compactSizeClassHorizontalCutoff;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithWrapperViewController:(id)arg1 articleViewController:(id)arg2;
@property(nonatomic, readonly) UIViewController *articleViewController; // @synthesize articleViewController;
@property(nonatomic, readonly) UINavigationController *wrapperViewController; // @synthesize wrapperViewController;

@end

