//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@class UIViewController;

@interface _TtC8AppStore24FlowNavigationController : UINavigationController
{
    // Error parsing type: , name: flowController
    // Error parsing type: , name: actionRunner
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithRootViewController:(id)arg1;
- (id)popToRootViewControllerAnimated:(_Bool)arg1;
@property(nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
@property(nonatomic, readonly) UIViewController *childViewControllerForStatusBarStyle;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNavigationBarClass:(Class)arg1 toolbarClass:(Class)arg2;

@end

