//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSString, _TtC8AppStore11DividerView;

@interface _TtC8AppStore26FootnoteCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: text
    // Error parsing type: , name: textLabel
    // Error parsing type: , name: dividerView
    // Error parsing type: , name: hasChevron
    // Error parsing type: , name: chevronView
    // Error parsing type: , name: textLightensOnHighlight
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;
@property(nonatomic) _Bool textLightensOnHighlight; // @synthesize textLightensOnHighlight;
@property(nonatomic) _Bool hasChevron; // @synthesize hasChevron;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) _TtC8AppStore11DividerView *dividerView; // @synthesize dividerView;
@property(nonatomic, copy) NSString *text; // @synthesize text;

@end

