//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class OS_dispatch_queue;

@interface _TtC8AppStore35LibraryInAppPurchaseStateDataSource : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: accessQueue
    // Error parsing type: , name: expectedAppStates
    // Error parsing type: , name: previouslyExistingAdamIds
    // Error parsing type: , name: database
    // Error parsing type: , name: notificationToken
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)refreshDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)dealloc;
@property(nonatomic, readonly) OS_dispatch_queue *accessQueue; // @synthesize accessQueue;

@end

