//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class _TtC8AppStore11ArtworkView;

@interface _TtC8AppStore22BorderedScreenshotView : UIView
{
    // Error parsing type: , name: appPlatform
    // Error parsing type: , name: chromeBorderView
    // Error parsing type: , name: artworkView
    // Error parsing type: , name: displayConfiguration
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) struct CGSize preferredArtworkSize;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *imageView;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) _TtC8AppStore11ArtworkView *artworkView; // @synthesize artworkView;

@end

