//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSArray, UIView, _TtC8AppStore39ScreenshotShelfCollectionViewFlowLayout;

@interface _TtC8AppStore33ScreenshotShelfCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: appPlatform
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: flowLayout
    // Error parsing type: , name: screenshotFetcher
    // Error parsing type: , name: pageTraits
    // Error parsing type: , name: topAccessoryView
    // Error parsing type: , name: bottomAccessoryView
    // Error parsing type: , name: artwork
    // Error parsing type: , name: sizedArtwork
    // Error parsing type: , name: didSelectHandler
}

- (CDUnknownBlockType).cxx_destruct;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(nonatomic, copy) CDUnknownBlockType didSelectHandler; // @synthesize didSelectHandler;
@property(nonatomic, readonly) _Bool hasPortraitPhoneArtwork;
@property(nonatomic, copy) NSArray *artwork; // @synthesize artwork;
@property(nonatomic, retain) UIView *bottomAccessoryView; // @synthesize bottomAccessoryView;
@property(nonatomic, retain) UIView *topAccessoryView; // @synthesize topAccessoryView;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGSize containerSize;
@property(nonatomic, readonly) _TtC8AppStore39ScreenshotShelfCollectionViewFlowLayout *flowLayout; // @synthesize flowLayout;

@end

