//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore37InAppPurchaseLockupCollectionViewCell.h"

@class _TtC8AppStore11ArtworkView;

@interface _TtC8AppStore45InAppPurchaseNonTiledLockupCollectionViewCell : _TtC8AppStore37InAppPurchaseLockupCollectionViewCell
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGSize preferredArtworkSize;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *artworkView;
- (void)didSelect:(id)arg1;

@end

