//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

@class NSString;

@interface _TtC8AppStore9SearchBar : UITextField
{
    // Error parsing type: , name: searchBarDelegate
}

+ (double)accessoryViewPadding;
+ (struct CGSize)leftViewSize;
+ (double)preferredHeight;
- (CDUnknownBlockType).cxx_destruct;
- (void)valueChangedWithUserInitiated:(_Bool)arg1;
- (void)valueChangedByUser;
- (void)clearSearchText;
- (struct CGRect)rightViewRectForBounds:(struct CGRect)arg1;
- (struct CGRect)leftViewRectForBounds:(struct CGRect)arg1;
- (struct CGRect)placeholderRectForBounds:(struct CGRect)arg1;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSString *placeholder;
- (void)setText:(id)arg1 userInitiated:(_Bool)arg2;
@property(nonatomic, copy) NSString *text;

@end

