//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore16DynamicTypeLabel.h"

@class _TtC8AppStore17DynamicTypeButton;

@interface _TtC8AppStore18ExpandableTextView : _TtC8AppStore16DynamicTypeLabel
{
    // Error parsing type: , name: moreButton
    // Error parsing type: , name: hasMoreButton
    // Error parsing type: , name: collapsedNumberOfLines
    // Error parsing type: , name: isCollapsed
    // Error parsing type: , name: moreTapHandler
}

+ (_Bool)isTruncatedFor:(id)arg1 layoutMargins:(struct UIEdgeInsets)arg2 collapsedNumberOfLines:(long long)arg3 fitting:(struct CGSize)arg4;
+ (struct CGSize)itemSizeForAttributedText:(id)arg1 isCollapsed:(_Bool)arg2 layoutMargins:(struct UIEdgeInsets)arg3 collapsedNumberOfLines:(long long)arg4 fitting:(struct CGSize)arg5;
+ (struct CGSize)itemSizeForText:(id)arg1 isCollapsed:(_Bool)arg2 layoutMargins:(struct UIEdgeInsets)arg3 collapsedNumberOfLines:(long long)arg4 fitting:(struct CGSize)arg5;
+ (long long)defaultCollapsedNumberOfLines;
- (CDUnknownBlockType).cxx_destruct;
- (void)moreFrom:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType moreTapHandler; // @synthesize moreTapHandler;
@property(nonatomic) _Bool isCollapsed; // @synthesize isCollapsed;
@property(nonatomic) long long collapsedNumberOfLines; // @synthesize collapsedNumberOfLines;
@property(nonatomic) _Bool hasMoreButton; // @synthesize hasMoreButton;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)tintColorDidChange;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) _TtC8AppStore17DynamicTypeButton *moreButton; // @synthesize moreButton;

@end

