//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel, _TtC8AppStore11ArtworkView, _TtC8AppStore11OfferButton, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore15SmallLockupView : UIView
{
    // Error parsing type: , name: artworkView
    // Error parsing type: , name: ordinalLabel
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
    // Error parsing type: , name: subtitleButton
    // Error parsing type: , name: offerButton
    // Error parsing type: , name: artworkSize
    // Error parsing type: , name: imageLabelMargin
    // Error parsing type: , name: labelLineCount
    // Error parsing type: , name: titleRegularSpace
    // Error parsing type: , name: titleCompressedSpace
    // Error parsing type: , name: subtitleSpace
    // Error parsing type: , name: bottomSpace
    // Error parsing type: , name: hasSubtitleButton
    // Error parsing type: , name: subtitleButtonClickHandler
}

+ (double)subtitleButtonToLabelMargin;
+ (double)labelButtonMargin;
+ (struct CGSize)preferredArtworkSize;
- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) UILabel *accessibilitybuyBadgeLabel;
- (void)subtitleButtonTrampolineWithSender:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType subtitleButtonClickHandler; // @synthesize subtitleButtonClickHandler;
@property(nonatomic) _Bool hasSubtitleButton; // @synthesize hasSubtitleButton;
- (void)layoutSubviews;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(nonatomic) long long labelLineCount; // @synthesize labelLineCount;
@property(nonatomic) double imageLabelMargin; // @synthesize imageLabelMargin;
@property(nonatomic) struct CGSize artworkSize; // @synthesize artworkSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 backgroundBlur:(id)arg2;
@property(nonatomic, readonly) _TtC8AppStore11OfferButton *offerButton; // @synthesize offerButton;
@property(nonatomic, retain) UIButton *subtitleButton; // @synthesize subtitleButton;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *ordinalLabel; // @synthesize ordinalLabel;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *artworkView; // @synthesize artworkView;
- (void)applyWithLockup:(id)arg1;

@end

