//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/_UINavigationBarTitleView.h>

@class _TtC8AppStore11ArtworkView;

@interface _TtC8AppStore16ProductTitleView : _UINavigationBarTitleView
{
    // Error parsing type: , name: iconView
    // Error parsing type: , name: offerButton
    // Error parsing type: , name: iconWidth
    // Error parsing type: , name: animationVerticalOffset
    // Error parsing type: , name: iconAspectRatio
    // Error parsing type: , name: navigationBarMode
    // Error parsing type: , name: offerButtonMode
    // Error parsing type: , name: collisionVisibility
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (void)contentDidChange;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) long long offerButtonMode; // @synthesize offerButtonMode;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *iconView; // @synthesize iconView;

@end

