//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface _TtC8AppStore10BorderView : UIView
{
}

@property(nonatomic) _Bool clipsToBounds;
@property(nonatomic, retain) UIColor *backgroundColor;
@property(nonatomic) unsigned long long roundedCorners;
@property(nonatomic) double borderWidth;
@property(nonatomic, retain) UIColor *borderColor;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

