//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, _TtC8AppStore15SmallLockupView, _TtC8AppStore16DynamicTypeLabel, _TtC8AppStore17LockupScreenshots;

@interface _TtC8AppStore21ScreenshotsLockupView : UIView
{
    // Error parsing type: , name: lockupView
    // Error parsing type: , name: screenshots
    // Error parsing type: , name: taglineLabel
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSString *tagline;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *taglineLabel; // @synthesize taglineLabel;
@property(nonatomic, retain) _TtC8AppStore17LockupScreenshots *screenshots; // @synthesize screenshots;
@property(nonatomic, retain) _TtC8AppStore15SmallLockupView *lockupView; // @synthesize lockupView;
- (void)applyWithLockup:(id)arg1;

@end

