//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class NSDictionary;

@interface _TtC8AppStore25ShelfDisplayingFlowLayout : UICollectionViewFlowLayout
{
    // Error parsing type: , name: multiColumnMinYBySection
    // Error parsing type: , name: multiColumnOrigins
}

+ (id)shelfBackgroundReusableViewKind;
- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, copy) NSDictionary *multiColumnOrigins; // @synthesize multiColumnOrigins;
@property(nonatomic, copy) NSDictionary *multiColumnMinYBySection; // @synthesize multiColumnMinYBySection;
- (id)invalidationContextForBoundsChange:(struct CGRect)arg1;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayout;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(nonatomic, readonly) struct CGRect collectionViewBounds;

@end

