//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class OS_dispatch_queue;

@interface _TtC8AppStore27PurchasesAppStateDataSource : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: accessQueue
    // Error parsing type: , name: callbackQueue
    // Error parsing type: , name: expectedAppStates
    // Error parsing type: , name: lastAccountId
    // Error parsing type: , name: additionalFamilyMembers
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)_refreshDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)refreshDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)updatePurchasesDatabaseWithCompletion:(CDUnknownBlockType)arg1;
- (void)purchaseDatabaseUpdated:(id)arg1;
- (void)dealloc;
- (id)initWithAdditionalFamilyMembers:(id)arg1;
@property(nonatomic, readonly) OS_dispatch_queue *callbackQueue; // @synthesize callbackQueue;
@property(nonatomic, readonly) OS_dispatch_queue *accessQueue; // @synthesize accessQueue;

@end

