//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, _TtC8AppStore10BorderView;

@interface _TtC8AppStore17RoundedCornerView : UIView
{
    // Error parsing type: , name: cornerRadius
    // Error parsing type: , name: cornerStyle
    // Error parsing type: , name: roundedCorners
    // Error parsing type: , name: borderView
    // Error parsing type: , name: borderColor
    // Error parsing type: , name: borderWidth
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(nonatomic, retain) UIColor *borderColor; // @synthesize borderColor;
- (void)updateBorder;
@property(nonatomic, retain) _TtC8AppStore10BorderView *borderView; // @synthesize borderView;
@property(nonatomic) unsigned long long roundedCorners; // @synthesize roundedCorners;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius;

@end

