//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@interface _TtC8AppStore20InstallProgressLayer : CALayer
{
    // Error parsing type: , name: stageColor
    // Error parsing type: , name: originAngle
}

+ (_Bool)needsDisplayForKey:(id)arg1;
+ (id)exitAnimation;
+ (id)enterAnimation;
+ (double)exitAnimationDuration;
+ (double)progressAnimationDuration;
+ (double)enterAnimationDuration;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithLayer:(id)arg1;
- (id)init;
- (void)drawRingIn:(struct CGContext *)arg1;
- (void)drawExitIn:(struct CGContext *)arg1;
- (void)drawBackgroundIn:(struct CGContext *)arg1;
- (void)drawInContext:(struct CGContext *)arg1;
- (id)actionForKey:(id)arg1;
- (void)addExitAnimation;
- (void)addEnterAnimation;

// Remaining properties
@property(nonatomic) double enterProgress; // @dynamic enterProgress;
@property(nonatomic) double exitProgress; // @dynamic exitProgress;
@property(nonatomic) double progress; // @dynamic progress;

@end

