//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore8LinkView : UIView
{
    // Error parsing type: , name: descriptionLabel
    // Error parsing type: , name: summaryLabel
    // Error parsing type: , name: disclosureIndicator
}

+ (double)heightForDescription:(id)arg1 summary:(id)arg2 fitting:(double)arg3 traits:(id)arg4 layoutMargins:(struct UIEdgeInsets)arg5;
+ (double)cornerRadius;
+ (id)defaultBackgroundColor;
+ (id)disclosureIndicatorImage;
+ (struct UIEdgeInsets)defaultLayoutMargins;
+ (double)labelDisclosureIndicatorMargin;
- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(nonatomic, readonly) UIView *disclosureIndicator; // @synthesize disclosureIndicator;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *summaryLabel; // @synthesize summaryLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *descriptionLabel; // @synthesize descriptionLabel;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

