//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC8AppStore17EditorsChoiceView : UIView
{
    // Error parsing type: , name: preferredLineCount
    // Error parsing type: , name: size
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: shouldCapWidthByAvailableWidth
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) double lastBaselineFromBottom;
@property(nonatomic, readonly) double lastBaselineMaxY;
- (void)tintColorDidChange;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithCoder:(id)arg1;

@end

