//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class _TtC8AppStore16DynamicTypeLabel, _TtC8AppStore9StackView;

@interface _TtC8AppStore10BundleView : UIView
{
    // Error parsing type: , name: titleHorizontalMargin
    // Error parsing type: , name: cornerRadius
    // Error parsing type: , name: iconStyle
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: itemStack
    // Error parsing type: , name: itemReusePool
}

+ (long long)maxBundleChildren;
- (CDUnknownBlockType).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)addWithBundleChildren:(id)arg1;
- (void)prepareForReuse;
@property(nonatomic, readonly) _TtC8AppStore9StackView *itemStack; // @synthesize itemStack;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *titleLabel; // @synthesize titleLabel;

@end

