//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIView, _TtC8AppStore16DynamicTypeLabel, _TtC8AppStore18ExpandableTextView;

@interface _TtC8AppStore33TitledParagraphCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: expandableTextView
    // Error parsing type: , name: primarySubtitleLabel
    // Error parsing type: , name: secondarySubtitleLabel
    // Error parsing type: , name: detailStyle
    // Error parsing type: , name: separatorView
    // Error parsing type: , name: pageTraits
}

+ (double)regularGridColumnCount;
+ (id)detailStylePrimarySubtitleFontColor;
+ (id)standardStylePrimarySubtitleFontColor;
- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UIView *separatorView; // @synthesize separatorView;
@property(nonatomic) _Bool detailStyle; // @synthesize detailStyle;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *secondarySubtitleLabel; // @synthesize secondarySubtitleLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *primarySubtitleLabel; // @synthesize primarySubtitleLabel;
@property(nonatomic, readonly) _TtC8AppStore18ExpandableTextView *expandableTextView; // @synthesize expandableTextView;

@end

