//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class _TtC11AppStoreKit6Action, _TtC8AppStore17DynamicTypeButton;

@interface _TtC8AppStore31RoundedButtonCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: button
    // Error parsing type: , name: dividerView
    // Error parsing type: , name: action
    // Error parsing type: , name: hasDivider
}

- (CDUnknownBlockType).cxx_destruct;
- (void)didTapButton:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool hasDivider; // @synthesize hasDivider;
@property(nonatomic, retain) _TtC11AppStoreKit6Action *action; // @synthesize action;
@property(nonatomic, readonly) _TtC8AppStore17DynamicTypeButton *button; // @synthesize button;

@end

