//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC8AppStore26TodayCardActionOverlayView : UIView
{
    // Error parsing type: , name: label
    // Error parsing type: , name: accessoryView
    // Error parsing type: , name: isExpanded
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, copy) CDUnknownBlockType clickActionHandler;
@property(nonatomic) _Bool wantsCardConsistentMargins;
@property(nonatomic) _Bool isExpanded; // @synthesize isExpanded;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

