//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore15SmallLockupView.h"

@class _TtC8AppStore16DynamicTypeLabel, _TtC8AppStore16ReviewRatingView;

@interface _TtC8AppStore21SmallSearchLockupView : _TtC8AppStore15SmallLockupView
{
    // Error parsing type: , name: userRatingRightMargin
    // Error parsing type: , name: includeRatings
    // Error parsing type: , name: userRatingView
    // Error parsing type: , name: ratingCountLabel
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 backgroundBlur:(id)arg2;
- (void)layoutSubviews;
@property(nonatomic, retain) _TtC8AppStore16DynamicTypeLabel *ratingCountLabel; // @synthesize ratingCountLabel;
@property(nonatomic, retain) _TtC8AppStore16ReviewRatingView *userRatingView; // @synthesize userRatingView;
@property(nonatomic) _Bool includeRatings; // @synthesize includeRatings;
- (void)applyWithSearchLockup:(id)arg1;

@end

