//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIView, _TtC8AppStore11ArtworkView, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore24ActionCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: textLabel
    // Error parsing type: , name: separatorView
    // Error parsing type: , name: accessoryView
    // Error parsing type: , name: accessoryType
    // Error parsing type: , name: lazilyCreatedArtworkView
    // Error parsing type: , name: accessoryAction
}

+ (struct CGSize)itemSizeWithFitting:(struct CGSize)arg1;
+ (double)preferredHeight;
+ (double)artworkTextMargin;
+ (struct CGSize)artworkSize;
+ (double)accessoryMargin;
- (CDUnknownBlockType).cxx_destruct;
- (void)disconnectAccessoryActionFrom:(unsigned long long)arg1 on:(id)arg2;
- (void)connectAccessoryActionTo:(unsigned long long)arg1 on:(id)arg2;
- (void)accessoryDidActionWithSender:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType accessoryAction; // @synthesize accessoryAction;
@property(nonatomic, readonly) struct CGSize preferredArtworkSize;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *artworkView;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isArtworkHidden;
@property(nonatomic, retain) UIView *accessoryView; // @synthesize accessoryView;
@property(nonatomic, readonly) UIView *separatorView; // @synthesize separatorView;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *textLabel; // @synthesize textLabel;
- (void)applyWithAction:(id)arg1;
- (void)didSelect:(id)arg1;

@end

