//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore29StoreCollectionViewController.h"

#import "_TtP11AppStoreKit24SearchHintsPresenterView_-Protocol.h"

@class NSString, UICollectionViewFlowLayout, _TtC8AppStore33SearchHintsCollectionViewDelegate, _TtC8AppStore35SearchHintsCollectionViewDataSource;

@interface _TtC8AppStore25SearchHintsViewController : _TtC8AppStore29StoreCollectionViewController <_TtP11AppStoreKit24SearchHintsPresenterView_>
{
    // Error parsing type: , name: presenter
    // Error parsing type: , name: storeDataProvider
    // Error parsing type: , name: flowLayout
    // Error parsing type: , name: searchHintsCollectionViewDataSource
    // Error parsing type: , name: searchHintsCollectionViewDelegate
    // Error parsing type: , name: isLoading
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)performWithAction:(id)arg1 sender:(id)arg2;
- (void)reloadData;
- (void)showWithUpdateError:(id)arg1;
- (void)hideLoading;
- (void)showLoading;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, retain) _TtC8AppStore33SearchHintsCollectionViewDelegate *searchHintsCollectionViewDelegate; // @synthesize searchHintsCollectionViewDelegate;
@property(nonatomic, retain) _TtC8AppStore35SearchHintsCollectionViewDataSource *searchHintsCollectionViewDataSource; // @synthesize searchHintsCollectionViewDataSource;
@property(nonatomic, retain) UICollectionViewFlowLayout *flowLayout; // @synthesize flowLayout;
@property(nonatomic, copy) NSString *term;

@end

