//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface _TtC8AppStoreP33_4C12C965B12FCBBF31BE3A1652C8D11F8CardView : UIView
{
    // Error parsing type: , name: tintView
    // Error parsing type: , name: viewConstraints
    // Error parsing type: , name: view
    // Error parsing type: , name: tapAction
}

- (CDUnknownBlockType).cxx_destruct;
- (void)didTapFrom:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType tapAction; // @synthesize tapAction;
@property(nonatomic, retain) UIColor *backgroundTintColor;
@property(nonatomic, retain) UIView *view; // @synthesize view;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

