//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVKit/AVPlayerViewController.h>

@class UIViewController;

@interface _TtC8AppStore20PlayerViewController : AVPlayerViewController
{
    // Error parsing type: , name: autoplay
    // Error parsing type: , name: shouldDismissWhenPlaysToEnd
    // Error parsing type: , name: alwaysShowDoneButton
}

- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, readonly) UIViewController *presentingViewController;
@property(nonatomic) _Bool alwaysShowDoneButton; // @synthesize alwaysShowDoneButton;
- (void)playerItemDidPlayToEndWithNotification:(id)arg1;
@property(nonatomic) _Bool shouldDismissWhenPlaysToEnd; // @synthesize shouldDismissWhenPlaysToEnd;
@property(nonatomic) _Bool autoplay; // @synthesize autoplay;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (id)initWithUrl:(id)arg1;
- (void)dealloc;
- (id)initWithPlayer:(id)arg1;

@end

