//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIActivityViewController.h>

@interface _TtC8AppStore22ActivityViewController : UIActivityViewController
{
    // Error parsing type: , name: artworkLoader
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithActivityItems:(id)arg1 applicationActivities:(id)arg2;
- (id)_titleForActivity:(id)arg1;

@end

