//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore17DynamicTypeButton.h"

@interface _TtC8AppStore12HeaderButton : _TtC8AppStore17DynamicTypeButton
{
    // Error parsing type: , name: touchOutsideMargin
}

+ (double)scaledImageDimensionFor:(double)arg1 traitCollection:(id)arg2;
+ (struct CGSize)itemSizeForTitle:(id)arg1 image:(id)arg2 fitting:(struct CGSize)arg3 traits:(id)arg4;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(nonatomic) struct UIEdgeInsets touchOutsideMargin; // @synthesize touchOutsideMargin;
- (void)willMoveToSuperview:(id)arg1;
- (id)init;

@end

