//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITabBarControllerDelegate-Protocol.h"

@interface _TtC8AppStore17TabChangeDelegate : NSObject <UITabBarControllerDelegate>
{
    // Error parsing type: , name: storeDataProvider
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (_Bool)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;

@end

