//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIScrollView, _TtC8AppStore14CardHeaderView;

@interface _TtC8AppStore21CardScrollCoordinator : NSObject
{
    // Error parsing type: , name: headerView
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: isRubberbandingEnabled
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)didScrollIn:(id)arg1;
@property(nonatomic, readonly) struct CGRect currentFrameOfHeaderView;
@property(nonatomic, readonly) struct UIEdgeInsets suggestedContentInset;
@property(nonatomic, readonly) _Bool isRubberbandingEnabled; // @synthesize isRubberbandingEnabled;
@property(nonatomic, readonly) UIScrollView *scrollView; // @synthesize scrollView;
@property(nonatomic, readonly) _TtC8AppStore14CardHeaderView *headerView; // @synthesize headerView;
- (id)initWithHeaderView:(id)arg1 scrollView:(id)arg2 isRubberbandingEnabled:(_Bool)arg3;

@end

