//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _TtC8AppStore11CloseButton;

@interface _TtC8AppStore35ArticleCloseButtonScrollCoordinator : NSObject
{
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: isOverArticle
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)didScrollIn:(id)arg1;
@property(nonatomic) _Bool isOverArticle; // @synthesize isOverArticle;
@property(nonatomic, readonly) _TtC8AppStore11CloseButton *closeButton; // @synthesize closeButton;
- (id)initWithCloseButton:(id)arg1;

@end

