//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "_TtP11AppStoreKit24LoadingPagePresenterView_-Protocol.h"
#import "_TtP8AppStore28FlowPreviewingViewController_-Protocol.h"

@interface _TtC8AppStore25LoadingPageViewController : UIViewController <_TtP11AppStoreKit24LoadingPagePresenterView_, _TtP8AppStore28FlowPreviewingViewController_>
{
    // Error parsing type: , name: presenter
    // Error parsing type: , name: contentViewController
    // Error parsing type: , name: overlayView
    // Error parsing type: , name: startedAsFlowPreview
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)showWithUpdateError:(id)arg1;
- (void)hideLoading;
- (void)showLoading;
- (void)performWithAction:(id)arg1 sender:(id)arg2;
@property(nonatomic) _Bool startedAsFlowPreview; // @synthesize startedAsFlowPreview;
@property(nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

