//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8AppStore29StoreCollectionViewController.h"

#import "_TtP11AppStoreKit26SearchResultsPresenterView_-Protocol.h"

@class _TtC8AppStore16VideoViewManager, _TtC8AppStore24VideoPlaybackCoordinator, _TtC8AppStore35SearchResultsCollectionViewDelegate, _TtC8AppStore37SearchResultsCollectionViewDataSource;

@interface _TtC8AppStore27SearchResultsViewController : _TtC8AppStore29StoreCollectionViewController <_TtP11AppStoreKit26SearchResultsPresenterView_>
{
    // Error parsing type: , name: presenter
    // Error parsing type: , name: searchResultsDelegate
    // Error parsing type: , name: artworkLoader
    // Error parsing type: , name: storeDataProvider
    // Error parsing type: , name: artworkIconFetcher
    // Error parsing type: , name: tableFlowLayout
    // Error parsing type: , name: gridFlowLayout
    // Error parsing type: , name: searchResultsCollectionViewDataSource
    // Error parsing type: , name: searchResultsCollectionViewDelegate
    // Error parsing type: , name: videoPlaybackCoordinator
    // Error parsing type: , name: videoViewManager
    // Error parsing type: , name: noResultsView
    // Error parsing type: , name: activityIndicator
    // Error parsing type: , name: isLoading
    // Error parsing type: , name: isAutoPlayEnabled
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)collectionView:(id)arg1 prefetchItemsAtIndexPaths:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)prefetchArtworkFor:(id)arg1;
- (void)performWithAction:(id)arg1 sender:(id)arg2;
- (void)searchCompleted;
- (void)reloadData;
- (void)showResultsFor:(id)arg1;
- (void)showNoResultsFor:(id)arg1;
@property(nonatomic) _Bool isAutoPlayEnabled; // @synthesize isAutoPlayEnabled;
- (void)showWithUpdateError:(id)arg1;
- (void)showWithNextPageError:(id)arg1;
- (void)hideNextPageLoading;
- (void)showNextPageLoading;
- (void)hideLoading;
- (void)showLoading;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) _Bool isCompact;
@property(nonatomic, readonly) _TtC8AppStore16VideoViewManager *videoViewManager; // @synthesize videoViewManager;
@property(nonatomic, retain) _TtC8AppStore24VideoPlaybackCoordinator *videoPlaybackCoordinator; // @synthesize videoPlaybackCoordinator;
@property(nonatomic, retain) _TtC8AppStore35SearchResultsCollectionViewDelegate *searchResultsCollectionViewDelegate; // @synthesize searchResultsCollectionViewDelegate;
@property(nonatomic, retain) _TtC8AppStore37SearchResultsCollectionViewDataSource *searchResultsCollectionViewDataSource; // @synthesize searchResultsCollectionViewDataSource;

@end

