//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAGradientLayer, NSArray;

@interface _TtC8AppStore12GradientView : UIView
{
    // Error parsing type: , name: kind
}

+ (Class)layerClass;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) struct CGPoint endPoint;
@property(nonatomic) struct CGPoint startPoint;
@property(nonatomic, copy) NSArray *locations;
@property(nonatomic, copy) NSArray *colors;
@property(nonatomic, readonly) CAGradientLayer *gradientLayer;

@end

