//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol _TtP8AppStore28FlowPreviewingViewController_
@property(nonatomic) _Bool startedAsFlowPreview;

@optional
- (void)flowPreviewingDidPop;
- (void)flowPreviewingDidEnterPeek;
@end

