//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtP11AppStoreKit13PresenterView_-Protocol.h"

@protocol _TtP11AppStoreKit26TopChartsPagePresenterView_ <_TtP11AppStoreKit13PresenterView_>
- (void)didReloadSegmentPresentersWithOldCount:(long long)arg1 newCount:(long long)arg2;
- (void)didChangeCategoriesButtonTitle;
- (void)didChangeTitle;
@end

