//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class UICollectionView, UICollectionViewLayout;

@protocol _TtP8AppStore49UICollectionViewDelegateShelfDisplayingFlowLayout_ <UICollectionViewDelegateFlowLayout>
- (long long)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 multiColumnCountAtSection:(long long)arg3;
- (double)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 multiColumnMarginAt:(long long)arg3;
- (_Bool)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 shouldLayoutManageMultiColumnAt:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 insetForBackgroundAtSection:(long long)arg3;
- (_Bool)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 shouldProvideBackgroundAtSection:(long long)arg3;
@end

