//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtP8AppStore49UICollectionViewDelegateShelfDisplayingFlowLayout_-Protocol.h"

@class UICollectionView, _TtC8AppStore29CollectionViewTableFlowLayout;

@protocol _TtP8AppStore37CollectionViewDelegateTableFlowLayout_ <_TtP8AppStore49UICollectionViewDelegateShelfDisplayingFlowLayout_>
- (double)collectionView:(UICollectionView *)arg1 heightForGlobalHeaderViewInTableFlowLayout:(_TtC8AppStore29CollectionViewTableFlowLayout *)arg2;
@end

