//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtP11AppStoreKit13PresenterView_-Protocol.h"

@class NSError;

@protocol _TtP11AppStoreKit22PaginatedPresenterView_ <_TtP11AppStoreKit13PresenterView_>
- (void)showWithNextPageError:(NSError *)arg1;
- (void)hideNextPageLoading;
- (void)showNextPageLoading;
@end

