//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ASDJobManager, NSArray;

@protocol ASDJobManagerObserver <NSObject>

@optional
- (void)jobManager:(ASDJobManager *)arg1 updatedStateOfJobs:(NSArray *)arg2;
- (void)jobManager:(ASDJobManager *)arg1 updatedProgressOfJobs:(NSArray *)arg2;
- (void)jobManager:(ASDJobManager *)arg1 completedJobs:(NSArray *)arg2;
- (void)jobManager:(ASDJobManager *)arg1 changedJobs:(NSArray *)arg2;
@end

