//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb  8 2018 12:17:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITraitEnvironment-Protocol.h"

@interface UIViewController (AppStore1) <UITraitEnvironment>
@property(nonatomic, readonly) double pageColumnWidth;
@property(nonatomic, readonly) double pageColumnMargin;
@property(nonatomic, readonly) struct UIEdgeInsets pageMarginInsets;
@property(nonatomic, readonly) struct CGSize pageContainerSize;
@end

