//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Coordinator;

@interface AbstractPromiseProvider : NSObject
{
    Coordinator *_coordinator;
}

@property(readonly, nonatomic) Coordinator *coordinator; // @synthesize coordinator=_coordinator;
- (void).cxx_destruct;
- (id)description;
- (id)initWithCoordinator:(id)arg1;

@end

