//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DaemonDatabase;

@interface AgentFactory : NSObject
{
    DaemonDatabase *_database;
}

- (void).cxx_destruct;
- (void)currentStatesForPIDs:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)currentStateForPID:(long long)arg1;
- (id)createAgentsForPIDs:(id)arg1 supervisor:(id)arg2;
- (id)createAgentForPID:(long long)arg1 supervisor:(id)arg2;
- (id)initWithDatabase:(id)arg1;

@end

