//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class Agent, AgentProgress, AgentRef, NSString;

@protocol Agent <NSObject>
- (AgentRef *)reference;
- (AgentProgress *)progress;
- (long long)PID;
- (NSString *)currentState;
- (Agent *)agent;
@end

