//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AgentOperation, NSError, SSOperationProgress;

@protocol AgentOperationDelegate <NSObject>

@optional
- (void)operationWillStart:(AgentOperation *)arg1;
- (void)operationFinished:(AgentOperation *)arg1;
- (void)operation:(AgentOperation *)arg1 updatedProgress:(SSOperationProgress *)arg2;
- (void)operation:(AgentOperation *)arg1 failedWithError:(NSError *)arg2;
@end

