//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreServices/SSMetricsMutableEvent.h>

@interface AppMetricsEvent : SSMetricsMutableEvent
{
}

+ (id)_sanitizeError:(id)arg1;
+ (id)_defaultProperties;
- (id)description;
- (_Bool)requiresDiagnosticSendingPermission;
- (void)addInstallationDescription:(id)arg1;
- (void)addApplicationDescription:(id)arg1;
- (id)init;

@end

