//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, NSString;

@interface AppMetricsInstallationDescriptor : NSObject
{
    _Bool _userInitiated;
    NSString *_deltaPackage;
    NSError *_failureReason;
    NSString *_installResult;
    NSString *_installSource;
    NSString *_installType;
    double _lifetimeDuration;
}

+ (id)newDescriptorWithEntity:(id)arg1;
@property(nonatomic) _Bool userInitiated; // @synthesize userInitiated=_userInitiated;
@property(nonatomic) double lifetimeDuration; // @synthesize lifetimeDuration=_lifetimeDuration;
@property(retain, nonatomic) NSString *installType; // @synthesize installType=_installType;
@property(retain, nonatomic) NSString *installSource; // @synthesize installSource=_installSource;
@property(copy, nonatomic) NSString *installResult; // @synthesize installResult=_installResult;
@property(copy, nonatomic) NSError *failureReason; // @synthesize failureReason=_failureReason;
@property(retain, nonatomic) NSString *deltaPackage; // @synthesize deltaPackage=_deltaPackage;
- (void).cxx_destruct;

@end

