//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_xpc_object;

@interface BackgroundTaskRequest : NSObject
{
    NSObject<OS_xpc_object> *_job;
    NSString *_requestIdentifier;
}

+ (id)xpcActivityWithDuration:(long long)arg1;
+ (id)usageCheckJob;
+ (id)updateCheckJobWithDate:(id)arg1 allowsCellular:(_Bool)arg2 requireScreenSleep:(_Bool)arg3 gracePeriod:(_Bool)arg4;
+ (id)requestCheckInWithIdentifier:(id)arg1;
+ (id)cacheDeleteUpdatJobWithInterval:(long long)arg1;
@property(copy, nonatomic) NSString *requestIdentifier; // @synthesize requestIdentifier=_requestIdentifier;
- (void).cxx_destruct;
- (id)copyBackgroundTaskAgentJob;
- (id)initWithBackgroundTaskAgentJob:(id)arg1;
- (id)init;

@end

