//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BagManager : NSObject
{
}

+ (id)_valueForClass:(id)arg1 class:(id)arg2 context:(id)arg3;
+ (id)_valueForClass:(id)arg1 class:(id)arg2;
+ (id)_networkConstraintsForDownloadPolicy:(id)arg1 forceReload:(_Bool)arg2;
+ (id)_loadedURLBagWithContext:(id)arg1 returningError:(id *)arg2;
+ (id)URLForKey:(id)arg1 context:(id)arg2;
+ (id)URLForKey:(id)arg1;
+ (id)numberValueForKey:(id)arg1;
+ (id)networkConstraintsForDownloadPolicy:(id)arg1 forceReload:(_Bool)arg2;
+ (void)loadBagWithCompletion:(CDUnknownBlockType)arg1;
+ (id)dictionaryValueForKey:(id)arg1 context:(id)arg2;
+ (id)dictionaryValueForKey:(id)arg1;
+ (_Bool)boolForKey:(id)arg1;
+ (id)bagDictionary;
+ (id)arrayValueForKey:(id)arg1;

@end

