//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AgentOperation.h"

#import "ISURLOperationDelegate-Protocol.h"

@class DownloadConfiguration, NSArray, NSNumber, NSString, SSDownloadPolicy, SSMemoryEntity;

@interface BuildPromiseConfigurationOperation : AgentOperation <ISURLOperationDelegate>
{
    NSString *_bundleID;
    SSMemoryEntity *_download;
    _Bool _ignoresDownloadHandler;
    NSArray *_mediaAssets;
    SSDownloadPolicy *_policy;
    DownloadConfiguration *_configuration;
}

+ (long long)_URLSessionTaskPriorityForDownloadPriority:(long long)arg1;
+ (long long)_URLSessionTaskPriorityForDownload:(id)arg1;
+ (_Bool)_isDTServiceHubIssuedRequest:(id)arg1;
+ (id)_duetTicketWithBundleIdentifier:(id)arg1;
@property(readonly, nonatomic) DownloadConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (_Bool)_usesStreamingZipDataConsumerForAsset:(id)arg1;
- (_Bool)_shouldFailForDiskSpaceWithAsset:(id)arg1 dataConsumer:(id)arg2;
- (_Bool)_sendsStoreHeadersForAsset:(id)arg1;
- (_Bool)_requiresPoweredPluggedIn;
- (id)_queryLaunchServicesForVariantID;
- (id)_newURLRequestWithAsset:(id)arg1;
- (id)_newStreamingZipOptionsWithAsset:(id)arg1;
- (id)_newDataConsumerDefinitionWithAsset:(id)arg1 destinationPath:(id)arg2;
- (id)_mediaAssetsForDownloadIdentifier:(long long)arg1 variantID:(id)arg2 session:(id)arg3;
- (long long)_loadSizeIfNecessaryForAsset:(id)arg1;
- (id)_downloadKeyCookieWithAsset:(id)arg1;
- (id)_clientIdentifier;
- (id)_bestMediaAsset;
- (long long)_assetSizeFromURLResponse:(id)arg1;
- (_Bool)_assetNeedsDecryption:(id)arg1;
- (_Bool)_assetIsDownloaded:(id)arg1;
- (_Bool)_allowsCellularAccessForAsset:(id)arg1;
- (void)operation:(id)arg1 didReceiveResponse:(id)arg2;
- (long long)operation:(id)arg1 dispositionForAuthenticationChallenge:(id)arg2;
- (void)run;
- (long long)downloadID;
- (id)initWithParentOperation:(id)arg1 downloadID:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentage;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentageCachedResponses;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSessionDuration;
@property(readonly) Class superclass;

@end

