//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JobAgentState.h"

@interface CanceledJobAgentState : JobAgentState
{
}

+ (_Bool)isInactiveState;
- (void)_updateQueue;
- (void)_cancelDownloads;
- (void)onMessage:(id)arg1;
- (void)onEnter;

@end

