//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CleanupManager : NSObject
{
}

- (void)_cleanupUpdates:(_Bool)arg1 updateCount:(long long *)arg2 removeCount:(long long *)arg3;
- (long long)_cleanupUpdates:(_Bool)arg1 removedApps:(id)arg2;
- (void)_cancelJobIDs:(id)arg1;
- (_Bool)garbageCollectionTimerIsExpired;
- (void)garbageCollectDownloads;
- (long long)cleanupUpdatesFollowingInstall:(id)arg1;
- (long long)cleanupUpdates:(id)arg1;
- (_Bool)cleanupStaleUpdateTimerIsExpired;
- (_Bool)cleanupStaleJobsTimerIsExpired;
- (void)cleanupStaleJobs;
- (void)performCleanup;

@end

