//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DownloadAgentMessage.h"

@class NSError;

@interface CompletedDownloadAgentMessage : DownloadAgentMessage
{
    NSError *_error;
    _Bool _result;
}

+ (id)forPID:(long long)arg1 supervisor:(id)arg2;
+ (id)forAgent:(id)arg1;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) _Bool result; // @synthesize result=_result;
- (void).cxx_destruct;
- (id)__apply__result:(_Bool)arg1 error:(id)arg2;

@end

