//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iTunesStore/ISOperation.h>

@class NSObject;
@protocol OS_dispatch_queue;

@interface CompleteCoordinatorsOperation : ISOperation
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

+ (id)_visuallyOrderedBundleIDs;
+ (id)_newPropertyValuesWithBundleID:(id)arg1 metadata:(id)arg2;
+ (id)_newPolicyRequiresThermal:(_Bool)arg1;
+ (void)_importNewJobs:(id)arg1;
+ (_Bool)_enumerateCoordinatorsWithError:(id *)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (void)_runSchedulerWithReason:(id)arg1;
- (void)run;
- (id)init;

@end

