//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AppMetricsMonitor, DownloadAgentSupervisor, JobAgentSupervisor, JobManagerListener, JobScheduler, LaunchServicesObserver, NSCountedSet, NSXPCListener, ODRAppReviewListener, ODRDevtoolsListener, ODRDiagnosticsListener, ODRLaunchServicesListener, ODRServiceDelegate, RequestBroker, RequestListener, SoftwareUpdateListener, StoreQueueListener;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface Daemon : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSObject<OS_dispatch_source> *_jetsamSource;
    JobManagerListener *_jobManagerDelegate;
    NSXPCListener *_jobManagerListener;
    NSCountedSet *_keepAliveAssertions;
    LaunchServicesObserver *_launchServicesObserver;
    ODRAppReviewListener *_odrAppReviewDelegate;
    NSXPCListener *_odrAppReviewListener;
    ODRDiagnosticsListener *_odrCtlDelegate;
    NSXPCListener *_odrCtlListener;
    ODRDevtoolsListener *_odrDevtoolsDelegate;
    NSXPCListener *_odrDevtoolsListener;
    ODRServiceDelegate *_odrFoundationDelegate;
    NSXPCListener *_odrFoundationListener;
    ODRLaunchServicesListener *_odrLaunchServicesDelegate;
    NSXPCListener *_odrLaunchServicesListener;
    RequestBroker *_requestBroker;
    RequestListener *_requestDelegate;
    NSXPCListener *_requestListener;
    NSObject<OS_dispatch_source> *_signalSource;
    NSXPCListener *_softwareUpdateListener;
    SoftwareUpdateListener *_softwareUpdateDelegate;
    NSXPCListener *_storeQueueListener;
    StoreQueueListener *_storeQueueDelegate;
    DownloadAgentSupervisor *_downloadSupervisor;
    JobAgentSupervisor *_jobSupervisor;
    JobScheduler *_jobScheduler;
    AppMetricsMonitor *_appMetricsMonitor;
}

+ (void)_performODRSoftwareUpdateHousekeeping:(_Bool)arg1;
+ (_Bool)isDeviceUnlocked;
+ (id)daemon;
@property(readonly, nonatomic) JobAgentSupervisor *jobSupervisor; // @synthesize jobSupervisor=_jobSupervisor;
@property(readonly, nonatomic) JobScheduler *jobScheduler; // @synthesize jobScheduler=_jobScheduler;
@property(readonly, nonatomic) DownloadAgentSupervisor *downloadSupervisor; // @synthesize downloadSupervisor=_downloadSupervisor;
@property(readonly, nonatomic) AppMetricsMonitor *appMetricsMonitor; // @synthesize appMetricsMonitor=_appMetricsMonitor;
- (void).cxx_destruct;
- (void)_startPipelinesAndEventBus;
- (void)_startODRXPCListeners;
- (void)_setupODRXPCMaintenanceTask;
- (void)_setupODRDataMigrationTask;
- (void)_setupCacheDeleteCoordinator;
- (void)_startXPCListeners;
- (void)_startStoreServicesSupport;
- (void)_setupSignalHandler;
- (void)_startODR;
- (void)_startLaunchServicesObserver;
- (void)_setupLogging;
- (void)_handleDialogReceivedNotification:(id)arg1;
- (id)_createListenerForMachServiceName:(id)arg1 withDelegate:(id)arg2;
- (void)takeKeepAliveAssertion:(id)arg1;
- (void)releaseKeepAliveAssertion:(id)arg1;
- (void)start;
- (_Bool)isMultiUser;
- (void)endShowingDialog;
- (void)beginShowingDialog;
- (void)dealloc;
- (id)init;

@end

