//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DownloadPolicyManager, SSSQLiteDatabase;

@interface DatabaseSession : NSObject
{
    SSSQLiteDatabase *_database;
    DownloadPolicyManager *_policyManager;
}

@property(readonly, nonatomic) DownloadPolicyManager *policyManager; // @synthesize policyManager=_policyManager;
@property(readonly, nonatomic) SSSQLiteDatabase *database; // @synthesize database=_database;
- (void).cxx_destruct;
- (id)initWithSessionDescriptor:(id)arg1;
- (id)init;

@end

