//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSError;

@protocol DataConsumerControl <NSObject>
- (_Bool)truncateWithError:(id *)arg1;
- (_Bool)suspendWithError:(id *)arg1;
- (_Bool)resetWithError:(id *)arg1;
- (_Bool)finishWithError:(id *)arg1;
- (_Bool)failWithReason:(NSError *)arg1 error:(id *)arg2;
- (_Bool)consumeData:(NSData *)arg1 error:(id *)arg2;
@end

