//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AgentState.h"

@interface DownloadAgentState : AgentState
{
}

- (void)transitionRestartDownload:(id)arg1 asset:(id)arg2 error:(id)arg3;
- (void)transitionFailDownload:(id)arg1 asset:(id)arg2 error:(id)arg3;

@end

