//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DownloadAgentTransitionContext.h"

@class NSError, NSNumber;

@interface DownloadStateRestartingAgentTransitionContext : DownloadAgentTransitionContext
{
    long long _assetPID;
    NSError *_error;
    NSNumber *_reason;
}

+ (id)forAgentState:(id)arg1;
- (void).cxx_destruct;
- (_Bool)applyToEntity:(id)arg1 inTransaction:(id)arg2;
- (id)__apply__error:(id)arg1 blockAssetPID:(long long)arg2 withReason:(id)arg3;
- (id)__apply__error:(id)arg1 retryAssetPID:(long long)arg2;

@end

