//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDelegate-Protocol.h"

@class DownloadAgentSupervisor, NSMutableDictionary, NSOperationQueue, NSString;
@protocol OS_dispatch_queue;

@interface DownloadSessionManager : NSObject <NSURLSessionDelegate>
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    DownloadAgentSupervisor *_downloadSupervisor;
    NSOperationQueue *_operationQueue;
    NSMutableDictionary *_sessions;
    NSMutableDictionary *_tasks;
}

- (void).cxx_destruct;
- (id)_taskWithRequest:(id)arg1 inSession:(id)arg2;
- (void)_storeSession:(id)arg1 withTask:(id)arg2;
- (void)_rebuildSessions;
- (id)_sessionWithConfiguration:(id)arg1;
- (id)_delegateForSession:(id)arg1 task:(id)arg2;
- (void)_daemonCommsStart;
- (void)_daemonCommsEnd;
- (void)_completeTask:(id)arg1 inSession:(id)arg2;
- (void)URLSession:(id)arg1 task:(id)arg2 _willSendRequestForEstablishedConnection:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 _willRetryBackgroundDataTask:(id)arg2 withError:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;
- (id)existingDataTaskForDownloadID:(long long)arg1 withDelegate:(id)arg2;
- (id)dataTaskForDownloadID:(long long)arg1 withRequest:(id)arg2 configuration:(id)arg3 delegate:(id)arg4;
- (id)initWithDownloadSupervisor:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

