//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ISOperationQueue, NSArray, NSLock, NSNumber;
@protocol OS_dispatch_queue;

@interface FamilyManager : NSObject
{
    NSNumber *_currentAccountDSID;
    NSArray *_familyAccountIDs;
    NSArray *_familyMembers;
    double _lastFamilyCheck;
    NSLock *_lock;
    NSObject<OS_dispatch_queue> *_notificationQueue;
    ISOperationQueue *_operationQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)_sinfPathForProxy:(id)arg1;
- (id)_operationQueue;
- (void)_handleAccountChangedNotification;
- (void)_clearFamily;
- (id)familyMembers;
- (id)familyAccountIDs;
- (void)_bootstrapFamilyIfNeeded;
- (void)_beginObservingAccountChangeNotification;
- (id)familyPurchaserIDFromSINF:(id)arg1;
- (id)init;

@end

