//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "InstallJobAgentMessage.h"

@class NSError;

@interface FinishInstallJobAgentMessage : InstallJobAgentMessage
{
    NSError *_error;
}

+ (id)forPID:(long long)arg1 supervisor:(id)arg2;
+ (id)forAgent:(id)arg1;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (id)__apply__error:(id)arg1;

@end

