//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SSSQLiteDatabase;

@interface IAPInfoDatabase : NSObject
{
    SSSQLiteDatabase *_database;
}

+ (id)_lastUpdatedPropertyForAccountId:(id)arg1;
+ (id)_serverRevisionPropertyForAccountId:(id)arg1;
+ (_Bool)_setupDatabase:(id)arg1;
- (void).cxx_destruct;
- (id)_valuesStringForIAPInfo:(id)arg1;
- (void)setLastUpdatedTimestamp:(unsigned int)arg1 forAccountId:(id)arg2;
- (unsigned int)lastUpdatedTimestampForAccountId:(id)arg1;
- (void)insertIAPs:(id)arg1 forAccountId:(id)arg2;
- (void)getIAPsWithAdamIds:(id)arg1 accountId:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)getAllIAPsForAccountId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)deleteIAPs:(id)arg1 forAccountId:(id)arg2;
- (void)setDatabaseServerRevision:(unsigned int)arg1 forAccountId:(id)arg2;
- (unsigned int)databaseServerRevisionForAccountId:(id)arg1;
- (void)removeAllIAPsForAccountId:(id)arg1;
- (_Bool)setValue:(id)arg1 forDatabaseProperty:(id)arg2;
- (id)valueForDatabaseProperty:(id)arg1;
- (_Bool)removeValueForDatabaseProperty:(id)arg1;
- (void)readUsingTransactionBlock:(CDUnknownBlockType)arg1;
- (void)readAsyncUsingTransactionBlock:(CDUnknownBlockType)arg1;
- (void)modifyUsingTransactionBlock:(CDUnknownBlockType)arg1;
- (id)initWithDatabaseURL:(id)arg1 readOnly:(_Bool)arg2;
- (id)init;

@end

