//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iTunesStore/ISOperation.h>

#import "ISStoreURLOperationDelegate-Protocol.h"

@class NSArray, NSData, NSNumber, NSString;

@interface IAPInfoItemsRequestOperation : ISOperation <ISStoreURLOperationDelegate>
{
    NSData *_responseData;
    unsigned int _status;
    _Bool _isUpdate;
    NSNumber *_serverRevision;
    NSArray *_iaps;
    NSArray *_deletedIaps;
    NSNumber *_accountId;
}

@property(readonly, nonatomic) NSNumber *accountId; // @synthesize accountId=_accountId;
@property(readonly, nonatomic) NSArray *deletedIaps; // @synthesize deletedIaps=_deletedIaps;
@property(readonly, nonatomic) NSArray *iaps; // @synthesize iaps=_iaps;
@property(readonly, nonatomic) NSNumber *serverRevision; // @synthesize serverRevision=_serverRevision;
@property(readonly, nonatomic) _Bool isUpdate; // @synthesize isUpdate=_isUpdate;
- (void).cxx_destruct;
- (void)operation:(id)arg1 finishedWithOutput:(id)arg2;
- (id)_parseResponseData:(id)arg1;
- (id)_newRequestPropertiesWithBodyData:(id)arg1 url:(id)arg2;
- (id)_newURLOperation:(id)arg1 url:(id)arg2 error:(id *)arg3;
- (id)_itemsUrl;
- (id)_bodyDataForUpdate;
- (void)run;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentage;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentageCachedResponses;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSessionDuration;
@property(readonly) Class superclass;

@end

