//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <InstallCoordination/IXAppInstallCoordinator.h>

@interface IXAppInstallCoordinator (ASDExtensions)
+ (unsigned long long)ASD_intentForClass:(Class)arg1;
+ (Class)ASD_classForIntent:(unsigned long long)arg1;
- (unsigned long long)ASD_intent;
@end

