//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JobError.h"

#import "NSCopying-Protocol.h"

@interface JobFatalError : JobError <NSCopying>
{
}

- (id)copyUserNotification;
- (_Bool)canCoalesceWithError:(id)arg1;

@end

