//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AgentOperation.h"

@class NSString, SSMemoryEntity;

@interface JobPreflightChecksOperation : AgentOperation
{
    NSString *_bundleID;
    SSMemoryEntity *_download;
    SSMemoryEntity *_job;
}

- (void).cxx_destruct;
- (_Bool)_shouldCancel32BitApp;
- (_Bool)_shouldCancelAutomaticDownload;
- (_Bool)_shouldCancelAsDuplicate;
- (_Bool)_itemIsInSoftwareLibrary;
- (void)run;
- (id)initWithParentOperation:(id)arg1 downloadID:(long long)arg2;

@end

