//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DownloadTransaction.h"

@interface JobTransaction : DownloadTransaction
{
}

- (void)_resetDownloadIDs:(id)arg1 userInitiated:(_Bool)arg2;
- (_Bool)_jobIsVaild:(id)arg1;
- (_Bool)_findAndResumeActiveJobForBundleID:(id)arg1 runScheduler:(_Bool)arg2;
- (id)_copyApplicationBundleIDForJob:(id)arg1;
- (id)_addApplicationWithBundleID:(id)arg1 database:(id)arg2;
- (_Bool)shouldNotifyServerJob:(id)arg1 wasCanceled:(_Bool)arg2;
- (_Bool)retryJob:(id)arg1 isUserInitiated:(_Bool)arg2;
- (_Bool)resetJob:(id)arg1 isUserInitiated:(_Bool)arg2;
- (id)mergeJobs:(id)arg1 runScheduler:(_Bool)arg2;
- (id)mergeJobs:(id)arg1;
- (id)importJobs:(id)arg1;
- (id)importDownload:(id)arg1 forJobID:(id)arg2;
- (void)finishJob:(id)arg1 withFinalState:(id)arg2;

@end

