//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSArray, NSString, NSURL, ODRBundleManagedObject;

@interface ODRAssetPackManagedObject : NSManagedObject
{
}

+ (_Bool)deleteAssetPackOnDiskAtURL:(id)arg1;
+ (id)totalSizeOfUnpurgeableAssetPacksForAppBundleID:(id)arg1;
+ (unsigned long long)numberOfAssetPacksForDownloadIdentifier:(long long)arg1;
+ (id)unpurgeableAssetPacksForAppBundleID:(id)arg1;
+ (id)unpurgeableAssetPacks;
+ (id)purgeableAssetPacks;
+ (id)missingPrioritizedAssetPacksForApplicationBundleID:(id)arg1 inBatchSize:(unsigned long long)arg2;
+ (id)missingInitialAssetPacksForApplicationBundleID:(id)arg1 inBatchSize:(unsigned long long)arg2;
+ (id)assetPackskWithLocalURL:(id)arg1;
+ (id)assetPacksForDownloadIdentifier:(long long)arg1;
+ (id)assetPacksForApplicationBundleID:(id)arg1 withPurgeReason:(unsigned long long)arg2 inBatchSize:(unsigned long long)arg3;
+ (id)assetPacksForApplicationBundleID:(id)arg1 withPurgeability:(_Bool)arg2 olderThan:(id)arg3;
+ (id)createAssetPackWithValues:(id)arg1 owningBundleURL:(id)arg2 inManagedObjectContext:(id)arg3;
+ (id)assetPackForBundleID:(id)arg1 applicationID:(id)arg2;
+ (id)assetPackForBundleID:(id)arg1;
+ (id)assetPackForBundleIDPredicate;
- (void)updateUsingValues:(id)arg1 ignoreContentHashes:(_Bool)arg2;
- (unsigned long long)dt_status;
- (id)downloadPercentageComplete;
- (_Bool)deleteAssetPackOnDisk;
- (_Bool)deleteAssetPackAndClearLocalURLForPurgeReason:(unsigned long long)arg1;
- (_Bool)computedEffectiveAlwaysPreserve;
- (id)computedEffectivePreservationPriority;
- (id)calculateLocalURLForEmbeddedAssetWithSourceURL:(id)arg1 bundleID:(id)arg2;
- (void)removeDownRequestUUID:(id)arg1;
- (void)addDownloadRequestUUID:(id)arg1;
- (void)setHashesArray:(id)arg1;
- (id)hashesArray;
@property(copy, nonatomic) NSArray *downloadRequestUUIDs;
@property(copy, nonatomic) NSArray *prefetchRequestUUIDs;
@property(readonly) ODRBundleManagedObject *bundle;
@property(readonly) _Bool isOnDevice;
@property(readonly) NSString *humanReadablePurgeReason;
@property(readonly, nonatomic) NSString *suggestedDestinationPath;
@property(readonly, nonatomic) NSString *suggestedLocalFilename;
@property(copy, nonatomic) NSURL *localURL;
@property(copy, nonatomic) NSURL *sourceURL;

@end

