//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ODRWorkManagedObject.h"

@class NSProgress;

@interface ODRAssetPackDownloadsWork : ODRWorkManagedObject
{
    _Bool _isCancelled;
    NSProgress *progress;
}

+ (id)initiateDownloadOfAssetPack:(id)arg1 forClientAppID:(id)arg2 attributionID:(id)arg3 priority:(double)arg4 isDiscretionary:(_Bool)arg5 jobID:(long long)arg6 completionHandler:(CDUnknownBlockType)arg7;
@property(retain, nonatomic) NSProgress *progress; // @synthesize progress;
- (void).cxx_destruct;
- (void)markAsCompleted;
- (_Bool)isCancelled;
- (void)cancel;
- (void)startWithProgress:(id)arg1 jobID:(long long)arg2 initialDownloadsCompletionHandler:(CDUnknownBlockType)arg3 prioritiziedDownloadsCompletionHandler:(CDUnknownBlockType)arg4;
- (void)start;

@end

