//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue;

@interface ODRBackgroundMaintenance : NSObject
{
    NSOperationQueue *_maintenanceQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)startBackgroundMaintenanceOperations;
- (id)_removeUnusedDownloadUUIDOperation;
- (id)_validateDownloadsOperation;
- (id)_validateOnDeviceAssetPacksOperation;
- (id)_validateOnDeviceManifestsOperation;
- (id)_validateManifestsOperation;
- (id)_launchServicesSyncOperation;
- (id)_workValidationOperation;
- (id)_bundleIDsForUserAndInstalledApps;
- (void)cancelBackgroundMaintenanceOperations;
- (id)_init;

@end

