//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ODRServerProtocol-Protocol.h"

@class NSLock, NSMutableDictionary, NSString;
@protocol ODRClientProtocol;

@interface ODRClient : NSObject <ODRServerProtocol>
{
    id <ODRClientProtocol> _clientProxy;
    NSString *_requestingAppBundleID;
    NSMutableDictionary *_bundleRequestToDownloadRequest;
    NSLock *_readyLock;
    NSMutableDictionary *_sandboxExtensions;
}

+ (void)_removeClient:(id)arg1;
+ (void)refreshManifestIfNecessaryForAssetPackWithID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (id)clientForAppBundleID:(id)arg1;
+ (id)activeClients;
+ (void)initialize;
@property(retain, nonatomic) NSMutableDictionary *sandboxExtensions; // @synthesize sandboxExtensions=_sandboxExtensions;
@property(retain, nonatomic) NSLock *readyLock; // @synthesize readyLock=_readyLock;
@property(copy, nonatomic) NSMutableDictionary *bundleRequestToDownloadRequest; // @synthesize bundleRequestToDownloadRequest=_bundleRequestToDownloadRequest;
@property(readonly) NSString *requestingAppBundleID; // @synthesize requestingAppBundleID=_requestingAppBundleID;
@property(retain, nonatomic) id <ODRClientProtocol> clientProxy; // @synthesize clientProxy=_clientProxy;
- (void).cxx_destruct;
- (void)_unpinAssetPack:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)_sandboxExtensionForBundleID:(id)arg1;
- (void)_pinAssetPack:(id)arg1 priority:(double)arg2 tagsRequest:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)_okToPurgeAssetPack:(id)arg1;
- (id)_issueSandboxExtensionForBundleID:(id)arg1;
- (void)_clearReadyLock;
- (id)_bundlePathForBundleID:(id)arg1;
- (void)setAlwaysPreserved:(_Bool)arg1 forTags:(id)arg2 inBundle:(id)arg3;
- (void)setPreservationPriority:(double)arg1 forTags:(id)arg2 inBundle:(id)arg3;
- (void)okToPurgeAssetPacks:(id)arg1;
- (void)unpinTags:(id)arg1 inBundle:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)setLoadingPriority:(double)arg1 forTags:(id)arg2 inBundle:(id)arg3;
- (void)conditionallyPinTags:(id)arg1 inBundle:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)pinTags:(id)arg1 inBundle:(id)arg2 priority:(double)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)tagStateInBundle:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)beginODRSessionWithBundleURL:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)hello:(CDUnknownBlockType)arg1;
- (id)interface;
- (id)initWithConnection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

