//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"

@class NSManagedObjectContext, NSManagedObjectModel, NSPersistentStoreCoordinator, NSString;

@interface ODRServiceDelegate : NSObject <NSXPCListenerDelegate>
{
    _Bool wasDBRebuilt;
    NSString *_libraryPath;
    NSString *_manifestsPath;
    NSString *_databasePath;
    NSString *_assetPacksPath;
    NSManagedObjectModel *_managedObjectModel;
    NSManagedObjectContext *_managedObjectContext;
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
}

+ (id)sharedDelegate;
@property(retain, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator; // @synthesize persistentStoreCoordinator=_persistentStoreCoordinator;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
@property(retain, nonatomic) NSManagedObjectModel *managedObjectModel; // @synthesize managedObjectModel=_managedObjectModel;
@property(retain, nonatomic) NSString *assetPacksPath; // @synthesize assetPacksPath=_assetPacksPath;
@property(retain, nonatomic) NSString *databasePath; // @synthesize databasePath=_databasePath;
@property(retain, nonatomic) NSString *manifestsPath; // @synthesize manifestsPath=_manifestsPath;
@property(retain, nonatomic) NSString *libraryPath; // @synthesize libraryPath=_libraryPath;
@property(nonatomic) _Bool wasDBRebuilt; // @synthesize wasDBRebuilt;
- (void).cxx_destruct;
- (void)handleApplicationDemotionWithBundleID:(id)arg1;
- (void)handleApplicationUpdateWithBundleID:(id)arg1 manifestData:(id)arg2;
- (void)handleApplicationUninstallWithBundleID:(id)arg1;
- (void)deleteAssetsForBundleID:(id)arg1;
- (void)handleApplicationInstallWithBundleID:(id)arg1;
- (void)syncApplicationTask:(CDUnknownBlockType)arg1;
- (id)_applicationTaskLock;
- (_Bool)isAssetPacksDirectoryEmpty;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (_Bool)ensureAllLibraryPathsExist:(_Bool *)arg1;
- (id)baseURLForODRContent;
- (id)sentinelFileURL;
- (id)systemContainerURL;
@property(readonly, nonatomic) _Bool isDeviceInEduMode;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

