//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface ODRSimulatedDownloadsManager : NSObject
{
    NSMutableArray *_entries;
}

+ (double)_computeSimulatedDownloadTimeForURL:(id)arg1;
+ (unsigned long long)getDirectoryFileSize:(id)arg1;
+ (unsigned long long)simulatedBandwidth;
+ (void)setSimulatedBandwidth:(unsigned long long)arg1;
+ (id)defaultManager;
+ (void)initialize;
- (void).cxx_destruct;
- (id)status;
- (void)removeEntry:(id)arg1;
- (void)removeRequest:(id)arg1;
- (void)addRequest:(id)arg1;
- (id)init;

@end

