//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSNumber, NSSet, NSString, ODRBundleManagedObject;

@interface ODRTagManagedObject : NSManagedObject
{
}

+ (id)createTagWithName:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)tagsForBundleWithID:(id)arg1 matchingTagsInSet:(id)arg2 error:(id *)arg3;
+ (id)tagWithName:(id)arg1 forBundleWithID:(id)arg2;
- (void)setAndReflectPreservationPriority:(id)arg1;
- (void)setAndReflectAlwaysPreserve:(id)arg1;
- (id)percentageDownloaded;
- (id)assetPackSize;
- (unsigned long long)dt_status;

// Remaining properties
@property(retain, nonatomic) NSNumber *alwaysPreserve; // @dynamic alwaysPreserve;
@property(retain, nonatomic) NSSet *assetPacks; // @dynamic assetPacks;
@property(retain, nonatomic) ODRBundleManagedObject *bundle; // @dynamic bundle;
@property(retain, nonatomic) NSNumber *preservationPriority; // @dynamic preservationPriority;
@property(retain, nonatomic) NSString *tagName; // @dynamic tagName;

@end

