//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSData, NSDictionary, NSObject, NSString;
@protocol OS_os_transaction;

@interface ODRWorkManagedObject : NSManagedObject
{
    NSObject<OS_os_transaction> *transaction;
}

@property(retain, nonatomic) NSObject<OS_os_transaction> *transaction; // @synthesize transaction;
- (void).cxx_destruct;
- (id)description;
@property(retain, nonatomic) NSDictionary *context;
- (void)markAsCompleted;
- (void)start;

// Remaining properties
@property(retain, nonatomic) NSString *bundleID; // @dynamic bundleID;
@property(retain, nonatomic) NSData *contextData; // @dynamic contextData;
@property(retain, nonatomic) NSString *type; // @dynamic type;

@end

