//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iTunesStore/ISOperation.h>

@class NSArray, NSMutableArray;

@interface PerformUpdatesOperation : ISOperation
{
    NSMutableArray *_updatesPurchases;
    NSMutableArray *_jobResultItems;
    _Bool _isBackgroundRequest;
    NSArray *_orderedBundleIDs;
}

@property(copy, nonatomic) NSArray *orderedBundleIDs; // @synthesize orderedBundleIDs=_orderedBundleIDs;
@property(nonatomic) _Bool isBackgroundRequest; // @synthesize isBackgroundRequest=_isBackgroundRequest;
- (void).cxx_destruct;
- (_Bool)_runAgentOperation:(id)arg1 returningError:(id *)arg2;
- (void)_setUpdateState:(long long)arg1 forPurchases:(id)arg2 forceNotification:(_Bool)arg3;
- (id)_purchaseWithSoftwareUpdateHelper:(id)arg1 bagKey:(id)arg2 buyParams:(id)arg3;
- (id)_purchaseWithSoftwareUpdate:(id)arg1;
- (void)_performAccountPurchases:(id)arg1;
- (id)_newUpdateWithStoreItemData:(id)arg1 bundleID:(id)arg2;
- (void)_createCoordinatorsForAccounts:(id)arg1;
- (void)_cancelCoordinatorsForBundleIDs:(id)arg1;
- (id)_bagKey;
- (void)run;
@property(readonly, nonatomic) NSArray *jobResults;
- (id)init;

@end

