//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AgentOperation.h"

@class Coordinator, Download, DownloadAsset, MIInstallOptions;

@interface PrepareInstallationOptionsOperation : AgentOperation
{
    DownloadAsset *_asset;
    Coordinator *_coordinator;
    Download *_download;
    MIInstallOptions *_options;
}

@property(readonly, nonatomic) MIInstallOptions *options; // @synthesize options=_options;
- (void).cxx_destruct;
- (id)_newDateFormatter;
- (void)_setAccountPropertiesOnMetadata:(id)arg1;
- (void)_setSoftwarePropertiesOnMetadata:(id)arg1;
- (id)_buildMetadata;
- (void)run;
- (id)initWithParentOperation:(id)arg1 coordinator:(id)arg2 downloadID:(long long)arg3 assetID:(long long)arg4 inDatabaseSession:(id)arg5;

@end

