//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AgentOperation.h"

@class Coordinator, Download, DownloadAsset;

@interface PreparePlaceholderOperation : AgentOperation
{
    DownloadAsset *_asset;
    Coordinator *_coordinator;
    Download *_download;
}

- (void).cxx_destruct;
- (void)run;
- (id)initWithParentOperation:(id)arg1 coordinator:(id)arg2 downloadID:(long long)arg3 inDatabaseSession:(id)arg4;

@end

