//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RequestOperation.h"

@class ASDPurgeableAppRequestOptions;

@interface PurgeableAppRequestOperation : RequestOperation
{
}

- (void)run;

// Remaining properties
@property(readonly, nonatomic) ASDPurgeableAppRequestOptions *options; // @dynamic options;

@end

