//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSDictionary;

@interface PurgeContext : NSObject
{
    _Bool _beyondGracePeriod;
    NSArray *_blacklist;
    NSDate *_cutoffDate;
    NSArray *_pluginBlacklist;
    NSArray *_watchBundles;
    NSDictionary *_windowApps;
}

@property(copy, nonatomic) NSDictionary *windowApps; // @synthesize windowApps=_windowApps;
@property(copy, nonatomic) NSArray *watchBundles; // @synthesize watchBundles=_watchBundles;
@property(copy, nonatomic) NSArray *pluginBlacklist; // @synthesize pluginBlacklist=_pluginBlacklist;
@property(copy, nonatomic) NSDate *cutoffDate; // @synthesize cutoffDate=_cutoffDate;
@property(copy, nonatomic) NSArray *blacklist; // @synthesize blacklist=_blacklist;
@property(nonatomic, getter=isBeyondGracePeriod) _Bool beyondGracePeriod; // @synthesize beyondGracePeriod=_beyondGracePeriod;
- (void).cxx_destruct;

@end

