//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreServices/SSVComplexOperation.h>

@class NSMutableOrderedSet, NSString;

@interface RefreshUpdateDownloadOperation : SSVComplexOperation
{
    NSString *_bundleID;
    NSMutableOrderedSet *_downloads;
}

@property(readonly) NSMutableOrderedSet *downloads; // @synthesize downloads=_downloads;
@property(readonly) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (void).cxx_destruct;
- (void)_setDownloadsWithMetadata:(id)arg1;
- (_Bool)_refreshDownloadUsingUpdate:(id)arg1 application:(id)arg2 error:(id *)arg3;
- (id)_purchaseAutoUpdatePurchaseWithUpdate:(id)arg1 application:(id)arg2;
- (void)main;
- (id)initWithDownloadBundleIdentifier:(id)arg1;

@end

