//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, NSXPCConnection, SSDownloadManager;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface RemoteJobListener : NSObject
{
    NSObject<OS_dispatch_group> *_group;
    NSXPCConnection *_connection;
    SSDownloadManager *_manager;
    NSMutableSet *_observing;
    NSHashTable *_observers;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_sessionTasks;
    NSMutableDictionary *_sessionTasksByIdentifier;
    NSString *_clientID;
}

@property(copy, nonatomic) NSString *clientID; // @synthesize clientID=_clientID;
- (void).cxx_destruct;
- (void)updateDownloadState:(id)arg1;
- (void)updateProgress:(id)arg1;
- (id)initWithConnection:(id)arg1;

@end

