//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASDRequestService-Protocol.h"

@class ClientDescriptor, NSMutableArray, NSOperationQueue, NSXPCConnection;

@interface RequestBrokerClient : NSObject <ASDRequestService>
{
    ClientDescriptor *_client;
    NSXPCConnection *_connection;
    NSMutableArray *_requests;
    NSOperationQueue *_operationQueue;
}

@property(readonly, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain) NSMutableArray *requests; // @synthesize requests=_requests;
@property __weak NSXPCConnection *connection; // @synthesize connection=_connection;
@property(readonly, nonatomic) ClientDescriptor *client; // @synthesize client=_client;
- (void).cxx_destruct;
- (void)_trackRequest:(id)arg1;
- (void)_releaseRequest:(id)arg1;
- (id)description;
- (void)submitRequest:(id)arg1 delegate:(id)arg2 withReplyHandler:(CDUnknownBlockType)arg3;
- (void)cancelAllRequestsWithErrorHandler:(CDUnknownBlockType)arg1;
- (void)queueOperation:(id)arg1;
- (void)invalidate;
- (id)initWithConnection:(id)arg1;

@end

