//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, NSString, RestoreBatchResponse, SSAccount;
@protocol OS_os_transaction;

@interface RestoreContext : NSObject
{
    _Bool _attemptedPrimaryAccountSetup;
    _Bool _failSilentlyForUnknownAccounts;
    NSMutableDictionary *_accountIDsByAppleID;
    long long _cancelRetryAlertState;
    NSArray *_familyAccountIDs;
    NSArray *_familyMembers;
    SSAccount *_primaryAccount;
    NSArray *_restoreItems;
    RestoreBatchResponse *_response;
    NSString *_restoreReason;
    NSMutableDictionary *_restoreAccounts;
    NSObject<OS_os_transaction> *_transaction;
}

@property(retain, nonatomic) NSObject<OS_os_transaction> *transaction; // @synthesize transaction=_transaction;
@property(retain, nonatomic) NSMutableDictionary *restoreAccounts; // @synthesize restoreAccounts=_restoreAccounts;
@property(copy, nonatomic) NSString *restoreReason; // @synthesize restoreReason=_restoreReason;
@property(copy, nonatomic) RestoreBatchResponse *response; // @synthesize response=_response;
@property(copy, nonatomic) NSArray *restoreItems; // @synthesize restoreItems=_restoreItems;
@property(copy, nonatomic) SSAccount *primaryAccount; // @synthesize primaryAccount=_primaryAccount;
@property(copy, nonatomic) NSArray *familyMembers; // @synthesize familyMembers=_familyMembers;
@property(copy, nonatomic) NSArray *familyAccountIDs; // @synthesize familyAccountIDs=_familyAccountIDs;
@property(nonatomic) _Bool failSilentlyForUnknownAccounts; // @synthesize failSilentlyForUnknownAccounts=_failSilentlyForUnknownAccounts;
@property(nonatomic) long long cancelRetryAlertState; // @synthesize cancelRetryAlertState=_cancelRetryAlertState;
@property(nonatomic) _Bool attemptedPrimaryAccountSetup; // @synthesize attemptedPrimaryAccountSetup=_attemptedPrimaryAccountSetup;
@property(retain, nonatomic) NSMutableDictionary *accountIDsByAppleID; // @synthesize accountIDsByAppleID=_accountIDsByAppleID;
- (void).cxx_destruct;
- (id)accountForKey:(id)arg1;
- (id)init;

@end

