//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreServices/SSMemoryEntity.h>

@class NSLock, NSMutableSet, NSSet, NSURLSession;

@interface Session : SSMemoryEntity
{
    NSLock *_lock;
    NSMutableSet *_tasks;
    NSURLSession *_session;
}

+ (id)defaultProperties;
+ (Class)databaseEntityClass;
+ (id)sessionWithConfiguration:(id)arg1 delegate:(id)arg2 delegateQueue:(id)arg3;
@property(retain) NSURLSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (void)_initCommon;
@property(readonly, copy) NSSet *tasks;
- (id)taskForID:(unsigned long long)arg1;
- (void)removeTask:(id)arg1;
- (void)purgeOrphanTasks;
- (id)addTaskWithRequest:(id)arg1;
- (void)addTask:(id)arg1;
- (id)initWithSession:(id)arg1;
- (id)initWithDatabaseEntity:(id)arg1 properties:(id)arg2;

@end

