//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppStoreDaemon/ASDSoftwareUpdate.h>

@interface SoftwareUpdate : ASDSoftwareUpdate
{
    _Bool _offloaded;
}

@property(nonatomic, getter=isOffloaded) _Bool offloaded; // @synthesize offloaded=_offloaded;

@end

