//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreServices/SSMemoryEntity.h>

@interface SSMemoryEntity (TypedProperties)
- (id)valueForProperty:(id)arg1 thatRespondsToSelector:(SEL)arg2;
- (id)valueForProperty:(id)arg1 thatIsClass:(Class)arg2;
- (id)URLForProperty:(id)arg1;
- (id)filterZeroValueForProperty:(id)arg1;
- (id)filterEmptyStringForProperty:(id)arg1;
- (id)dateForProperty:(id)arg1;
- (_Bool)boolForProperty:(id)arg1 ifUnset:(_Bool)arg2;
@end

