//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DownloadJobAgentMessage.h"

@class AgentRef;

@interface StartedDownloadJobAgentMessage : DownloadJobAgentMessage
{
    AgentRef *_download;
}

+ (id)forPID:(long long)arg1 supervisor:(id)arg2;
+ (id)forAgent:(id)arg1;
@property(readonly, nonatomic) AgentRef *download; // @synthesize download=_download;
- (void).cxx_destruct;
- (id)__apply__download:(id)arg1;

@end

