//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iTunesStore/ISOperation.h>

@class NSPredicate;

@interface SystemAppLookupOperation : ISOperation
{
    NSPredicate *_predicate;
    CDUnknownBlockType _responseHandler;
}

+ (_Bool)_errorIsMissingMetadata:(id)arg1;
+ (id)lookupSystemApplicationsWithBundleIDs:(id)arg1;
+ (id)lookupSystemApplicationWithBundleID:(id)arg1;
@property(copy) CDUnknownBlockType responseHandler; // @synthesize responseHandler=_responseHandler;
- (void).cxx_destruct;
- (void)run;
- (id)initWithPredicate:(id)arg1;

@end

