//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UpdatesDatabaseSession.h"

@interface UpdatesDatabaseTransaction : UpdatesDatabaseSession
{
}

- (id)_newUpdateEntityPropertiesWithUpdate:(id)arg1;
- (_Bool)setUpdateState:(long long)arg1 forPurchaseID:(long long)arg2;
- (_Bool)setUpdateState:(long long)arg1 forASDPurchases:(id)arg2;
- (_Bool)setUpdateState:(long long)arg1 forPurchases:(id)arg2;
- (_Bool)setUpdateState:(long long)arg1 forPurchase:(id)arg2;
- (_Bool)setUpdateState:(long long)arg1 forASDPurchase:(id)arg2;
- (_Bool)mergeAvailableUpdates:(id)arg1 withReason:(long long)arg2 availableCount:(long long *)arg3 notifyChanges:(_Bool *)arg4;
- (_Bool)deleteUpdatesInstalledBefore:(double)arg1;

@end

