//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "InternalJob.h"

@interface UpdateJob : InternalJob
{
    _Bool _isAutoUpdate;
}

@property(readonly, nonatomic) _Bool isAutoUpdate; // @synthesize isAutoUpdate=_isAutoUpdate;
@property(readonly, nonatomic) _Bool isPendingApproval;
- (id)initJobAsAutoUpdate:(_Bool)arg1 withActivity:(id)arg2;

@end

