//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WorkspaceTool : NSObject
{
}

+ (id)_placeholderScratch;
+ (_Bool)_placeholderInstalledForBundleID:(id)arg1;
+ (_Bool)uninstallPlaceholderForBundleID:(id)arg1;
+ (id)iTunesMetadataPlistForProxy:(id)arg1;
+ (_Bool)createPlaceholder:(id)arg1 isLaunchProhibited:(_Bool)arg2;
+ (_Bool)createPlaceholder:(id)arg1;
+ (_Bool)cancelProgressForBundleID:(id)arg1;
+ (id)allInstalledApplicationsStoreIDs;

@end

